-- ============================================================
-- Backfill: 'Finance Management 5.0 - Nov 2025.csv'
-- User 9e36aab2-dc6e-4ff6-9ae1-c81e82225424
-- BCA bank bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae | BCA VISA card 2f940480-5908-4c11-9fa1-9ff7a58c65c9
-- Idempotent: safe to re-run (natural-key upserts + deterministic txn ids).
-- Generated by supabase/imports/generate_monthly.py 2025-11
-- ============================================================
BEGIN;

-- NOTE: expenses/transfers are imported with category_id = NULL (this sheet
--       does not categorize spending). Income is the one exception: its
--       category = its Description (e.g. Salary, Bank Interest).

-- Categories (income only; create-or-reuse by name).
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Salary') ON CONFLICT (user_id, name) DO NOTHING;
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'ST012T2') ON CONFLICT (user_id, name) DO NOTHING;
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Bank Interest') ON CONFLICT (user_id, name) DO NOTHING;

-- Budgets for the month (periodic_amount = the spreadsheet's budget).
INSERT INTO budgets (user_id, name, year_month, periodic_amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Food', '2025-11', 3000000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET periodic_amount = EXCLUDED.periodic_amount;
INSERT INTO budgets (user_id, name, year_month, periodic_amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Transport', '2025-11', 2500000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET periodic_amount = EXCLUDED.periodic_amount;
INSERT INTO budgets (user_id, name, year_month, periodic_amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Social', '2025-11', 3000000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET periodic_amount = EXCLUDED.periodic_amount;
INSERT INTO budgets (user_id, name, year_month, periodic_amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Others', '2025-11', 3000000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET periodic_amount = EXCLUDED.periodic_amount;

-- Fixed expenses (Monthly Expenses Details). Only paid ones are imported.
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'KPR', '2025-11', 12299123) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Savings', '2025-11', 7000000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Papa', '2025-11', 5000000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Electricity', '2025-11', 1000000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'First Media', '2025-11', 427350) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'FF XIV', '2025-11', 220000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'IPL VPP', '2025-11', 175000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'PDAM', '2025-11', 100000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Paket Data', '2025-11', 100000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Netflix', '2025-11', 46500) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'IPL Cilejit', '2025-11', 192303) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'ADM BCA', '2025-11', 20000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Youtube Premium', '2025-11', 18315) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;

-- Ensure monthly-balance rows exist so the recalc trigger has rows to update.
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2025-11', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2025-12', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('2f940480-5908-4c11-9fa1-9ff7a58c65c9', '2025-11', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('2f940480-5908-4c11-9fa1-9ff7a58c65c9', '2025-12', 0) ON CONFLICT (account_id, year_month) DO NOTHING;

-- Transactions (125 rows). category_id is set only for income
-- (= its Description); expenses/transfers stay NULL.
-- Per row: (id, acct, xfer, type, amount, date, budget, fixed, category, description).
-- Rows that duplicate a non-monthly-sheet transaction are COMMENTED OUT and
-- marked 'DUPLICATE of non-monthly sheet' — the non-monthly sheet is kept as
-- the single source. Review them before running (uncomment to keep instead).
INSERT INTO transactions
  (id, user_id, account_id, transfer_account_id, type, status,
   amount, description, date, category_id, budget_id, fixed_expense_id)
SELECT
  v.id::uuid, '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid,
  CASE v.acct WHEN 'BCA' THEN 'bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae'::uuid WHEN 'CARD' THEN '2f940480-5908-4c11-9fa1-9ff7a58c65c9'::uuid END,
  CASE v.xfer WHEN 'CARD' THEN '2f940480-5908-4c11-9fa1-9ff7a58c65c9'::uuid ELSE NULL END,
  v.type::transaction_type, 'confirmed',
  v.amount, v.description, v.date::date,
  c.id,   -- category_id      (income only, matched by name; else NULL)
  b.id,   -- budget_id        (matched by name)
  f.id    -- fixed_expense_id (matched by name)
FROM (VALUES
    -- 2025-11-01
    ('dbb7e8ec-9a5f-562d-9561-17c7a0d9804a', 'BCA' , NULL  , 'income'  ,    41106869, '2025-11-01', NULL              , NULL                  , 'Salary'          , 'Salary'),
    ('7c3d3fa1-e12c-595a-a29a-0801ddeb050b', 'BCA' , NULL  , 'expense' ,     5000000, '2025-11-01', NULL              , 'Papa'                , NULL              , NULL),
    ('04e88242-5669-522f-afac-5a47f382240a', 'BCA' , NULL  , 'expense' ,       18315, '2025-11-01', NULL              , 'Youtube Premium'     , NULL              , NULL),
    ('f2e3a2e9-19d8-5dd6-8570-2b9b11a93f76', 'BCA' , NULL  , 'expense' ,       46500, '2025-11-01', NULL              , 'Netflix'             , NULL              , NULL),
    ('5ac20975-a82f-5d11-9582-995258f02bc3', 'BCA' , NULL  , 'expense' ,      175000, '2025-11-01', NULL              , 'IPL VPP'             , NULL              , NULL),
    ('49e3059c-0249-59f9-9fb8-f4c0ffe8487a', 'BCA' , NULL  , 'expense' ,     -100000, '2025-11-01', 'Transport'       , NULL                  , NULL              , NULL),
    ('2c7b0ef5-38ab-5ed0-9580-0afd7ad504f5', 'CARD', NULL  , 'expense' ,      216520, '2025-11-01', NULL              , 'FF XIV'              , NULL              , NULL),
    ('9eee8622-1061-54b1-89d1-c576dc020b8d', 'CARD', NULL  , 'expense' ,      110000, '2025-11-01', 'Social'          , NULL                  , NULL              , NULL),
    ('6a199039-43e8-5d38-b474-8923e4f962d4', 'CARD', NULL  , 'expense' ,       20000, '2025-11-01', 'Social'          , NULL                  , NULL              , NULL),
    ('c4a0bd4f-dde9-5b2e-a94f-584becb01945', 'CARD', NULL  , 'expense' ,       95899, '2025-11-01', 'Others'          , NULL                  , NULL              , 'Nail Clippers'),
    -- 2025-11-02
    ('4ca5ea97-6222-5396-a2f3-8b846ba30eb2', 'CARD', NULL  , 'expense' ,      275500, '2025-11-02', 'Others'          , NULL                  , NULL              , 'Lumbar Support'),
    ('748e73c5-f1ea-521b-9fb0-65abe4ddcf6b', 'CARD', NULL  , 'expense' ,       55000, '2025-11-02', 'Social'          , NULL                  , NULL              , NULL),
    ('01ac1801-4f5c-5e2f-acc1-7c467158ca5d', 'CARD', NULL  , 'expense' ,       36000, '2025-11-02', 'Social'          , NULL                  , NULL              , NULL),
    ('af8f73a4-cd24-51ca-b971-f3fcf930ab36', 'CARD', NULL  , 'expense' ,      104650, '2025-11-02', 'Food'            , NULL                  , NULL              , NULL),
    ('70015a3a-5748-5ef7-aa47-f5f569e985dd', 'CARD', NULL  , 'expense' ,      258639, '2025-11-02', 'Others'          , NULL                  , NULL              , 'Mini Stepper'),
    -- 2025-11-03
    ('8b4aee1f-9bb2-5ad3-903e-08ae6699e7d7', 'BCA' , NULL  , 'expense' ,        5900, '2025-11-03', 'Food'            , NULL                  , NULL              , NULL),
    ('baaa75ca-354b-57a8-b2a9-dd299d260d46', 'CARD', NULL  , 'expense' ,       35000, '2025-11-03', 'Others'          , NULL                  , NULL              , 'ByU'),
    ('2550ca67-a250-59c0-a765-2362490d7b93', 'CARD', NULL  , 'expense' ,       36000, '2025-11-03', 'Food'            , NULL                  , NULL              , NULL),
    ('15668d82-89ec-52d7-a378-1efb037b195f', 'CARD', NULL  , 'expense' ,       25200, '2025-11-03', 'Food'            , NULL                  , NULL              , NULL),
    -- 2025-11-04
    ('45ee2790-5319-582b-9b22-6e8705ee76ab', 'CARD', NULL  , 'expense' ,       77800, '2025-11-04', 'Others'          , NULL                  , NULL              , 'Sensodyne'),
    ('998c2a43-595b-5725-8b32-da04dbe054ce', 'CARD', NULL  , 'expense' ,       69296, '2025-11-04', 'Food'            , NULL                  , NULL              , NULL),
    ('8b7b09a5-8099-54e7-a98c-9745283d1085', 'CARD', NULL  , 'expense' ,       25200, '2025-11-04', 'Food'            , NULL                  , NULL              , NULL),
    -- 2025-11-05
    ('666f4072-3d33-5cdc-a32f-718e120525f5', 'CARD', NULL  , 'expense' ,       36000, '2025-11-05', 'Food'            , NULL                  , NULL              , NULL),
    ('33baf057-b4b1-50dd-8af9-e0f6e53e71f1', 'CARD', NULL  , 'expense' ,       25200, '2025-11-05', 'Food'            , NULL                  , NULL              , NULL),
    ('5df7ef3a-a059-55e6-ae00-4976dc8ffb27', 'CARD', NULL  , 'expense' ,      111400, '2025-11-05', 'Food'            , NULL                  , NULL              , 'GrabMart'),
    ('0c8ded8d-99f0-500f-ad60-4a8a4f4721c1', 'CARD', NULL  , 'expense' ,       74750, '2025-11-05', NULL              , 'PDAM'                , NULL              , NULL),
    -- 2025-11-06
    ('0ab0f6d2-be7e-59e7-b60c-4de79dd4c003', 'CARD', NULL  , 'expense' ,     3033728, '2025-11-06', 'Others'          , NULL                  , NULL              , 'DualSense Edge'),
    -- 2025-11-07
    ('f694b152-94dd-5563-8252-9b9008eed3a5', 'CARD', NULL  , 'expense' ,      152800, '2025-11-07', 'Others'          , NULL                  , NULL              , 'Cable Organizer'),
    ('939fb60d-c895-5efd-b6b3-a2497aa3134e', 'CARD', NULL  , 'expense' ,      107600, '2025-11-07', 'Food'            , NULL                  , NULL              , NULL),
    ('03767a37-7e57-555f-adad-9cd268605895', 'BCA' , NULL  , 'expense' ,     -150000, '2025-11-07', 'Transport'       , NULL                  , NULL              , NULL),
    ('085ae875-e19c-561d-8dd4-89ad9a1203d1', 'BCA' , NULL  , 'expense' ,        2500, '2025-11-07', 'Others'          , NULL                  , NULL              , 'Savings'),
    ('86c1992f-9078-57ea-8a4c-8d8320e9619b', 'BCA' , NULL  , 'expense' ,     7000000, '2025-11-07', NULL              , 'Savings'             , NULL              , NULL),
    -- 2025-11-08
    ('9b06a8ba-aaa5-5d47-acce-f032abfe956f', 'CARD', NULL  , 'expense' ,       94100, '2025-11-08', 'Others'          , NULL                  , NULL              , 'Bluetooth Adapter'),
    ('e2616441-69e0-5140-85e1-e542a57f468a', 'CARD', NULL  , 'expense' ,       14500, '2025-11-08', 'Food'            , NULL                  , NULL              , NULL),
    ('fab4db1d-56a5-5f7f-80e0-97bda3084ce9', 'CARD', NULL  , 'expense' ,       50129, '2025-11-08', 'Others'          , NULL                  , NULL              , 'USB Cable extension'),
    -- 2025-11-09
    ('330711ac-85f9-561f-bcff-fde2ab484de3', 'CARD', NULL  , 'expense' ,        2800, '2025-11-09', 'Others'          , NULL                  , NULL              , 'Electricity'),
    ('d125d121-45cf-5b7e-bb35-da40fbc0e0b9', 'CARD', NULL  , 'expense' ,     1000000, '2025-11-09', NULL              , 'Electricity'         , NULL              , NULL),
    -- 2025-11-10
    ('54386943-f83c-5b9b-821e-0698a139f57a', 'BCA' , NULL  , 'income'  ,      143991, '2025-11-10', NULL              , NULL                  , 'ST012T2'         , 'ST012T2'),
    ('5d5037ae-c6cb-5480-8b6a-3da5072cf719', 'BCA' , 'CARD', 'transfer',     9728100, '2025-11-10', NULL              , NULL                  , NULL              , NULL),
    ('dbde4d1a-c928-5c51-8866-481429c18181', 'CARD', NULL  , 'expense' ,      421800, '2025-11-10', NULL              , 'First Media'         , NULL              , NULL),
    ('491dfece-30ee-5f3a-a32b-51542f6c7a7f', 'CARD', NULL  , 'expense' ,       26000, '2025-11-10', 'Food'            , NULL                  , NULL              , NULL),
    ('fe4c439a-0de6-5434-be68-94652eb5448e', 'CARD', NULL  , 'expense' ,       25600, '2025-11-10', 'Food'            , NULL                  , NULL              , NULL),
    -- 2025-11-11
    ('d1ad0316-1861-5f92-831e-11132c3c3511', 'BCA' , NULL  , 'expense' ,        5900, '2025-11-11', 'Food'            , NULL                  , NULL              , NULL),
    ('e19b62ee-d55d-574d-8ed8-2f1faf3db6fe', 'BCA' , NULL  , 'expense' ,     1000000, '2025-11-11', 'Transport'       , NULL                  , NULL              , 'Emoney'),
    ('58f20a8c-012e-5747-b2d8-40efd7c083da', 'BCA' , NULL  , 'expense' ,        2500, '2025-11-11', 'Others'          , NULL                  , NULL              , 'Emoney'),
    ('24d98840-4dca-5526-9be4-ac60bf1d4608', 'CARD', NULL  , 'expense' ,      401407, '2025-11-11', 'Social'          , NULL                  , NULL              , 'VEGA Agoda'),
    ('fc074036-becf-52d7-b044-a87ef57e8d71', 'CARD', NULL  , 'expense' ,       34000, '2025-11-11', 'Food'            , NULL                  , NULL              , NULL),
    ('bc01a044-6e20-5468-9fe6-1eb9b05dab8d', 'CARD', NULL  , 'expense' ,       42550, '2025-11-11', 'Food'            , NULL                  , NULL              , NULL),
    -- 2025-11-12
    ('64fad4e8-b0dd-5363-8bd1-38268390bcbd', 'BCA' , NULL  , 'expense' ,        5900, '2025-11-12', 'Food'            , NULL                  , NULL              , NULL),
    ('8d142ee6-4286-51b3-a411-6356681e18bf', 'CARD', NULL  , 'expense' ,      185400, '2025-11-12', 'Food'            , NULL                  , NULL              , NULL),
    ('c8282b54-61e7-5605-b647-70747f1f815f', 'CARD', NULL  , 'expense' ,       36000, '2025-11-12', 'Food'            , NULL                  , NULL              , NULL),
    ('376dab0b-a48c-50c6-9aec-3a2cb99eaff7', 'CARD', NULL  , 'expense' ,       19219, '2025-11-12', 'Food'            , NULL                  , NULL              , NULL),
    ('0b385fc4-b1f0-5720-ac30-d4436d2a468a', 'CARD', NULL  , 'expense' ,      111000, '2025-11-12', 'Others'          , NULL                  , NULL              , 'Shopee Ads'),
    -- 2025-11-14
    ('2bafd475-1c09-5c29-b4a5-535fde28db6f', 'CARD', NULL  , 'expense' ,       70000, '2025-11-14', NULL              , 'Paket Data'          , NULL              , NULL),
    -- ('99a88a15-2909-5bdc-82a0-c230a198b794', 'CARD', NULL  , 'expense' ,     1700000, '2025-11-14', NULL              , NULL                  , NULL              , 'Tiket Kereta'),  -- DUPLICATE of non-monthly sheet — commented out for review, see overlaps-2025-11.md
    -- 2025-11-15
    -- ('bb2e96ee-6f5a-575a-8f56-d8a71b36e296', 'CARD', NULL  , 'expense' ,     1740000, '2025-11-15', NULL              , NULL                  , NULL              , 'Tiket Bus'),  -- DUPLICATE of non-monthly sheet — commented out for review, see overlaps-2025-11.md
    ('57ab90cb-e811-5a3f-8433-a8b17780d4b2', 'CARD', NULL  , 'expense' ,       58000, '2025-11-15', 'Social'          , NULL                  , NULL              , NULL),
    ('500ef17b-4362-535e-b81d-090840d39545', 'CARD', NULL  , 'expense' ,      100000, '2025-11-15', 'Social'          , NULL                  , NULL              , NULL),
    ('650afd59-4af8-5d82-9234-3e93c6ceff11', 'CARD', NULL  , 'expense' ,       20000, '2025-11-15', 'Social'          , NULL                  , NULL              , NULL),
    ('f88e26ec-3884-506a-9ea0-616ed9e8d26e', 'CARD', NULL  , 'expense' ,       85000, '2025-11-15', 'Social'          , NULL                  , NULL              , NULL),
    ('eb37302b-a49e-5bdb-aee6-0c4f1d359023', 'CARD', NULL  , 'expense' ,      150000, '2025-11-15', 'Social'          , NULL                  , NULL              , NULL),
    ('342d3c32-b590-56b8-90e9-89acb8cc37c2', 'CARD', NULL  , 'expense' ,       65835, '2025-11-15', 'Social'          , NULL                  , NULL              , NULL),
    ('933ca205-f29f-5d8d-976a-115661595538', 'CARD', NULL  , 'expense' ,       12400, '2025-11-15', 'Social'          , NULL                  , NULL              , NULL),
    -- 2025-11-16
    ('9e5a6a2f-ff6a-5625-b0a5-ef0dd246cf61', 'CARD', NULL  , 'expense' ,      105750, '2025-11-16', 'Others'          , NULL                  , NULL              , 'Tissue'),
    ('fcd6143d-d40c-5257-a0f6-66a2bf443f7e', 'CARD', NULL  , 'expense' ,       60000, '2025-11-16', 'Food'            , NULL                  , NULL              , NULL),
    ('2dc22243-4a4b-56fb-af58-4bb24a2fd9fb', 'BCA' , NULL  , 'expense' ,     -100000, '2025-11-16', 'Transport'       , NULL                  , NULL              , NULL),
    -- ('dcf99def-3471-50fa-938a-51d176642aa0', 'CARD', NULL  , 'expense' ,     3241496, '2025-11-16', NULL              , NULL                  , NULL              , 'Hotel'),  -- DUPLICATE of non-monthly sheet — commented out for review, see overlaps-2025-11.md
    -- 2025-11-17
    ('fe739d12-786e-5f4d-92cd-8bae90f88630', 'BCA' , NULL  , 'expense' ,        5900, '2025-11-17', 'Food'            , NULL                  , NULL              , NULL),
    ('c0dbf938-628b-5ce6-b2fb-8fc1ea29882c', 'CARD', NULL  , 'expense' ,       24000, '2025-11-17', 'Others'          , NULL                  , NULL              , 'GrabUnlimited'),
    ('c8e02c60-684e-586a-8f45-8d514e3f186c', 'CARD', NULL  , 'expense' ,       27608, '2025-11-17', 'Food'            , NULL                  , NULL              , NULL),
    ('aa120076-6838-512c-892a-1f42d997ad7f', 'CARD', NULL  , 'expense' ,      126650, '2025-11-17', 'Food'            , NULL                  , NULL              , NULL),
    -- 2025-11-18
    ('bb1bda04-7afe-52be-af65-b470c296d474', 'CARD', NULL  , 'expense' ,       48286, '2025-11-18', 'Food'            , NULL                  , NULL              , NULL),
    ('b993a3d6-5312-5fc5-b490-75348ad3e5c8', 'CARD', NULL  , 'expense' ,       31320, '2025-11-18', 'Food'            , NULL                  , NULL              , NULL),
    -- 2025-11-19
    ('cba02a4c-db56-5926-932a-ae7895c11b8a', 'BCA' , NULL  , 'expense' ,        5900, '2025-11-19', 'Food'            , NULL                  , NULL              , NULL),
    ('97232e8b-507b-5750-9cd6-59dcc8f2506a', 'CARD', NULL  , 'expense' ,       35000, '2025-11-19', 'Others'          , NULL                  , NULL              , 'ByU'),
    ('1d901a5e-ad0f-574a-8fe0-257359810673', 'CARD', NULL  , 'expense' ,       15000, '2025-11-19', 'Food'            , NULL                  , NULL              , NULL),
    ('bca56c07-6102-5fec-a0f4-08f4958276f8', 'CARD', NULL  , 'expense' ,       35614, '2025-11-19', 'Food'            , NULL                  , NULL              , NULL),
    ('f86e01fe-1105-5acc-ab5f-90465041744b', 'CARD', NULL  , 'expense' ,       31320, '2025-11-19', 'Food'            , NULL                  , NULL              , NULL),
    -- 2025-11-20
    ('a81ef7c4-97f0-5202-98ec-b784d3a79329', 'CARD', NULL  , 'expense' ,      111700, '2025-11-20', 'Food'            , NULL                  , NULL              , NULL),
    ('d2fbdcf7-ee09-52a2-b7a3-52e1c8098d22', 'CARD', NULL  , 'expense' ,      216000, '2025-11-20', 'Food'            , NULL                  , NULL              , NULL),
    -- 2025-11-21
    ('3425460c-35cb-5d74-8ae0-b67dd5f2c2d1', 'BCA' , NULL  , 'expense' ,       20000, '2025-11-21', NULL              , 'ADM BCA'             , NULL              , NULL),
    -- 2025-11-22
    ('66337f1c-96bb-5739-addc-122621c81c82', 'CARD', NULL  , 'expense' ,       16000, '2025-11-22', 'Social'          , NULL                  , NULL              , NULL),
    ('ceb973b4-6437-5ca6-9ec7-50dc19eec6cb', 'CARD', NULL  , 'expense' ,        5000, '2025-11-22', 'Social'          , NULL                  , NULL              , NULL),
    ('4fe38e3f-c978-5361-a400-69ea79296e52', 'CARD', NULL  , 'expense' ,      593762, '2025-11-22', 'Social'          , NULL                  , NULL              , NULL),
    ('009e0654-7d86-5a73-a4b2-fe9c58ee72dd', 'CARD', NULL  , 'expense' ,       40000, '2025-11-22', 'Social'          , NULL                  , NULL              , NULL),
    ('9d9304c9-b5a4-53ac-82c3-c05fb1a0fd2b', 'CARD', NULL  , 'expense' ,       90850, '2025-11-22', 'Food'            , NULL                  , NULL              , NULL),
    ('b87b8acc-3b02-5f43-ae41-8cb286f4f0e8', 'CARD', NULL  , 'expense' ,      180250, '2025-11-22', 'Food'            , NULL                  , NULL              , NULL),
    ('8dd2d7e3-1061-5690-9586-956ad00d5d2c', 'BCA' , NULL  , 'expense' ,      -81000, '2025-11-22', 'Social'          , NULL                  , NULL              , NULL),
    ('f2288c60-cfaf-52be-a7e6-75599300aabb', 'BCA' , NULL  , 'expense' ,      -91245, '2025-11-22', 'Social'          , NULL                  , NULL              , NULL),
    ('732d6e1a-dad2-5049-91a1-62f455c9653c', 'BCA' , NULL  , 'expense' ,      -76230, '2025-11-22', 'Social'          , NULL                  , NULL              , NULL),
    ('8ff14123-a5a3-5183-a8e4-72eb46640a55', 'BCA' , NULL  , 'expense' ,     -119600, '2025-11-22', 'Social'          , NULL                  , NULL              , NULL),
    -- 2025-11-23
    ('6fe8d860-672b-568b-85c8-e51e7bb15798', 'CARD', NULL  , 'expense' ,       69002, '2025-11-23', 'Food'            , NULL                  , NULL              , NULL),
    ('04d5e7eb-0b65-5e09-8fe2-d797bec92dd2', 'BCA' , NULL  , 'expense' ,      192303, '2025-11-23', NULL              , 'IPL Cilejit'         , NULL              , NULL),
    ('81571afd-7fce-5297-a96e-8d1f9f8b0678', 'BCA' , NULL  , 'expense' ,      -84300, '2025-11-23', 'Food'            , NULL                  , NULL              , NULL),
    -- 2025-11-24
    ('bc6ef8b9-d3d2-50bb-9b1d-c62eab6e180f', 'BCA' , NULL  , 'expense' ,      -80000, '2025-11-24', 'Social'          , NULL                  , NULL              , NULL),
    ('32b7ac89-2b09-5e8f-a60d-bcbe4c58db3e', 'BCA' , NULL  , 'expense' ,        5900, '2025-11-24', 'Food'            , NULL                  , NULL              , NULL),
    ('5b5eade9-b4b1-550b-a6ea-685bca218e77', 'CARD', NULL  , 'expense' ,       42000, '2025-11-24', 'Food'            , NULL                  , NULL              , NULL),
    ('58fd3f3e-fc91-5914-9651-510549771921', 'CARD', NULL  , 'expense' ,       31320, '2025-11-24', 'Food'            , NULL                  , NULL              , NULL),
    -- 2025-11-25
    ('8b9fe43b-4a1a-5663-a294-fd39b2dd3590', 'BCA' , NULL  , 'expense' ,    12299124, '2025-11-25', NULL              , 'KPR'                 , NULL              , NULL),
    ('829fb338-1a24-5ce0-bed7-0300f8076c68', 'CARD', NULL  , 'expense' ,       94827, '2025-11-25', 'Food'            , NULL                  , NULL              , NULL),
    ('4a1ef8f1-608a-5449-b00a-197b4092d966', 'CARD', NULL  , 'expense' ,       12500, '2025-11-25', 'Others'          , NULL                  , NULL              , NULL),
    ('fcd18ce3-789a-593c-9473-be80351cfee7', 'CARD', NULL  , 'expense' ,       31320, '2025-11-25', 'Food'            , NULL                  , NULL              , NULL),
    ('1a282bad-1b89-59ff-a30b-38aa7928f225', 'CARD', NULL  , 'expense' ,      299999, '2025-11-25', 'Others'          , NULL                  , NULL              , NULL),
    ('136eb7b9-91ef-5f5d-a71d-196ba9f22d58', 'CARD', NULL  , 'expense' ,       10000, '2025-11-25', 'Others'          , NULL                  , NULL              , 'Bea Materai CC'),
    -- 2025-11-26
    ('9890fb88-0ff7-5f5e-96ec-458734a1d868', 'BCA' , 'CARD', 'transfer',    19660910, '2025-11-26', NULL              , NULL                  , NULL              , NULL),
    ('84945041-faf9-59fa-929c-ed6528cdc181', 'CARD', NULL  , 'expense' ,       73524, '2025-11-26', 'Food'            , NULL                  , NULL              , NULL),
    ('d8cfe7c8-6137-5f67-8359-31d1ab3f9aa3', 'CARD', NULL  , 'expense' ,       31320, '2025-11-26', 'Food'            , NULL                  , NULL              , NULL),
    ('8cc6b3fd-ddf7-5668-97ae-c7203f8b386e', 'CARD', NULL  , 'expense' ,        2000, '2025-11-26', 'Food'            , NULL                  , NULL              , 'Unrecorded tips'),
    ('f30e3fa6-47ac-5c5e-940e-ddbcd146f974', 'CARD', NULL  , 'expense' ,        4910, '2025-11-26', 'Others'          , NULL                  , NULL              , 'Missing record'),
    -- 2025-11-27
    ('a9f9b5fb-1d38-5cf2-a9f2-cb6f61369ccf', 'CARD', NULL  , 'expense' ,      111000, '2025-11-27', 'Others'          , NULL                  , NULL              , 'ShopeeAds'),
    -- 2025-11-28
    ('25dab63a-93eb-5270-8d06-7b5c9a4302f3', 'CARD', NULL  , 'expense' ,      170200, '2025-11-28', 'Food'            , NULL                  , NULL              , NULL),
    -- 2025-11-29
    ('208a6a78-b382-56db-ab28-ba24c4daebb4', 'BCA' , NULL  , 'expense' ,       35000, '2025-11-29', 'Transport'       , NULL                  , NULL              , 'Railink'),
    ('9fc28275-d8f0-5343-82c0-a6805d3fd264', 'BCA' , NULL  , 'income'  ,     7500000, '2025-11-29', NULL              , NULL                  , NULL              , NULL),
    ('16a759a1-7632-5f09-b021-9d50a490e244', 'CARD', NULL  , 'expense' ,       33500, '2025-11-29', 'Social'          , NULL                  , NULL              , NULL),
    ('d70d7697-9d5b-5edf-8d04-0c5be4d607c9', 'CARD', NULL  , 'expense' ,      276500, '2025-11-29', 'Social'          , NULL                  , NULL              , NULL),
    ('217fa926-61db-5977-a13b-5581f55e9032', 'CARD', NULL  , 'expense' ,       60000, '2025-11-29', 'Social'          , NULL                  , NULL              , NULL),
    ('b601217e-dbae-559c-a1ef-55aafc24f44f', 'CARD', NULL  , 'expense' ,       35200, '2025-11-29', 'Social'          , NULL                  , NULL              , NULL),
    ('a9432f24-9e6f-5d1e-a435-baa8dd4fd049', 'CARD', NULL  , 'expense' ,       20000, '2025-11-29', 'Social'          , NULL                  , NULL              , NULL),
    ('119e3085-1190-5ec3-a95a-934b1929ca79', 'CARD', NULL  , 'expense' ,       35000, '2025-11-29', 'Social'          , NULL                  , NULL              , NULL),
    ('824a3885-5d6b-58fa-8c3b-f15045fb5c1d', 'CARD', NULL  , 'expense' ,       25000, '2025-11-29', 'Social'          , NULL                  , NULL              , NULL),
    ('3c8c12b7-47ec-5728-a8de-9925450d924a', 'CARD', NULL  , 'expense' ,       56700, '2025-11-29', 'Others'          , NULL                  , NULL              , 'Groceries'),
    -- 2025-11-30
    ('4deb7365-92d0-5f35-aac1-5636c652920b', 'BCA' , NULL  , 'income'  ,         238, '2025-11-30', NULL              , NULL                  , 'Bank Interest'   , 'Bank Interest'),
    ('703d43c0-4829-5cc9-9f32-bdeef2551345', 'BCA' , NULL  , 'expense' ,      691280, '2025-11-30', 'Food'            , NULL                  , NULL              , 'Budget Adjustment'),
    ('f31f8244-cbeb-55c9-9f87-48b9b16c5922', 'BCA' , NULL  , 'expense' ,     1075523, '2025-11-30', 'Social'          , NULL                  , NULL              , 'Budget Adjustment'),
    ('1b691c50-ab12-52ac-8a90-afcb25fc96ed', 'BCA' , NULL  , 'expense' ,    -1766803, '2025-11-30', 'Others'          , NULL                  , NULL              , 'Budget Adjustment')
  ) AS v(id, acct, xfer, type, amount, date, budget_name, fixed_name, category_name, description)
LEFT JOIN budgets b
  ON b.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid
  AND b.year_month = '2025-11' AND b.name = v.budget_name
LEFT JOIN fixed_expenses f
  ON f.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid AND f.year_month = '2025-11'
  AND f.name = v.fixed_name
LEFT JOIN categories c
  ON c.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid AND c.name = v.category_name
ON CONFLICT (id) DO NOTHING;

COMMIT;
