-- ============================================================
-- Budget carry-over seed for 2025-12 -> feeds carry_in of 2026-01.
-- Values = Row 2 of 'Finance Management 5.0 - Jan 2026.csv'. Reproduces that sheet's Row 3.
-- User 9e36aab2-dc6e-4ff6-9ae1-c81e82225424 | dummy expenses on BCA bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae (DO move the BCA balance).
-- Run this BEFORE the per-month imports. Idempotent.
-- Generated by supabase/imports/generate_carryover_seed.py
-- ============================================================
BEGIN;

-- 2025-12 budgets (standard periodic; carry-over chains into 2026-01).
INSERT INTO budgets (user_id, name, year_month, periodic_amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Food', '2025-12', 3000000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET periodic_amount = EXCLUDED.periodic_amount;
INSERT INTO budgets (user_id, name, year_month, periodic_amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Transport', '2025-12', 2500000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET periodic_amount = EXCLUDED.periodic_amount;
INSERT INTO budgets (user_id, name, year_month, periodic_amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Social', '2025-12', 3000000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET periodic_amount = EXCLUDED.periodic_amount;
INSERT INTO budgets (user_id, name, year_month, periodic_amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Others', '2025-12', 2284520) ON CONFLICT (user_id, name, year_month) DO UPDATE SET periodic_amount = EXCLUDED.periodic_amount;

INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2025-12', 0) ON CONFLICT (account_id, year_month) DO NOTHING;

-- Dummy BCA expense per envelope: periodic - spend = remaining (= Row 2).
INSERT INTO transactions
  (id, user_id, account_id, transfer_account_id, type, status,
   amount, description, date, category_id, budget_id, fixed_expense_id)
SELECT
  v.id::uuid, '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid, 'bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae'::uuid, NULL,
  'expense'::transaction_type, 'confirmed',
  v.amount, v.description, v.date::date,
  NULL, b.id, NULL
FROM (VALUES
    ('1be69a89-1779-5f59-8a39-2370a0c42533', 3000000, '2025-12-01', 'Carry-over seed -> 2026-01', 'Food'),
    ('710f8803-71fc-5a61-a887-60051b849341', 160365, '2025-12-01', 'Carry-over seed -> 2026-01', 'Transport'),
    ('d78275fe-f6fc-5aac-8c1f-01258c34de71', 3666260, '2025-12-01', 'Carry-over seed -> 2026-01', 'Social'),
    ('bf45e45b-a4f9-569d-8f9c-095c1b4ff379', 2817424, '2025-12-01', 'Carry-over seed -> 2026-01', 'Others')
  ) AS v(id, amount, date, description, budget_name)
LEFT JOIN budgets b ON b.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid AND b.year_month = '2025-12' AND b.name = v.budget_name
ON CONFLICT (id) DO NOTHING;

COMMIT;
