-- ============================================================
-- Backfill: 'Finance Management 5.0 - Jan 2026.csv'
-- User 9e36aab2-dc6e-4ff6-9ae1-c81e82225424
-- BCA bank bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae | BCA VISA card 2f940480-5908-4c11-9fa1-9ff7a58c65c9
-- Idempotent: safe to re-run (natural-key upserts + deterministic txn ids).
-- Generated by supabase/imports/generate_monthly.py 2026-01
-- ============================================================
BEGIN;

-- NOTE: expenses/transfers are imported with category_id = NULL (this sheet
--       does not categorize spending). Income is the one exception: its
--       category = its Description (e.g. Salary, Bank Interest).

-- Categories (income only; create-or-reuse by name).
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Salary') ON CONFLICT (user_id, name) DO NOTHING;
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'ST012T2') ON CONFLICT (user_id, name) DO NOTHING;
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Bank Interest') ON CONFLICT (user_id, name) DO NOTHING;

-- Budgets for the month (periodic_amount = the spreadsheet's budget).
INSERT INTO budgets (user_id, name, year_month, periodic_amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Food', '2026-01', 3000000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET periodic_amount = EXCLUDED.periodic_amount;
INSERT INTO budgets (user_id, name, year_month, periodic_amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Transport', '2026-01', 2500000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET periodic_amount = EXCLUDED.periodic_amount;
INSERT INTO budgets (user_id, name, year_month, periodic_amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Social', '2026-01', 3000000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET periodic_amount = EXCLUDED.periodic_amount;
INSERT INTO budgets (user_id, name, year_month, periodic_amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Others', '2026-01', 2284520) ON CONFLICT (user_id, name, year_month) DO UPDATE SET periodic_amount = EXCLUDED.periodic_amount;

-- Fixed expenses (Monthly Expenses Details). Only paid ones are imported.
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'KPR', '2026-01', 12299123) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Papa', '2026-01', 5000000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Electricity', '2026-01', 1000000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'First Media', '2026-01', 427350) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'FF XIV', '2026-01', 220000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'IPL Cilejit', '2026-01', 192303) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'IPL VPP', '2026-01', 175000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'PDAM', '2026-01', 100000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Paket Data', '2026-01', 100000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Netflix', '2026-01', 46500) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Youtube Premium', '2026-01', 18315) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;

-- Ensure monthly-balance rows exist so the recalc trigger has rows to update.
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2026-01', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2026-02', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('2f940480-5908-4c11-9fa1-9ff7a58c65c9', '2026-01', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('2f940480-5908-4c11-9fa1-9ff7a58c65c9', '2026-02', 0) ON CONFLICT (account_id, year_month) DO NOTHING;

-- Transactions (122 rows). category_id is set only for income
-- (= its Description); expenses/transfers stay NULL.
-- Per row: (id, acct, xfer, type, amount, date, budget, fixed, category, description).
-- Rows that duplicate a non-monthly-sheet transaction are COMMENTED OUT and
-- marked 'DUPLICATE of non-monthly sheet' — the non-monthly sheet is kept as
-- the single source. Review them before running (uncomment to keep instead).
INSERT INTO transactions
  (id, user_id, account_id, transfer_account_id, type, status,
   amount, description, date, category_id, budget_id, fixed_expense_id)
SELECT
  v.id::uuid, '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid,
  CASE v.acct WHEN 'BCA' THEN 'bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae'::uuid WHEN 'CARD' THEN '2f940480-5908-4c11-9fa1-9ff7a58c65c9'::uuid END,
  CASE v.xfer WHEN 'CARD' THEN '2f940480-5908-4c11-9fa1-9ff7a58c65c9'::uuid ELSE NULL END,
  v.type::transaction_type, 'confirmed',
  v.amount, v.description, v.date::date,
  c.id,   -- category_id      (income only, matched by name; else NULL)
  b.id,   -- budget_id        (matched by name)
  f.id    -- fixed_expense_id (matched by name)
FROM (VALUES
    -- 2026-01-01
    ('8ad14649-97a6-5c26-ac90-98be4207a24b', 'BCA' , NULL  , 'income'  ,    50141799, '2026-01-01', NULL              , NULL                  , 'Salary'          , 'Salary'),
    ('5eb5860e-61ee-5ca1-859f-8190d659f812', 'BCA' , NULL  , 'expense' ,     5000000, '2026-01-01', NULL              , 'Papa'                , NULL              , NULL),
    ('22e27d25-e10f-5e8e-a63b-2e9707f534dd', 'BCA' , NULL  , 'expense' ,       18315, '2026-01-01', NULL              , 'Youtube Premium'     , NULL              , NULL),
    ('bc2b5240-65f0-52d6-b18d-5cf11c35dc45', 'BCA' , NULL  , 'expense' ,       46500, '2026-01-01', NULL              , 'Netflix'             , NULL              , NULL),
    ('b4bc1b8f-0c47-5b9a-abb7-81629594e8cd', 'BCA' , NULL  , 'expense' ,      175000, '2026-01-01', NULL              , 'IPL VPP'             , NULL              , NULL),
    -- 2026-01-02
    ('0f1a747e-a6be-5509-b466-beebb0103e45', 'CARD', NULL  , 'expense' ,      518600, '2026-01-02', 'Others'          , NULL                  , NULL              , 'Cards'),
    ('5af6ae16-1a9c-57d5-b1dd-ce552b149c35', 'CARD', NULL  , 'expense' ,       97000, '2026-01-02', 'Others'          , NULL                  , NULL              , 'Cards'),
    ('f46394c6-c874-554f-b47c-670dda37f82c', 'CARD', NULL  , 'expense' ,      132400, '2026-01-02', 'Food'            , NULL                  , NULL              , NULL),
    ('fb835b96-be64-5b52-b287-6a0b082fcc8f', 'CARD', NULL  , 'expense' ,      354400, '2026-01-02', 'Others'          , NULL                  , NULL              , 'Cards'),
    -- 2026-01-03
    ('adacdf44-3c02-5153-a89d-06973c27089e', 'CARD', NULL  , 'expense' ,       20000, '2026-01-03', 'Social'          , NULL                  , NULL              , NULL),
    ('c797450a-d50a-55bf-9234-d786920c48c2', 'CARD', NULL  , 'expense' ,       20000, '2026-01-03', 'Social'          , NULL                  , NULL              , NULL),
    ('2f776f59-8249-5661-8c7a-c5af224b414a', 'CARD', NULL  , 'expense' ,      129000, '2026-01-03', 'Social'          , NULL                  , NULL              , NULL),
    ('bc3260f4-de19-515f-8d6a-c9ed82a204fa', 'CARD', NULL  , 'expense' ,       17500, '2026-01-03', 'Social'          , NULL                  , NULL              , NULL),
    ('14d42b3e-b73a-550f-9f68-b53411c3ae95', 'CARD', NULL  , 'expense' ,      160598, '2026-01-03', 'Others'          , NULL                  , NULL              , 'T-Shirt'),
    ('f1f6e673-d0f9-593d-be64-b495371aace7', 'BCA' , NULL  , 'expense' ,     1000000, '2026-01-03', 'Transport'       , NULL                  , NULL              , NULL),
    ('8d015c5d-62fe-5a98-b69c-91c198b9f081', 'BCA' , NULL  , 'expense' ,        1500, '2026-01-03', 'Others'          , NULL                  , NULL              , NULL),
    -- 2026-01-04
    ('4fa73ff7-da14-537b-a336-516264a0cf51', 'CARD', NULL  , 'expense' ,       75000, '2026-01-04', 'Social'          , NULL                  , NULL              , NULL),
    ('be772c64-acab-5fc4-a929-89f4689105de', 'CARD', NULL  , 'expense' ,       40000, '2026-01-04', 'Social'          , NULL                  , NULL              , NULL),
    -- ('024678c4-6e08-584a-895f-3d71b7d45bc8', 'CARD', NULL  , 'expense' ,      599000, '2026-01-04', NULL              , NULL                  , NULL              , NULL),  -- DUPLICATE of non-monthly sheet — commented out for review, see overlaps-2026-01.md
    -- ('d79d8288-8bc2-516d-abcb-8776b739d30b', 'CARD', NULL  , 'expense' ,      247401, '2026-01-04', NULL              , NULL                  , NULL              , NULL),  -- DUPLICATE of non-monthly sheet — commented out for review, see overlaps-2026-01.md
    ('5a517993-db14-5865-bd5c-1eb73e2a198a', 'CARD', NULL  , 'expense' ,       75250, '2026-01-04', NULL              , 'PDAM'                , NULL              , NULL),
    ('50635139-dfef-5c58-ab49-04604bc43141', 'CARD', NULL  , 'expense' ,      500000, '2026-01-04', 'Transport'       , NULL                  , NULL              , NULL),
    ('5956cf7f-1493-5819-931c-024c50d8068f', 'CARD', NULL  , 'expense' ,        3100, '2026-01-04', 'Others'          , NULL                  , NULL              , NULL),
    -- 2026-01-05
    ('47bfaf93-a18f-5b7e-a7a0-3dcadf3e2ce8', 'CARD', NULL  , 'expense' ,      111000, '2026-01-05', 'Others'          , NULL                  , NULL              , 'ShopeeAds'),
    ('b5cd920a-675b-5971-8762-a9b1eb27e6a1', 'CARD', NULL  , 'expense' ,      157600, '2026-01-05', 'Food'            , NULL                  , NULL              , 'Groceries'),
    ('b604a1b4-fe25-5dac-b7ac-c6844a0e46e0', 'CARD', NULL  , 'expense' ,       21000, '2026-01-05', 'Food'            , NULL                  , NULL              , NULL),
    ('dbce2758-1b95-5624-a57b-3a32a2015622', 'CARD', NULL  , 'expense' ,       35000, '2026-01-05', 'Food'            , NULL                  , NULL              , NULL),
    -- 2026-01-06
    ('ab0f88d8-a139-5e13-ab13-44d912eca4a5', 'CARD', NULL  , 'expense' ,       42000, '2026-01-06', 'Food'            , NULL                  , NULL              , NULL),
    ('72cffe04-b19c-57f2-b56c-2ba1123dee67', 'CARD', NULL  , 'expense' ,       24000, '2026-01-06', 'Food'            , NULL                  , NULL              , NULL),
    -- 2026-01-07
    ('227fe54c-ce7a-5b9e-bca2-9a087050d396', 'CARD', NULL  , 'expense' ,       42000, '2026-01-07', 'Food'            , NULL                  , NULL              , NULL),
    ('dbb3b58e-8954-569b-9b41-d2ab4095d72c', 'BCA' , NULL  , 'expense' ,        5900, '2026-01-07', 'Food'            , NULL                  , NULL              , NULL),
    -- 2026-01-08
    ('2f43e587-f977-5dda-b035-b153c92934a4', 'BCA' , NULL  , 'expense' ,       43360, '2026-01-08', NULL              , NULL                  , NULL              , 'IPL Alegria'),
    -- 2026-01-09
    ('40df06ea-3ba1-5ae0-93e1-accbf36a167e', 'CARD', NULL  , 'expense' ,      110500, '2026-01-09', 'Food'            , NULL                  , NULL              , NULL),
    ('69f8f935-62db-5325-973b-90ad3b966029', 'CARD', NULL  , 'expense' ,      309311, '2026-01-09', 'Social'          , NULL                  , NULL              , NULL),
    ('60cd87b8-0c44-5888-9d0c-e0904485d54b', 'CARD', NULL  , 'expense' ,        1000, '2026-01-09', 'Others'          , NULL                  , NULL              , 'Paket Data'),
    ('d7b0fba3-e28a-5d40-ae54-255d74cf0e77', 'CARD', NULL  , 'expense' ,       50000, '2026-01-09', NULL              , 'Paket Data'          , NULL              , NULL),
    ('4bc4bd7a-f764-5af6-92c2-a601cfb316b7', 'BCA' , 'CARD', 'transfer',     1403889, '2026-01-09', NULL              , NULL                  , NULL              , NULL),
    -- 2026-01-10
    ('017f00bd-8ff9-5e41-922c-25f9a178332c', 'CARD', NULL  , 'expense' ,      379900, '2026-01-10', 'Others'          , NULL                  , NULL              , NULL),
    ('85a743ef-42ba-5d76-b16f-d951b0934efd', 'CARD', NULL  , 'expense' ,       75000, '2026-01-10', 'Social'          , NULL                  , NULL              , NULL),
    ('45fdd01b-5877-5460-8456-a59b18628672', 'CARD', NULL  , 'expense' ,       77000, '2026-01-10', 'Social'          , NULL                  , NULL              , NULL),
    ('5cc1de4a-19a6-5dbc-871e-f5af4ece7f74', 'CARD', NULL  , 'expense' ,       20000, '2026-01-10', 'Social'          , NULL                  , NULL              , NULL),
    ('20caff20-87b8-57cf-ac93-5b7423561dc2', 'CARD', NULL  , 'expense' ,       25000, '2026-01-10', 'Social'          , NULL                  , NULL              , NULL),
    ('d10d7220-19ae-5a9b-8291-0a813c902e22', 'CARD', NULL  , 'expense' ,       33000, '2026-01-10', 'Social'          , NULL                  , NULL              , NULL),
    -- 2026-01-11
    ('b5c8f714-a6ac-5489-ab80-c4d42c48861f', 'CARD', NULL  , 'expense' ,       51000, '2026-01-11', 'Social'          , NULL                  , NULL              , NULL),
    ('b6f49c84-e7cf-5ead-86bb-13b977959435', 'CARD', NULL  , 'expense' ,      110500, '2026-01-11', 'Food'            , NULL                  , NULL              , NULL),
    -- 2026-01-12
    ('2c9607db-a0d8-548e-8da8-ffe65add0904', 'CARD', NULL  , 'expense' ,       92725, '2026-01-12', 'Others'          , NULL                  , NULL              , 'Tissue Basah'),
    ('901502d4-ad78-5d3f-94aa-a1abf08549b3', 'CARD', NULL  , 'expense' ,       24000, '2026-01-12', 'Others'          , NULL                  , NULL              , NULL),
    ('3241e563-ab4f-57c8-94ac-1186273b8e62', 'CARD', NULL  , 'expense' ,       67000, '2026-01-12', 'Food'            , NULL                  , NULL              , NULL),
    ('2a89bdaf-7373-5860-bf0e-025122226eac', 'CARD', NULL  , 'expense' ,       34000, '2026-01-12', 'Food'            , NULL                  , NULL              , NULL),
    ('277a74c4-44dd-576a-8861-b68bec1e0fa8', 'BCA' , NULL  , 'income'  ,      143991, '2026-01-12', NULL              , NULL                  , 'ST012T2'         , 'ST012T2'),
    ('b96722af-2204-5369-a0de-ab0d30ff2c90', 'BCA' , NULL  , 'expense' ,        5900, '2026-01-12', 'Food'            , NULL                  , NULL              , NULL),
    -- 2026-01-13
    ('10422ade-4a03-5711-aa89-8c91b057e972', 'CARD', NULL  , 'expense' ,       42000, '2026-01-13', 'Food'            , NULL                  , NULL              , NULL),
    -- 2026-01-14
    ('a28f13f8-7fa6-50a2-94fb-7fe567db9900', 'CARD', NULL  , 'expense' ,       75000, '2026-01-14', NULL              , NULL                  , NULL              , 'ByU'),
    ('48057845-e228-5275-86d6-40f6a659f7f5', 'CARD', NULL  , 'expense' ,       26000, '2026-01-14', 'Food'            , NULL                  , NULL              , NULL),
    ('cb6faa9c-a52a-5742-8ec8-439a3d0e81e3', 'CARD', NULL  , 'expense' ,       13356, '2026-01-14', 'Others'          , NULL                  , NULL              , 'Travel Pass SGD 1'),
    ('083b507b-2bf6-5921-9161-72abc43baea2', 'CARD', NULL  , 'expense' ,       12000, '2026-01-14', 'Others'          , NULL                  , NULL              , 'Travel Pass'),
    -- 2026-01-15
    ('7e1acc40-0354-5741-a9a3-391bdda3528f', 'CARD', NULL  , 'expense' ,      421800, '2026-01-15', NULL              , 'First Media'         , NULL              , NULL),
    ('d1e02c1a-a2e9-5fc9-80b5-b715e11c0792', 'CARD', NULL  , 'expense' ,       47862, '2026-01-15', 'Food'            , NULL                  , NULL              , NULL),
    ('3b0a5290-264b-5093-969c-26a85f733a4a', 'CARD', NULL  , 'expense' ,      104625, '2026-01-15', 'Food'            , NULL                  , NULL              , NULL),
    ('b2cfb8bc-b078-541c-be16-fd865f0c786f', 'CARD', NULL  , 'expense' ,      345955, '2026-01-15', 'Social'          , NULL                  , NULL              , NULL),
    -- 2026-01-16
    ('e306b620-b3e4-58b8-895b-7563b9c475d4', 'CARD', NULL  , 'expense' ,      407728, '2026-01-16', 'Others'          , NULL                  , NULL              , 'Chess Deck'),
    ('c14a00ab-024d-5b6c-96a9-dceb3557c295', 'BCA' , NULL  , 'expense' ,       20000, '2026-01-16', 'Others'          , NULL                  , NULL              , 'ADM BCA'),
    -- 2026-01-17
    ('9d323950-bd44-57c4-8b4d-87b0a440f330', 'CARD', NULL  , 'expense' ,      216000, '2026-01-17', 'Social'          , NULL                  , NULL              , NULL),
    ('d84b91c1-3e0d-5547-95fe-23708b12f0a4', 'CARD', NULL  , 'expense' ,       20000, '2026-01-17', 'Social'          , NULL                  , NULL              , NULL),
    -- 2026-01-18
    ('4c99912d-e5fd-5b83-979d-2babd0b6cb8e', 'CARD', NULL  , 'expense' ,      380000, '2026-01-18', 'Social'          , NULL                  , NULL              , NULL),
    ('3223796c-403f-5f82-a33f-2de308e8cf28', 'BCA' , NULL  , 'expense' ,     1000000, '2026-01-18', 'Transport'       , NULL                  , NULL              , 'EMoney'),
    ('6f48c825-54b9-591b-92e7-e064be12b912', 'BCA' , NULL  , 'expense' ,        1500, '2026-01-18', 'Others'          , NULL                  , NULL              , 'EMoney'),
    -- 2026-01-19
    ('57f2c5b8-95fa-584b-bbda-c7f7b2ee8a25', 'CARD', NULL  , 'expense' ,       98000, '2026-01-19', NULL              , 'Paket Data'          , NULL              , NULL),
    ('9882c77e-9983-554f-b0ed-68fc8a1879de', 'CARD', NULL  , 'expense' ,       70300, '2026-01-19', 'Others'          , NULL                  , NULL              , 'Obat Kolestrol + Asam Urat'),
    ('5c5a9073-0a30-5081-a2bb-0f1184571e61', 'CARD', NULL  , 'expense' ,      140800, '2026-01-19', 'Food'            , NULL                  , NULL              , NULL),
    -- 2026-01-20
    ('c65d4e37-a09a-5d91-95b0-0f65923a51ce', 'CARD', NULL  , 'expense' ,      179100, '2026-01-20', 'Food'            , NULL                  , NULL              , NULL),
    ('70694bdd-9851-57b1-9626-eee1ccd35587', 'CARD', NULL  , 'expense' ,       29000, '2026-01-20', 'Food'            , NULL                  , NULL              , NULL),
    ('e8dac4d7-699b-5d14-871c-b772fde7e36e', 'CARD', NULL  , 'expense' ,       20000, '2026-01-20', 'Food'            , NULL                  , NULL              , NULL),
    ('000ceb98-4b28-557a-add0-168a2a10b18c', 'CARD', NULL  , 'expense' ,        2800, '2026-01-20', 'Others'          , NULL                  , NULL              , 'Electricity'),
    ('f7c14264-35da-598d-924f-3b045350590b', 'CARD', NULL  , 'expense' ,     1000000, '2026-01-20', NULL              , 'Electricity'         , NULL              , NULL),
    ('b5bb2bff-0df3-5927-b84c-455c86728284', 'BCA' , 'CARD', 'transfer',     6700000, '2026-01-20', NULL              , NULL                  , NULL              , NULL),
    -- 2026-01-21
    ('d67f025f-60b9-55a2-8421-458f007512f8', 'CARD', NULL  , 'expense' ,       21000, '2026-01-21', 'Food'            , NULL                  , NULL              , NULL),
    ('89a41188-d2c2-5f68-94c7-452161ad2517', 'BCA' , NULL  , 'expense' ,        5900, '2026-01-21', 'Food'            , NULL                  , NULL              , NULL),
    -- 2026-01-22
    ('7dc3ecde-62f3-5e4d-a4e5-c2b88c79f917', 'CARD', NULL  , 'expense' ,       71373, '2026-01-22', 'Food'            , NULL                  , NULL              , NULL),
    -- 2026-01-23
    ('a1cf9e6f-e617-5dc1-920c-dbe16ed1b07d', 'CARD', NULL  , 'expense' ,       42000, '2026-01-23', 'Food'            , NULL                  , NULL              , NULL),
    ('9e2223df-7c8e-5946-99ce-ce6ce4e88be7', 'CARD', NULL  , 'expense' ,       28000, '2026-01-23', 'Food'            , NULL                  , NULL              , NULL),
    -- 2026-01-25
    ('8890200e-ebd1-5848-b401-1e0e49c35b00', 'CARD', NULL  , 'expense' ,       14000, '2026-01-25', 'Transport'       , NULL                  , NULL              , NULL),
    ('3287c555-533c-5495-957c-0db7c55b5ee7', 'CARD', NULL  , 'expense' ,       50000, '2026-01-25', 'Social'          , NULL                  , NULL              , NULL),
    ('6dcc8430-8b9f-5756-a024-f51043d6c0b4', 'BCA' , NULL  , 'expense' ,    12299123, '2026-01-25', NULL              , 'KPR'                 , NULL              , NULL),
    ('3ec1f8e8-83df-50b1-ab90-1e2ce97e86ce', 'CARD', NULL  , 'expense' ,       10000, '2026-01-25', 'Others'          , NULL                  , NULL              , 'Bea Materai Lunas'),
    -- 2026-01-26
    ('97e64e54-b3bb-5338-8bfe-238933fe52c0', 'CARD', NULL  , 'expense' ,      493500, '2026-01-26', 'Others'          , NULL                  , NULL              , NULL),
    ('f5c484bf-5ee7-584e-b2a2-7a1a3d245114', 'CARD', NULL  , 'expense' ,       35000, '2026-01-26', 'Food'            , NULL                  , NULL              , NULL),
    ('068bd992-2a83-5f9c-8cc9-9d2ca61046d4', 'CARD', NULL  , 'expense' ,       27800, '2026-01-26', 'Food'            , NULL                  , NULL              , NULL),
    ('1cb9d5f1-0214-5d4c-ae43-64b45c47f8f6', 'CARD', NULL  , 'expense' ,       29000, '2026-01-26', 'Food'            , NULL                  , NULL              , NULL),
    ('279ff19d-c315-5753-9b65-5be374f09026', 'CARD', NULL  , 'expense' ,       64000, '2026-01-26', 'Food'            , NULL                  , NULL              , NULL),
    -- 2026-01-27
    ('53034fe5-4ee7-5295-ae9a-90d2346b35e3', 'CARD', NULL  , 'expense' ,       21000, '2026-01-27', 'Food'            , NULL                  , NULL              , NULL),
    -- 2026-01-28
    ('3a8b79fd-68f3-54c5-b7bb-3c540ba8f80e', 'CARD', NULL  , 'expense' ,       96709, '2026-01-28', 'Food'            , NULL                  , NULL              , NULL),
    ('ad8e4d1e-da05-5616-8da6-4f1a709208ad', 'CARD', NULL  , 'expense' ,       22833, '2026-01-28', 'Food'            , NULL                  , NULL              , NULL),
    ('edf44512-a834-5721-904c-2e57ce3b28d7', 'CARD', NULL  , 'expense' ,      451810, '2026-01-28', 'Others'          , NULL                  , NULL              , 'Battery + Adhesive'),
    ('6b65c833-8dfa-54fa-8cab-5f8a530ac2b1', 'CARD', NULL  , 'expense' ,      108500, '2026-01-28', 'Food'            , NULL                  , NULL              , NULL),
    -- 2026-01-29
    ('9353822b-1bd4-5c58-a525-d6dd87c3d0d9', 'CARD', NULL  , 'expense' ,       32293, '2026-01-29', 'Food'            , NULL                  , NULL              , NULL),
    ('2532673e-55fb-5511-9dba-4cb0e12731ae', 'CARD', NULL  , 'expense' ,      105000, '2026-01-29', 'Others'          , NULL                  , NULL              , 'Adhesive'),
    ('a92143f4-3d0b-5d2c-b84d-a57ba302b26d', 'CARD', NULL  , 'expense' ,      223500, '2026-01-29', 'Others'          , NULL                  , NULL              , 'Obat Kolestrol + Asam Urat + Psidii'),
    ('ccd46a5e-491b-5b06-bc65-c5f738c81a01', 'BCA' , NULL  , 'expense' ,     1000000, '2026-01-29', 'Transport'       , NULL                  , NULL              , 'EMoney'),
    ('00e2e77d-f829-56db-a83d-b76eba712354', 'BCA' , NULL  , 'expense' ,         500, '2026-01-29', 'Others'          , NULL                  , NULL              , 'EMoney'),
    ('4797f4a5-71cc-547a-8138-11b369f44095', 'BCA' , NULL  , 'expense' ,      192303, '2026-01-29', NULL              , 'IPL Cilejit'         , NULL              , NULL),
    -- 2026-01-30
    ('51539eca-5786-5dec-8fba-27ef093cc1ce', 'CARD', NULL  , 'expense' ,      225135, '2026-01-30', NULL              , 'FF XIV'              , NULL              , NULL),
    ('6552b907-98af-57b0-af61-bea7d70aab84', 'CARD', NULL  , 'expense' ,      107000, '2026-01-30', 'Food'            , NULL                  , NULL              , NULL),
    ('9b5024ff-4717-54f0-94db-b92a95eac1c0', 'CARD', NULL  , 'expense' ,      181710, '2026-01-30', 'Food'            , NULL                  , NULL              , NULL),
    -- 2026-01-31
    ('27d183c9-ef4f-5f89-a069-c42a7b616ca0', 'CARD', NULL  , 'expense' ,       35000, '2026-01-31', 'Transport'       , NULL                  , NULL              , NULL),
    ('9ddba937-16b6-5a05-8849-8c5563d72c51', 'CARD', NULL  , 'expense' ,       24000, '2026-01-31', 'Transport'       , NULL                  , NULL              , NULL),
    ('68a7d9fc-9da3-5d1b-8717-e0bdfb32e517', 'CARD', NULL  , 'expense' ,       49000, '2026-01-31', 'Social'          , NULL                  , NULL              , NULL),
    ('78259ad4-31b6-5138-812a-0e4f2a5d4701', 'CARD', NULL  , 'expense' ,       69900, '2026-01-31', 'Others'          , NULL                  , NULL              , 'Socks'),
    ('7115cafb-3477-5de8-b105-29ee5ffbad0e', 'CARD', NULL  , 'expense' ,      384520, '2026-01-31', 'Food'            , NULL                  , NULL              , 'FibreFirst'),
    ('d7b1aa7d-343d-5379-9fd3-02514f51c789', 'CARD', NULL  , 'expense' ,      289713, '2026-01-31', 'Social'          , NULL                  , NULL              , NULL),
    ('2f2f77d7-ec24-5f8c-9879-a570074ce4c5', 'CARD', NULL  , 'expense' ,      125401, '2026-01-31', 'Others'          , NULL                  , NULL              , NULL),
    ('8459e68c-3f0c-57ce-a64f-54ed59c8dc43', 'CARD', NULL  , 'expense' ,       20000, '2026-01-31', 'Transport'       , NULL                  , NULL              , NULL),
    ('0229b56b-d08a-5db4-b854-ebd428ce94ba', 'CARD', NULL  , 'expense' ,       70000, '2026-01-31', 'Transport'       , NULL                  , NULL              , NULL),
    ('3abed99b-b6e8-52d1-941e-db103a58d7ef', 'CARD', NULL  , 'expense' ,       20500, '2026-01-31', 'Transport'       , NULL                  , NULL              , NULL),
    ('ff88f9b0-57a4-51d0-8d2d-f3015e89e841', 'CARD', NULL  , 'expense' ,       43000, '2026-01-31', 'Transport'       , NULL                  , NULL              , NULL),
    ('7ff5e251-e469-59fb-ab83-80180506d0d1', 'CARD', NULL  , 'expense' ,       20000, '2026-01-31', 'Social'          , NULL                  , NULL              , NULL),
    ('86501e15-29fd-5174-b43a-1df5e2e197d3', 'CARD', NULL  , 'expense' ,       27000, '2026-01-31', 'Transport'       , NULL                  , NULL              , NULL),
    ('5c69140a-1635-5a7f-bc43-3ea3bffb28e5', 'CARD', NULL  , 'expense' ,       46600, '2026-01-31', 'Transport'       , NULL                  , NULL              , NULL),
    ('5e738ab5-2961-52e3-bb52-54c8ae41df48', 'CARD', NULL  , 'expense' ,     -184656, '2026-01-31', 'Others'          , NULL                  , NULL              , 'Refund Adhesive'),
    ('7922b757-4634-5d0b-8e3a-e98f88f61183', 'BCA' , NULL  , 'income'  ,         324, '2026-01-31', NULL              , NULL                  , 'Bank Interest'   , 'Bank Interest'),
    ('eaa1f088-2ca5-5350-80ac-e5c5ecb2f471', 'BCA' , NULL  , 'expense' ,      344175, '2026-01-31', 'Food'            , NULL                  , NULL              , 'Budget Adjustment'),
    ('a0a28d75-44d6-5583-896d-f4eabc9c7a44', 'BCA' , NULL  , 'expense' ,     -344175, '2026-01-31', 'Others'          , NULL                  , NULL              , 'Budget Adjustment')
  ) AS v(id, acct, xfer, type, amount, date, budget_name, fixed_name, category_name, description)
LEFT JOIN budgets b
  ON b.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid
  AND b.year_month = '2026-01' AND b.name = v.budget_name
LEFT JOIN fixed_expenses f
  ON f.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid AND f.year_month = '2026-01'
  AND f.name = v.fixed_name
LEFT JOIN categories c
  ON c.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid AND c.name = v.category_name
ON CONFLICT (id) DO NOTHING;

COMMIT;
