-- ============================================================
-- Budget carry-over seed for 2026-02 -> feeds carry_in of 2026-03.
-- Values = Row 2 of 'Finance Management 5.0 - Mar 2026.csv'. Reproduces that sheet's Row 3.
-- User 9e36aab2-dc6e-4ff6-9ae1-c81e82225424 | dummy expenses on BCA bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae (DO move the BCA balance).
-- Run this BEFORE the per-month imports. Idempotent.
-- Generated by supabase/imports/generate_carryover_seed.py
-- ============================================================
BEGIN;

-- 2026-02 budgets (standard periodic; carry-over chains into 2026-03).
INSERT INTO budgets (user_id, name, year_month, periodic_amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Food', '2026-02', 3000000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET periodic_amount = EXCLUDED.periodic_amount;
INSERT INTO budgets (user_id, name, year_month, periodic_amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Transport', '2026-02', 2500000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET periodic_amount = EXCLUDED.periodic_amount;
INSERT INTO budgets (user_id, name, year_month, periodic_amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Social', '2026-02', 2455000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET periodic_amount = EXCLUDED.periodic_amount;
INSERT INTO budgets (user_id, name, year_month, periodic_amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Others', '2026-02', 1477509) ON CONFLICT (user_id, name, year_month) DO UPDATE SET periodic_amount = EXCLUDED.periodic_amount;

INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2026-02', 0) ON CONFLICT (account_id, year_month) DO NOTHING;

-- Dummy BCA expense per envelope: periodic - spend = remaining (= Row 2).
INSERT INTO transactions
  (id, user_id, account_id, transfer_account_id, type, status,
   amount, description, date, category_id, budget_id, fixed_expense_id)
SELECT
  v.id::uuid, '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid, 'bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae'::uuid, NULL,
  'expense'::transaction_type, 'confirmed',
  v.amount, v.description, v.date::date,
  NULL, b.id, NULL
FROM (VALUES
	('49e8597a-8058-5e08-8b8a-4896ab592a55', 3000000, '2026-02-01', 'Carry-over seed -> 2026-03', 'Food'),
    ('49e8597a-8058-5e08-8b8a-4896ab592a55', 788565, '2026-02-01', 'Carry-over seed -> 2026-03', 'Transport'),
    ('811f111a-4d8f-5d4a-a393-7758c9a03456', 2762140, '2026-02-01', 'Carry-over seed -> 2026-03', 'Social'),
    ('81c873eb-c0ab-5a46-ad11-756e24ff0bfe', 607126, '2026-02-01', 'Carry-over seed -> 2026-03', 'Others')
  ) AS v(id, amount, date, description, budget_name)
LEFT JOIN budgets b ON b.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid AND b.year_month = '2026-02' AND b.name = v.budget_name
ON CONFLICT (id) DO NOTHING;

COMMIT;
