-- ============================================================
-- Budget carry-over seed for 2026-03 -> feeds carry_in of 2026-04.
-- Values = Row 2 of 'Finance Management 5.0 - Apr 2026.csv'. Reproduces that sheet's Row 3.
-- User 9e36aab2-dc6e-4ff6-9ae1-c81e82225424 | dummy expenses on BCA bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae (DO move the BCA balance).
-- Run this BEFORE the per-month imports. Idempotent.
-- Generated by supabase/imports/generate_carryover_seed.py
-- ============================================================
BEGIN;

-- 2026-03 budgets (standard periodic; carry-over chains into 2026-04).
INSERT INTO budgets (user_id, name, year_month, periodic_amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Transport', '2026-03', 2500000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET periodic_amount = EXCLUDED.periodic_amount;
INSERT INTO budgets (user_id, name, year_month, periodic_amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Social', '2026-03', 2600000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET periodic_amount = EXCLUDED.periodic_amount;
INSERT INTO budgets (user_id, name, year_month, periodic_amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Others', '2026-03', 1477509) ON CONFLICT (user_id, name, year_month) DO UPDATE SET periodic_amount = EXCLUDED.periodic_amount;

INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2026-03', 0) ON CONFLICT (account_id, year_month) DO NOTHING;

-- Dummy BCA expense per envelope: periodic - spend = remaining (= Row 2).
INSERT INTO transactions
  (id, user_id, account_id, transfer_account_id, type, status,
   amount, description, date, category_id, budget_id, fixed_expense_id)
SELECT
  v.id::uuid, '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid, 'bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae'::uuid, NULL,
  'expense'::transaction_type, 'confirmed',
  v.amount, v.description, v.date::date,
  NULL, b.id, NULL
FROM (VALUES
    ('667589cc-304f-5ffd-ba0c-b2beb2c69f3e', 643565, '2026-03-01', 'Carry-over seed -> 2026-04', 'Transport'),
    ('ebc79792-9eb1-58a8-9731-32bcc764e445', 2595078, '2026-03-01', 'Carry-over seed -> 2026-04', 'Social'),
    ('b9e7066a-ace8-580b-9dbd-1a0116f3f85a', 1254559, '2026-03-01', 'Carry-over seed -> 2026-04', 'Others')
  ) AS v(id, amount, date, description, budget_name)
LEFT JOIN budgets b ON b.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid AND b.year_month = '2026-03' AND b.name = v.budget_name
ON CONFLICT (id) DO NOTHING;

COMMIT;
