-- ============================================================
-- Backfill: 'Finance Management 5.0 - May 2026.csv'
-- User 9e36aab2-dc6e-4ff6-9ae1-c81e82225424
-- BCA bank bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae | BCA VISA card 2f940480-5908-4c11-9fa1-9ff7a58c65c9
-- Idempotent: safe to re-run (natural-key upserts + deterministic txn ids).
-- Generated by supabase/imports/generate_monthly.py 2026-05
-- ============================================================
BEGIN;

-- NOTE: this spreadsheet does not categorize transactions, so every
--       transaction is imported with category_id = NULL.

-- Budgets for the month (periodic_amount = the spreadsheet's budget).
INSERT INTO budgets (user_id, name, year_month, periodic_amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Food', '2026-05', 2600000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET periodic_amount = EXCLUDED.periodic_amount;
INSERT INTO budgets (user_id, name, year_month, periodic_amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Transport', '2026-05', 2500000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET periodic_amount = EXCLUDED.periodic_amount;
INSERT INTO budgets (user_id, name, year_month, periodic_amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Social', '2026-05', 2600000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET periodic_amount = EXCLUDED.periodic_amount;
INSERT INTO budgets (user_id, name, year_month, periodic_amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Others', '2026-05', 1477509) ON CONFLICT (user_id, name, year_month) DO UPDATE SET periodic_amount = EXCLUDED.periodic_amount;

-- Fixed expenses (Monthly Expenses Details). Only paid ones are imported.
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'KPR', '2026-05', 12299123) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Papa', '2026-05', 6000000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Electricity Alegria', '2026-05', 300000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'First Media', '2026-05', 427350) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'FF XIV', '2026-05', 230000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'IPL Cilejit', '2026-05', 192303) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'IPL VPP', '2026-05', 175000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'IPL Alegria', '2026-05', 100000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'My Republic', '2026-05', 832000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'PDAM', '2026-05', 100000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Paket Data', '2026-05', 100000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Netflix', '2026-05', 46500) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'ADM BCA', '2026-05', 20000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Youtube Premium', '2026-05', 18315) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;

-- Ensure monthly-balance rows exist so the recalc trigger has rows to update.
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2026-05', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2026-06', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('2f940480-5908-4c11-9fa1-9ff7a58c65c9', '2026-05', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('2f940480-5908-4c11-9fa1-9ff7a58c65c9', '2026-06', 0) ON CONFLICT (account_id, year_month) DO NOTHING;

-- Transactions (150 rows). category_id is always NULL (no categories).
-- Per row: (id, acct, xfer, type, amount, date, budget, fixed, description).
INSERT INTO transactions
  (id, user_id, account_id, transfer_account_id, type, status,
   amount, description, date, category_id, budget_id, fixed_expense_id)
SELECT
  v.id::uuid, '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid,
  CASE v.acct WHEN 'BCA' THEN 'bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae'::uuid WHEN 'CARD' THEN '2f940480-5908-4c11-9fa1-9ff7a58c65c9'::uuid END,
  CASE v.xfer WHEN 'CARD' THEN '2f940480-5908-4c11-9fa1-9ff7a58c65c9'::uuid ELSE NULL END,
  v.type::transaction_type, 'confirmed',
  v.amount, v.description, v.date::date,
  NULL,   -- category_id (this sheet does not categorize)
  b.id,   -- budget_id        (matched by name)
  f.id    -- fixed_expense_id (matched by name)
FROM (VALUES
    -- 2026-05-01
    ('ee6893a0-f42b-51f3-b3d6-1b595f9ccf49', 'BCA' , NULL  , 'income'  ,    44869286, '2026-05-01', NULL              , NULL                  , 'Salary'),
    ('09032039-9e23-58de-b7fc-29b6371d287a', 'BCA' , NULL  , 'expense' ,     6000000, '2026-05-01', NULL              , 'Papa'                , 'Papa'),
    ('d017720c-838c-5d7b-ab49-257756a0877d', 'BCA' , NULL  , 'expense' ,       18315, '2026-05-01', NULL              , 'Youtube Premium'     , 'Youtube Premium'),
    ('f869f66d-7226-50b8-913a-78cbd7c03135', 'BCA' , NULL  , 'expense' ,       46500, '2026-05-01', NULL              , 'Netflix'             , 'Netflix'),
    ('74b16ad1-98ce-5d35-a28d-a32faf0226ef', 'BCA' , NULL  , 'expense' ,      175000, '2026-05-01', NULL              , 'IPL VPP'             , 'IPL VPP'),
    ('586c9b40-0d98-5845-adf0-4bab47daff6e', 'CARD', NULL  , 'expense' ,      819442, '2026-05-01', 'Social'          , NULL                  , NULL),
    ('eb899650-8312-524a-8446-921af553f18b', 'CARD', NULL  , 'expense' ,      275755, '2026-05-01', 'Social'          , NULL                  , NULL),
    -- 2026-05-02
    ('4cd6b483-cefa-514d-862b-8c667f352109', 'CARD', NULL  , 'expense' ,       29600, '2026-05-02', 'Social'          , NULL                  , NULL),
    ('7037b0c8-75eb-5b4a-97f7-735e5c6368f8', 'CARD', NULL  , 'expense' ,       71100, '2026-05-02', 'Social'          , NULL                  , NULL),
    ('dba84cf0-126c-546b-b1ed-1cb3d3dff81d', 'CARD', NULL  , 'expense' ,       54000, '2026-05-02', 'Social'          , NULL                  , NULL),
    ('6eb93acc-340e-5ee7-9678-803fc83fc9c7', 'CARD', NULL  , 'expense' ,       40500, '2026-05-02', 'Transport'       , NULL                  , NULL),
    ('fa086b31-bc4f-5d8a-bd3f-06127f6617bc', 'CARD', NULL  , 'expense' ,       20000, '2026-05-02', 'Social'          , NULL                  , NULL),
    ('21311862-8494-521b-b35e-be7912fa7e4d', 'CARD', NULL  , 'expense' ,       40000, '2026-05-02', 'Transport'       , NULL                  , NULL),
    ('1fb1f589-2935-5c39-af11-aa8053a3833a', 'CARD', NULL  , 'expense' ,        5000, '2026-05-02', 'Transport'       , NULL                  , NULL),
    ('5bc4fa60-9bbc-51ee-83d4-b05df18f5032', 'BCA' , NULL  , 'expense' ,      501000, '2026-05-02', 'Transport'       , NULL                  , NULL),
    -- 2026-05-03
    ('6a426536-6542-5ac3-a222-671961329c86', 'CARD', NULL  , 'expense' ,       80000, '2026-05-03', 'Social'          , NULL                  , NULL),
    ('d43d522c-f092-5ccb-8903-123a800c5c93', 'CARD', NULL  , 'expense' ,       85160, '2026-05-03', 'Food'            , NULL                  , NULL),
    ('2153b5db-68b9-58ab-b1f7-740568d458b5', 'CARD', NULL  , 'expense' ,      204700, '2026-05-03', NULL              , NULL                  , 'House Renovation'),
    ('1edca36f-88de-50a4-a52c-129656c7697c', 'BCA' , NULL  , 'expense' ,      999500, '2026-05-03', 'Transport'       , NULL                  , NULL),
    -- 2026-05-04
    ('2be724c0-a3b3-5f6d-a3e9-295dffaac4ab', 'CARD', NULL  , 'expense' ,      402234, '2026-05-04', NULL              , 'Electricity Alegria' , 'Electricity Alegria'),
    ('7dcbcd48-8b94-5f91-b5d9-6a8fb21886be', 'CARD', NULL  , 'expense' ,       46500, '2026-05-04', NULL              , 'PDAM'                , 'PDAM'),
    ('553a6d02-0c98-5ab0-9ca4-8bf56ed9a578', 'CARD', NULL  , 'expense' ,      138400, '2026-05-04', NULL              , NULL                  , 'House Renovation'),
    ('644a2376-52c7-5b05-907e-343d82d876b1', 'CARD', NULL  , 'expense' ,      133700, '2026-05-04', 'Food'            , NULL                  , NULL),
    ('cd5a4e2d-b30f-59a5-841e-cb4046416636', 'CARD', NULL  , 'expense' ,      180000, '2026-05-04', 'Others'          , NULL                  , 'Blackmores'),
    ('c9ae31a2-0672-5f7a-a217-9a6980a10a78', 'CARD', NULL  , 'expense' ,       23000, '2026-05-04', 'Food'            , NULL                  , NULL),
    ('5951ba5d-d78e-5653-967c-069ca391e54d', 'CARD', NULL  , 'expense' ,       32500, '2026-05-04', 'Transport'       , NULL                  , NULL),
    ('32673ebd-4131-5e9d-b1d4-386d41fe5c83', 'CARD', NULL  , 'expense' ,        2000, '2026-05-04', 'Transport'       , NULL                  , NULL),
    ('21ed35d1-56d5-5cb5-82b3-f39e3a806278', 'CARD', NULL  , 'expense' ,      117050, '2026-05-04', 'Food'            , NULL                  , NULL),
    -- 2026-05-05
    ('04444a67-631a-588e-a8f7-ab4d1609864c', 'CARD', NULL  , 'expense' ,       26000, '2026-05-05', 'Food'            , NULL                  , NULL),
    ('01cf0327-1044-5d8f-9245-53dc7f1c1147', 'CARD', NULL  , 'expense' ,       23000, '2026-05-05', 'Transport'       , NULL                  , NULL),
    ('e41a4235-290a-51d7-be45-75940d7ab7b9', 'CARD', NULL  , 'expense' ,        5000, '2026-05-05', 'Transport'       , NULL                  , NULL),
    ('bd8370eb-32fb-5ce6-afb8-a5955a29f192', 'CARD', NULL  , 'expense' ,      651642, '2026-05-05', 'Social'          , NULL                  , NULL),
    -- 2026-05-06
    ('6f1f515f-8896-5850-b4ee-4c79818991f3', 'CARD', NULL  , 'expense' ,       12600, '2026-05-06', 'Food'            , NULL                  , NULL),
    ('c7d8e70c-3104-5416-8427-106f87a24374', 'CARD', NULL  , 'expense' ,       21000, '2026-05-06', 'Food'            , NULL                  , NULL),
    ('a14938d9-d159-5afa-8efa-99dbec61f133', 'CARD', NULL  , 'expense' ,       23870, '2026-05-06', 'Food'            , NULL                  , NULL),
    ('4cb41a0a-ed6f-560d-aa37-8b4910c7412a', 'CARD', NULL  , 'expense' ,      328246, '2026-05-06', NULL              , NULL                  , 'House Renovation'),
    ('5ec054d4-dc7c-58a1-a708-b31ee27caba5', 'CARD', NULL  , 'expense' ,      180000, '2026-05-06', 'Food'            , NULL                  , NULL),
    ('208c4487-e344-5a80-a759-6769c29ab1e4', 'BCA' , 'CARD', 'transfer',     5388396, '2026-05-06', NULL              , NULL                  , NULL),
    ('1abd07c4-0a1b-530a-b80f-a7cfd9b82c11', 'CARD', NULL  , 'expense' ,       71730, '2026-05-06', NULL              , 'IPL Alegria'         , 'IPL Alegria'),
    -- 2026-05-07
    ('2ca8cb06-f56f-59ac-aa6d-8f482fa38ba3', 'CARD', NULL  , 'expense' ,       22071, '2026-05-07', 'Transport'       , NULL                  , NULL),
    ('829a1aee-c004-5f39-8e42-eb904fb8acb1', 'CARD', NULL  , 'expense' ,       13000, '2026-05-07', 'Food'            , NULL                  , NULL),
    ('cc1d9bc4-703a-5a4c-b3a2-b84c9788e0a9', 'CARD', NULL  , 'expense' ,       41520, '2026-05-07', 'Others'          , NULL                  , 'Laundry'),
    ('1b421167-5b6d-5a56-ab58-5404570e043a', 'CARD', NULL  , 'expense' ,      345882, '2026-05-07', 'Social'          , NULL                  , NULL),
    ('82473ac5-7ff4-5598-ad86-c4dbbb0750cd', 'CARD', NULL  , 'expense' ,       93465, '2026-05-07', 'Food'            , NULL                  , NULL),
    ('fc0e1f57-e1c2-569a-8144-b0fcc1d8a70c', 'BCA' , NULL  , 'income'  ,    50000000, '2026-05-07', NULL              , NULL                  , 'Lidya Laparoskopi'),
    -- 2026-05-08
    ('ecacb444-4d88-5300-8fc5-f5cd7f901858', 'CARD', NULL  , 'expense' ,       44000, '2026-05-08', 'Food'            , NULL                  , NULL),
    ('680225e4-b772-58f2-a2d2-9ff5e5c47cb2', 'CARD', NULL  , 'expense' ,       67001, '2026-05-08', 'Food'            , NULL                  , NULL),
    ('4859f0d4-77b9-5001-a568-6140e403cb63', 'CARD', NULL  , 'expense' ,        2000, '2026-05-08', 'Food'            , NULL                  , NULL),
    ('88b4740d-d212-5a25-8144-ddbca55ebc5c', 'CARD', NULL  , 'expense' ,   -30000000, '2026-05-08', NULL              , NULL                  , 'Lidya Laparoskopi'),
    ('45bedc49-03aa-559e-b798-267295e389f8', 'CARD', NULL  , 'expense' ,   -13000000, '2026-05-08', NULL              , NULL                  , 'Lidya Laparoskopi'),
    ('f8c24030-6646-5325-82ce-dd56f40c20d1', 'BCA' , NULL  , 'income'  ,    15000000, '2026-05-08', NULL              , NULL                  , 'Lidya Laparoskopi'),
    -- 2026-05-09
    ('d25df82b-c459-5e1a-8f2c-45d59c941a7c', 'CARD', NULL  , 'expense' ,       25000, '2026-05-09', 'Food'            , NULL                  , NULL),
    ('b4bd394d-3ca6-540b-8ef9-5ebbbe736535', 'CARD', NULL  , 'expense' ,       24000, '2026-05-09', 'Food'            , NULL                  , NULL),
    ('54023f9e-13f3-585e-8b3a-531137472b2e', 'CARD', NULL  , 'expense' ,   -15000000, '2026-05-09', NULL              , NULL                  , 'Lidya Laparoskopi'),
    ('5152a3c2-2846-537a-b166-e42dbcabb2b8', 'CARD', NULL  , 'expense' ,    -7000000, '2026-05-09', NULL              , NULL                  , 'Lidya Laparoskopi'),
    ('d12d0a44-9fe7-5421-a3de-9fc42e6f9383', 'BCA' , NULL  , 'income'  ,   -40000000, '2026-05-09', NULL              , NULL                  , 'Lidya Laparoskopi Hospital Payment'),
    ('bc8ef8ca-4865-5b94-9b89-883af19cdade', 'CARD', NULL  , 'expense' ,    40000000, '2026-05-09', NULL              , NULL                  , 'Lidya Laparoskopi Hospital Payment'),
    ('eec31293-6575-54fe-baaa-ed85f5d14f86', 'CARD', NULL  , 'expense' ,       86100, '2026-05-09', 'Food'            , NULL                  , NULL),
    ('943557bf-3598-5172-8f53-a2ab1d6dad68', 'CARD', NULL  , 'expense' ,        2000, '2026-05-09', 'Food'            , NULL                  , NULL),
    ('eab71ff4-f769-5f13-bdc6-5fbb3335b9a2', 'CARD', NULL  , 'expense' ,       35000, '2026-05-09', 'Food'            , NULL                  , NULL),
    ('ff17302d-403c-55e6-9996-d5a2ffc49692', 'CARD', NULL  , 'expense' ,      175500, '2026-05-09', 'Others'          , NULL                  , 'STNK Mobil'),
    ('bd499fa5-21de-57cf-a8c4-b81cbf7863f8', 'CARD', NULL  , 'expense' ,       77900, '2026-05-09', 'Food'            , NULL                  , NULL),
    ('5a2693e0-741b-5af0-b06e-360dbb11180b', 'CARD', NULL  , 'expense' ,        2000, '2026-05-09', 'Food'            , NULL                  , NULL),
    -- 2026-05-10
    ('07385fe7-10b9-5f4c-af7f-afb0892dadef', 'CARD', NULL  , 'expense' ,      121202, '2026-05-10', 'Food'            , NULL                  , NULL),
    ('c48dd210-f25e-55ea-838e-06fef887fcaf', 'CARD', NULL  , 'expense' ,        2000, '2026-05-10', 'Food'            , NULL                  , NULL),
    ('a4a0e723-5168-5ad0-9968-2761d8580d6d', 'BCA' , NULL  , 'income'  ,   -11980813, '2026-05-10', NULL              , NULL                  , 'Lidya Laparoskopi'),
    ('db9150a7-d215-5932-a051-6c094fa08025', 'CARD', NULL  , 'expense' ,    11980813, '2026-05-10', NULL              , NULL                  , 'Lidya Laparoskopi'),
    -- 2026-05-11
    ('053f136e-0866-574f-9603-db4e8a776ff3', 'CARD', NULL  , 'expense' ,       52505, '2026-05-11', 'Food'            , NULL                  , NULL),
    ('e71ec9be-b120-5fc7-abc4-43b8f3b3db75', 'CARD', NULL  , 'expense' ,       26950, '2026-05-11', 'Food'            , NULL                  , NULL),
    ('75b00524-2faa-5bb5-8dcd-fb521a403efe', 'BCA' , NULL  , 'income'  ,      143991, '2026-05-11', NULL              , NULL                  , 'ST12T02'),
    ('582ba933-0ac6-5c42-aea4-c559b32aa949', 'BCA' , NULL  , 'expense' ,      192303, '2026-05-11', NULL              , 'IPL Cilejit'         , 'IPL Cilejit'),
    -- 2026-05-12
    ('4fddcaf5-e821-52f1-95c2-51815a2c4fc6', 'CARD', NULL  , 'expense' ,       60482, '2026-05-12', 'Others'          , NULL                  , 'Hook Suction Cup'),
    ('2ec9fe97-ed6c-5a8f-be23-0adaeceae824', 'CARD', NULL  , 'expense' ,       31000, '2026-05-12', 'Food'            , NULL                  , NULL),
    ('5aff1a32-1b65-502f-8ec1-5973889990fc', 'CARD', NULL  , 'expense' ,       26950, '2026-05-12', 'Food'            , NULL                  , NULL),
    ('66d28966-3740-5883-99fb-22e679fe43a0', 'CARD', NULL  , 'expense' ,      133000, '2026-05-12', 'Food'            , NULL                  , NULL),
    ('f4e3a430-0c0e-5c6a-b6da-90a807036a7e', 'CARD', NULL  , 'expense' ,        2000, '2026-05-12', 'Food'            , NULL                  , NULL),
    -- 2026-05-13
    ('338be927-a091-5825-906f-3286c05d5109', 'CARD', NULL  , 'expense' ,      342430, '2026-05-13', NULL              , NULL                  , 'Tangga Rumah Lipat'),
    ('3a8245f3-d267-5e02-990f-ee9f46f03028', 'CARD', NULL  , 'expense' ,      503100, '2026-05-13', 'Transport'       , NULL                  , NULL),
    -- 2026-05-14
    ('835dc93c-66f6-5a44-983d-8f8ceb91cacb', 'CARD', NULL  , 'expense' ,       49000, '2026-05-14', 'Social'          , NULL                  , NULL),
    ('7a54e5cb-5882-5fd1-bb28-8bbf6a776190', 'CARD', NULL  , 'expense' ,       70400, '2026-05-14', 'Food'            , NULL                  , NULL),
    ('e9d504d8-0a73-532c-9acc-e82f493cd3dc', 'CARD', NULL  , 'expense' ,      427350, '2026-05-14', NULL              , 'First Media'         , 'First media'),
    ('73b02c1e-d800-5f88-8815-12adba1de6a0', 'BCA' , NULL  , 'expense' ,       45200, '2026-05-14', 'Transport'       , NULL                  , NULL),
    -- 2026-05-15
    ('1f1db95e-0661-597a-884e-c839e5dfa17e', 'CARD', NULL  , 'expense' ,       18000, '2026-05-15', 'Food'            , NULL                  , NULL),
    ('0dae2bbe-4337-548a-b20d-424d79d02d9d', 'BCA' , NULL  , 'expense' ,       20000, '2026-05-15', NULL              , 'ADM BCA'             , 'ADM BCA'),
    -- 2026-05-16
    ('3a03a65f-e5d6-56a9-be74-ecd6a1d87f6b', 'CARD', NULL  , 'expense' ,     4300973, '2026-05-16', NULL              , NULL                  , 'TTRacing Titus X'),
    ('7c419e75-c037-5454-afd6-4478c1cae61c', 'CARD', NULL  , 'expense' ,     1009756, '2026-05-16', 'Social'          , NULL                  , NULL),
    ('ee8a948b-a550-57f0-a2ba-9fab47c7cd91', 'CARD', NULL  , 'expense' ,       25000, '2026-05-16', 'Social'          , NULL                  , NULL),
    ('3463efc4-a0a7-536d-917f-22b94624bcaa', 'CARD', NULL  , 'expense' ,       60500, '2026-05-16', 'Social'          , NULL                  , NULL),
    ('0452fb74-4ca5-53f5-b0c3-11574d349738', 'CARD', NULL  , 'expense' ,       27000, '2026-05-16', 'Social'          , NULL                  , NULL),
    ('0c462f54-4c96-5962-9c62-5b2ceab247ab', 'BCA' , NULL  , 'expense' ,     -145750, '2026-05-16', 'Social'          , NULL                  , NULL),
    ('2a9bd6be-4e0a-554e-acce-153fe2316b03', 'BCA' , NULL  , 'expense' ,     -177232, '2026-05-16', 'Social'          , NULL                  , NULL),
    ('c51ac6c1-7101-559d-ab0b-321487c5cd42', 'BCA' , NULL  , 'expense' ,     -151580, '2026-05-16', 'Social'          , NULL                  , NULL),
    ('c1fe3d02-1cdd-539c-8a6a-d7e4440117b2', 'BCA' , NULL  , 'expense' ,     -169070, '2026-05-16', 'Social'          , NULL                  , NULL),
    ('d66e381a-55fd-595e-b559-05ddb6c709df', 'BCA' , NULL  , 'expense' ,      381250, '2026-05-16', 'Social'          , NULL                  , NULL),
    ('28091222-2ccd-5a31-a78d-5bac6f4f95af', 'BCA' , NULL  , 'expense' ,     -122430, '2026-05-16', 'Social'          , NULL                  , NULL),
    -- 2026-05-17
    ('26609a48-3aec-59e4-b2a8-22fdce07c204', 'CARD', NULL  , 'expense' ,       82590, '2026-05-17', 'Food'            , NULL                  , NULL),
    -- 2026-05-18
    ('baefffaa-a531-5dd7-b6db-1aa11d7e5a52', 'CARD', NULL  , 'expense' ,     1431500, '2026-05-18', NULL              , NULL                  , 'TP Link Router'),
    ('c5602273-c26f-513c-a470-e0770bbaea98', 'CARD', NULL  , 'expense' ,      832000, '2026-05-18', NULL              , 'My Republic'         , 'My Republic'),
    ('bbb7e55e-ca35-5c3d-87d6-ce42afb92d0b', 'CARD', NULL  , 'expense' ,        2000, '2026-05-18', 'Food'            , NULL                  , NULL),
    ('a61ad1e0-cb5e-5848-8312-e6116a4ffa85', 'CARD', NULL  , 'expense' ,       90260, '2026-05-18', 'Food'            , NULL                  , NULL),
    -- 2026-05-19
    ('193d940f-b5c2-5cf2-8d69-27ae46f2f115', 'CARD', NULL  , 'expense' ,       27400, '2026-05-19', 'Food'            , NULL                  , NULL),
    ('cd635a4f-5693-5329-a903-a88d41f8911a', 'CARD', NULL  , 'expense' ,        2000, '2026-05-19', 'Food'            , NULL                  , NULL),
    ('f233d78b-c662-5e0a-bd44-e163c448c6fd', 'CARD', NULL  , 'expense' ,       90000, '2026-05-19', NULL              , 'Paket Data'          , 'Paket Data'),
    ('c57439a2-cf61-5c03-b4ef-07fc14d60558', 'CARD', NULL  , 'expense' ,       87200, '2026-05-19', 'Food'            , NULL                  , NULL),
    -- 2026-05-20
    ('502b8767-372a-5b36-8d26-e12a5f20a21e', 'CARD', NULL  , 'expense' ,      269705, '2026-05-20', NULL              , NULL                  , 'Vention Cable Management'),
    ('dfe4f96e-5aba-5c2f-a31b-eee06b7c5555', 'CARD', NULL  , 'expense' ,       23000, '2026-05-20', 'Food'            , NULL                  , NULL),
    ('a84451c0-54af-58f5-a2de-66a9d8166330', 'CARD', NULL  , 'expense' ,      107982, '2026-05-20', NULL              , NULL                  , 'Cable Management'),
    ('15a33c66-faed-57c4-b39c-3ce5e8a0e608', 'CARD', NULL  , 'expense' ,       78000, '2026-05-20', 'Transport'       , NULL                  , NULL),
    ('79ccce9f-fc94-5ec0-8378-fd2176c514ea', 'BCA' , NULL  , 'expense' ,       10900, '2026-05-20', 'Food'            , NULL                  , NULL),
    ('da31aac6-001e-5b20-921c-8980b9985b14', 'BCA' , NULL  , 'expense' ,      101500, '2026-05-20', 'Transport'       , NULL                  , NULL),
    -- 2026-05-21
    ('4fb73ae4-1524-567b-a222-4e5054aa100e', 'CARD', NULL  , 'expense' ,        7000, '2026-05-21', 'Transport'       , NULL                  , NULL),
    ('8cf9a98d-a30e-5e41-8863-b27be150cf71', 'CARD', NULL  , 'expense' ,        5000, '2026-05-21', 'Transport'       , NULL                  , NULL),
    ('1c91e7ab-7e14-5c0c-a670-9b2e0852a885', 'CARD', NULL  , 'expense' ,       55330, '2026-05-21', 'Food'            , NULL                  , NULL),
    ('04f5b309-dee4-5d98-89c0-797547edec7a', 'CARD', NULL  , 'expense' ,       57500, '2026-05-21', 'Transport'       , NULL                  , NULL),
    ('2416383f-af1c-583b-90a2-84c3dcc47786', 'CARD', NULL  , 'expense' ,       10000, '2026-05-21', 'Transport'       , NULL                  , NULL),
    -- 2026-05-22
    ('7a3e8e58-60ff-5b25-aa07-abb2b41562e0', 'BCA' , NULL  , 'expense' ,       37502, '2026-05-22', 'Food'            , NULL                  , NULL),
    -- 2026-05-23
    ('cfb04c1f-c2bc-52de-9329-efe15a7c6e5e', 'CARD', NULL  , 'expense' ,     1026422, '2026-05-23', NULL              , NULL                  , 'PIA'),
    ('b29cadfe-3e4d-5c7b-84f0-0585025bd9e1', 'CARD', NULL  , 'expense' ,      281000, '2026-05-23', 'Social'          , NULL                  , NULL),
    ('ccee0c4d-524e-5c09-ba74-30fbf0f05e55', 'CARD', NULL  , 'expense' ,      179800, '2026-05-23', 'Social'          , NULL                  , NULL),
    ('73186f4a-f54b-502b-ba2c-f8ed6232d4c5', 'CARD', NULL  , 'expense' ,       97500, '2026-05-23', 'Food'            , NULL                  , NULL),
    ('9ee4ebd9-6160-5e45-83e4-95a1e3c6a91a', 'CARD', NULL  , 'expense' ,        2000, '2026-05-23', 'Food'            , NULL                  , NULL),
    ('f7b693e3-8fb0-593e-9596-7eaa017cf335', 'BCA' , NULL  , 'expense' ,       75000, '2026-05-23', 'Others'          , NULL                  , 'Laundry'),
    -- 2026-05-24
    ('966dff6c-513b-5cc3-b94f-edea18c170e6', 'CARD', NULL  , 'expense' ,      134000, '2026-05-24', 'Social'          , NULL                  , NULL),
    ('bf119649-8439-5204-b9ac-2f5b666786c3', 'CARD', NULL  , 'expense' ,    27213000, '2026-05-24', NULL              , NULL                  , 'IKEA Furniture'),
    ('aa8477d6-ca65-5a27-9686-d8677e3fb814', 'CARD', NULL  , 'expense' ,      901500, '2026-05-24', NULL              , NULL                  , 'Headboard'),
    ('165d61e9-5d74-5521-b328-eca24daf0d7c', 'BCA' , 'CARD', 'transfer',    27000000, '2026-05-24', NULL              , NULL                  , NULL),
    -- 2026-05-25
    ('ef0d48e4-9dcf-5283-a91d-4261851a5f6a', 'CARD', NULL  , 'expense' ,       23000, '2026-05-25', 'Food'            , NULL                  , NULL),
    ('5c845587-e539-5668-8379-7329bfb6f923', 'CARD', NULL  , 'expense' ,       57500, '2026-05-25', 'Transport'       , NULL                  , NULL),
    ('a5c3ee71-ec8c-58d2-b7bb-b6dab04f275a', 'CARD', NULL  , 'expense' ,        5000, '2026-05-25', 'Transport'       , NULL                  , NULL),
    ('d07fcd16-667d-5241-a80d-9ffc28a51c2f', 'BCA' , NULL  , 'expense' ,    12299123, '2026-05-25', NULL              , 'KPR'                 , 'KPR'),
    ('be911de4-84e3-5624-acf2-2c59dc3529b7', 'CARD', NULL  , 'expense' ,       10000, '2026-05-25', 'Others'          , NULL                  , 'Bea Materai Lunas'),
    -- 2026-05-26
    ('1d240c29-e4a8-5659-959d-1acd24738d4a', 'CARD', NULL  , 'expense' ,        7000, '2026-05-26', 'Transport'       , NULL                  , NULL),
    ('c97bdf13-793e-5234-b073-c3652793c788', 'CARD', NULL  , 'expense' ,        5000, '2026-05-26', 'Transport'       , NULL                  , NULL),
    ('adcf8f12-b75a-568a-83fc-b9f1dd0449e2', 'CARD', NULL  , 'expense' ,       23000, '2026-05-26', 'Food'            , NULL                  , NULL),
    ('f0ff82f9-d66f-5e5e-97d0-a1e0c903ee8e', 'CARD', NULL  , 'expense' ,       57500, '2026-05-26', 'Transport'       , NULL                  , NULL),
    ('5da2a0a5-e213-522b-a248-c4e3d3eb2b7c', 'CARD', NULL  , 'expense' ,        5000, '2026-05-26', 'Transport'       , NULL                  , NULL),
    ('ed702128-dafe-5213-b010-8edb332767f1', 'BCA' , NULL  , 'expense' ,       80500, '2026-05-26', 'Social'          , NULL                  , 'Roberto Farewell'),
    -- 2026-05-27
    ('6a0d5389-2ee2-5a22-8d10-d231efafa1d9', 'CARD', NULL  , 'expense' ,      145000, '2026-05-27', 'Food'            , NULL                  , NULL),
    -- 2026-05-28
    ('226b90af-8a88-5c1b-aa55-fbde6a234139', 'CARD', NULL  , 'expense' ,      127601, '2026-05-28', 'Food'            , NULL                  , NULL),
    ('aa03ebd4-d573-55ba-8b8b-69a08834b64b', 'CARD', NULL  , 'expense' ,      100000, '2026-05-28', 'Others'          , NULL                  , 'Extra Paket Data'),
    -- 2026-05-29
    ('e23cba01-831b-57d3-8990-f5b37058cecc', 'CARD', NULL  , 'expense' ,      123600, '2026-05-29', 'Food'            , NULL                  , NULL),
    ('3b2b3282-c986-57ec-93b6-762b6be00f36', 'CARD', NULL  , 'expense' ,        2000, '2026-05-29', 'Food'            , NULL                  , NULL),
    ('504dbd22-d3b3-5bdd-9d0f-9dd591d9bb5b', 'CARD', NULL  , 'expense' ,       98000, '2026-05-29', 'Food'            , NULL                  , NULL),
    ('e20351b1-e2f7-54d8-a5bd-5f2ac60020a5', 'CARD', NULL  , 'expense' ,        2000, '2026-05-29', 'Food'            , NULL                  , NULL),
    -- 2026-05-30
    ('e24ca1e6-8a4f-59db-a2d5-38adc5a983c1', 'CARD', NULL  , 'expense' ,      227053, '2026-05-30', NULL              , 'FF XIV'              , 'FF XIV'),
    ('e08c61ad-4678-5911-abaa-40ffa5f41aed', 'CARD', NULL  , 'expense' ,      131040, '2026-05-30', 'Food'            , NULL                  , NULL),
    -- 2026-05-31
    ('e31477c8-f7aa-579d-aa8f-a826761c2674', 'CARD', NULL  , 'expense' ,       17500, '2026-05-31', 'Transport'       , NULL                  , NULL),
    ('28083025-784c-505f-82a0-8f1491ab5735', 'CARD', NULL  , 'expense' ,       20000, '2026-05-31', 'Social'          , NULL                  , NULL),
    ('0430d540-cf68-5cd2-8da1-9ff76ce07b41', 'CARD', NULL  , 'expense' ,      116000, '2026-05-31', 'Food'            , NULL                  , NULL),
    ('b767b7ed-26e9-58dd-aa36-3ed55be613a1', 'BCA' , NULL  , 'income'  ,         499, '2026-05-31', NULL              , NULL                  , 'Bank Interest')
  ) AS v(id, acct, xfer, type, amount, date, budget_name, fixed_name, description)
LEFT JOIN budgets b
  ON b.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid
  AND b.year_month = '2026-05' AND b.name = v.budget_name
LEFT JOIN fixed_expenses f
  ON f.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid AND f.year_month = '2026-05'
  AND f.name = v.fixed_name
ON CONFLICT (id) DO NOTHING;

COMMIT;
