-- ============================================================
-- Backfill: 'Finance Management 5.0 - Mar 2026.csv'
-- User 9e36aab2-dc6e-4ff6-9ae1-c81e82225424
-- BCA bank bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae | BCA VISA card 2f940480-5908-4c11-9fa1-9ff7a58c65c9
-- Idempotent: safe to re-run (natural-key upserts + deterministic txn ids).
-- Generated by supabase/imports/generate_monthly.py 2026-03
-- ============================================================
BEGIN;

-- NOTE: this spreadsheet does not categorize transactions, so every
--       transaction is imported with category_id = NULL.

-- Budgets for the month (periodic_amount = the spreadsheet's budget).
INSERT INTO budgets (user_id, name, year_month, periodic_amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Food', '2026-03', 2745000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET periodic_amount = EXCLUDED.periodic_amount;
INSERT INTO budgets (user_id, name, year_month, periodic_amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Transport', '2026-03', 2500000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET periodic_amount = EXCLUDED.periodic_amount;
INSERT INTO budgets (user_id, name, year_month, periodic_amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Social', '2026-03', 2455000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET periodic_amount = EXCLUDED.periodic_amount;
INSERT INTO budgets (user_id, name, year_month, periodic_amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Others', '2026-03', 1477509) ON CONFLICT (user_id, name, year_month) DO UPDATE SET periodic_amount = EXCLUDED.periodic_amount;

-- Fixed expenses (Monthly Expenses Details). Only paid ones are imported.
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'KPR', '2026-03', 12299123) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Papa', '2026-03', 5000000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Electricity VPP', '2026-03', 1000000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Electricity Alegria', '2026-03', 300000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'First Media', '2026-03', 427350) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'FF XIV', '2026-03', 460000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'IPL Cilejit', '2026-03', 192303) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'IPL VPP', '2026-03', 325000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'IPL Alegria', '2026-03', 100000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'PDAM', '2026-03', 100000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Paket Data', '2026-03', 100000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Netflix', '2026-03', 46500) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'ADM BCA', '2026-03', 20000) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;
INSERT INTO fixed_expenses (user_id, name, year_month, amount) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Youtube Premium', '2026-03', 18315) ON CONFLICT (user_id, name, year_month) DO UPDATE SET amount = EXCLUDED.amount;

-- Ensure monthly-balance rows exist so the recalc trigger has rows to update.
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2026-03', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2026-04', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('2f940480-5908-4c11-9fa1-9ff7a58c65c9', '2026-03', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('2f940480-5908-4c11-9fa1-9ff7a58c65c9', '2026-04', 0) ON CONFLICT (account_id, year_month) DO NOTHING;

-- Transactions (127 rows). category_id is always NULL (no categories).
-- Per row: (id, acct, xfer, type, amount, date, budget, fixed, description).
-- Rows that duplicate a non-monthly-sheet transaction are COMMENTED OUT and
-- marked 'DUPLICATE of non-monthly sheet' — the non-monthly sheet is kept as
-- the single source. Review them before running (uncomment to keep instead).
INSERT INTO transactions
  (id, user_id, account_id, transfer_account_id, type, status,
   amount, description, date, category_id, budget_id, fixed_expense_id)
SELECT
  v.id::uuid, '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid,
  CASE v.acct WHEN 'BCA' THEN 'bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae'::uuid WHEN 'CARD' THEN '2f940480-5908-4c11-9fa1-9ff7a58c65c9'::uuid END,
  CASE v.xfer WHEN 'CARD' THEN '2f940480-5908-4c11-9fa1-9ff7a58c65c9'::uuid ELSE NULL END,
  v.type::transaction_type, 'confirmed',
  v.amount, v.description, v.date::date,
  NULL,   -- category_id (this sheet does not categorize)
  b.id,   -- budget_id        (matched by name)
  f.id    -- fixed_expense_id (matched by name)
FROM (VALUES
    -- 2026-03-01
    ('9d9d1746-990e-5d76-a715-ff896fae536e', 'BCA' , NULL  , 'income'  ,    21504235, '2026-03-01', NULL              , NULL                  , 'Salary'),
    ('dbdda7e7-eada-5dba-967a-db26cf3ef125', 'BCA' , NULL  , 'expense' ,     5000000, '2026-03-01', NULL              , 'Papa'                , NULL),
    ('715c6b02-aa2e-53e5-a41f-754827737552', 'BCA' , NULL  , 'expense' ,       18315, '2026-03-01', NULL              , 'Youtube Premium'     , NULL),
    ('c95969b6-f2ac-57b6-bc56-09f1b5bf970a', 'BCA' , NULL  , 'expense' ,       46500, '2026-03-01', NULL              , 'Netflix'             , NULL),
    ('2065e575-344e-553d-9a97-b74b15eef319', 'BCA' , NULL  , 'expense' ,      325000, '2026-03-01', NULL              , 'IPL VPP'             , NULL),
    ('a0990364-8368-51d2-ae33-f02e47379bd4', 'CARD', NULL  , 'expense' ,      223001, '2026-03-01', NULL              , 'FF XIV'              , NULL),
    ('7a04c7ab-a6fc-5e56-a29e-2ad546711eb4', 'CARD', NULL  , 'expense' ,      256010, '2026-03-01', NULL              , 'Electricity Alegria' , NULL),
    ('d864ef64-83e1-501f-b86e-74639e281a38', 'CARD', NULL  , 'expense' ,        1800, '2026-03-01', 'Others'          , NULL                  , 'Electricity VPP Admin Fee'),
    ('338eaa54-efb2-59c1-8f00-143e7142d91d', 'CARD', NULL  , 'expense' ,     1000000, '2026-03-01', NULL              , 'Electricity VPP'     , NULL),
    -- ('f629a85a-ab6a-5fdd-bff9-f3b2686c3441', 'CARD', NULL  , 'expense' ,     1695885, '2026-03-01', NULL              , NULL                  , 'Apple Developer'),  -- DUPLICATE of non-monthly sheet — commented out for review, see overlaps-2026-03.md
    ('fa155588-6011-51e0-b442-2c6223e160fd', 'BCA' , NULL  , 'expense' ,     -162140, '2026-03-01', 'Social'          , NULL                  , NULL),
    ('12a80769-f759-5cfd-a3e2-8a50fc3dc6ea', 'BCA' , NULL  , 'expense' ,      -21000, '2026-03-01', 'Social'          , NULL                  , NULL),
    ('4367e9cf-5b0f-51f4-8b14-c0d8f2588f00', 'BCA' , NULL  , 'expense' ,     -101000, '2026-03-01', 'Social'          , NULL                  , NULL),
    ('5d193785-e9c8-53a5-93a2-0ac10b56c2c7', 'BCA' , NULL  , 'expense' ,      -23000, '2026-03-01', 'Social'          , NULL                  , NULL),
    -- 2026-03-02
    ('b812deb6-b604-5d33-a680-6b0481a6e542', 'CARD', NULL  , 'expense' ,      263700, '2026-03-02', 'Food'            , NULL                  , NULL),
    ('9ac6334f-7a6a-5fa8-b6af-f86d23817373', 'CARD', NULL  , 'expense' ,       51580, '2026-03-02', 'Food'            , NULL                  , NULL),
    -- 2026-03-03
    ('50d7c31e-2504-57b1-945e-126d1b95d62f', 'CARD', NULL  , 'expense' ,       29000, '2026-03-03', 'Food'            , NULL                  , NULL),
    -- 2026-03-04
    ('f2bc85a5-28b7-550e-8ba0-4b23a73b3a96', 'CARD', NULL  , 'expense' ,       63750, '2026-03-04', NULL              , 'PDAM'                , NULL),
    ('75f179c0-74ab-5174-8514-6fed68bde904', 'CARD', NULL  , 'expense' ,      197000, '2026-03-04', 'Social'          , NULL                  , NULL),
    ('33f4c8fa-2690-5c89-b8a7-a319d6a5e1d5', 'CARD', NULL  , 'expense' ,      319819, '2026-03-04', 'Social'          , NULL                  , NULL),
    -- 2026-03-05
    ('9932ee73-5aa1-5820-ab48-b340b1429b2a', 'CARD', NULL  , 'expense' ,      171800, '2026-03-05', 'Food'            , NULL                  , NULL),
    ('29ad3842-57cf-506b-b3d0-0f07c0caeae1', 'CARD', NULL  , 'expense' ,       41365, '2026-03-05', 'Food'            , NULL                  , NULL),
    ('3e9cf10f-cdc4-5b16-b882-88181111fa21', 'CARD', NULL  , 'expense' ,       15000, '2026-03-05', 'Food'            , NULL                  , NULL),
    ('a1b134df-9385-591e-91e2-c0fa69b96d71', 'CARD', NULL  , 'expense' ,      435000, '2026-03-05', 'Others'          , NULL                  , 'MD Gems'),
    -- ('732d4e7c-0a53-5af3-94bb-b197bea9cb79', 'CARD', NULL  , 'expense' ,      642443, '2026-03-05', NULL              , NULL                  , 'PBB Alegria'),  -- DUPLICATE of non-monthly sheet — commented out for review, see overlaps-2026-03.md
    -- 2026-03-06
    ('f47a664b-430b-5323-859d-1f68b2d67fbb', 'CARD', NULL  , 'expense' ,       98400, '2026-03-06', 'Others'          , NULL                  , 'Water'),
    ('8578ef73-955c-5fd0-9d05-4b971289b24e', 'CARD', NULL  , 'expense' ,      129001, '2026-03-06', 'Food'            , NULL                  , NULL),
    ('566caca5-5c08-540c-9f81-3585df91344f', 'CARD', NULL  , 'expense' ,      136700, '2026-03-06', 'Food'            , NULL                  , NULL),
    ('351aeffb-40c8-5c7f-add0-6accaf1e7659', 'CARD', NULL  , 'expense' ,       14500, '2026-03-06', 'Food'            , NULL                  , NULL),
    ('55573123-d561-51b9-895e-59fc9df8db51', 'CARD', NULL  , 'expense' ,       13000, '2026-03-06', 'Food'            , NULL                  , NULL),
    ('273c0c8f-d167-5e94-97f5-e724cd8aaf94', 'CARD', NULL  , 'expense' ,      -13000, '2026-03-06', 'Food'            , NULL                  , NULL),
    -- 2026-03-07
    ('9be27eb5-b891-526a-8fce-56d9cc9e19e3', 'CARD', NULL  , 'expense' ,       61000, '2026-03-07', 'Social'          , NULL                  , NULL),
    ('b37d791b-c3e4-5028-bbaa-7d00a647b6b9', 'BCA' , NULL  , 'expense' ,       72730, '2026-03-07', NULL              , 'IPL Alegria'         , NULL),
    -- 2026-03-08
    ('951a21df-3943-59ee-942a-49236a8793c0', 'CARD', NULL  , 'expense' ,      100000, '2026-03-08', 'Social'          , NULL                  , NULL),
    ('4497a801-930c-5ab5-8e84-9dc1783a2a42', 'CARD', NULL  , 'expense' ,       20000, '2026-03-08', 'Transport'       , NULL                  , NULL),
    ('60109c08-c4b9-5737-8656-3e1c1c4d9895', 'CARD', NULL  , 'expense' ,       14500, '2026-03-08', 'Social'          , NULL                  , NULL),
    ('d65308de-3af1-5c8c-9669-ceb46549f033', 'CARD', NULL  , 'expense' ,      150000, '2026-03-08', 'Social'          , NULL                  , NULL),
    ('47ef0360-ed58-5cde-a622-0cca28d8ce43', 'BCA' , NULL  , 'expense' ,     1000000, '2026-03-08', 'Transport'       , NULL                  , 'E-Money'),
    ('f7f69797-b6c4-5dea-a182-749c63244bc5', 'BCA' , NULL  , 'expense' ,        1500, '2026-03-08', 'Others'          , NULL                  , 'E-Money'),
    -- 2026-03-09
    ('56159944-1915-570d-a581-7a2454006729', 'CARD', NULL  , 'expense' ,      -21000, '2026-03-09', 'Food'            , NULL                  , NULL),
    ('dcd99e4b-fe5e-5337-9e23-425eaf789d45', 'CARD', NULL  , 'expense' ,       24000, '2026-03-09', 'Others'          , NULL                  , 'GU'),
    ('f953c3dc-796a-5130-9cb3-32bba4a3fe26', 'CARD', NULL  , 'expense' ,       47080, '2026-03-09', 'Food'            , NULL                  , NULL),
    ('03ca7c11-e39f-5e47-902b-0ec94ee35a63', 'CARD', NULL  , 'expense' ,        5000, '2026-03-09', 'Food'            , NULL                  , NULL),
    ('8490d8c0-1605-52c0-9b7d-6bd14aca26fa', 'CARD', NULL  , 'expense' ,       25200, '2026-03-09', 'Food'            , NULL                  , NULL),
    ('92f3d7f6-bec4-5687-9198-3948f5a4b6dd', 'CARD', NULL  , 'expense' ,       21000, '2026-03-09', 'Food'            , NULL                  , NULL),
    ('16807e6b-1466-55e7-a416-73fa861cde59', 'CARD', NULL  , 'expense' ,      133500, '2026-03-09', 'Food'            , NULL                  , NULL),
    ('e06bda4e-cd5d-5570-9806-59c3e86800d1', 'CARD', NULL  , 'expense' ,        2000, '2026-03-09', 'Food'            , NULL                  , NULL),
    ('628f8c50-10e2-5a4a-9b6a-ec73064da011', 'BCA' , NULL  , 'expense' ,        5900, '2026-03-09', 'Food'            , NULL                  , NULL),
    -- 2026-03-10
    ('1c581097-dc78-5916-9cd4-1da22f940511', 'CARD', NULL  , 'expense' ,       80000, '2026-03-10', NULL              , 'Paket Data'          , NULL),
    ('2f70274c-7b7e-50bd-9854-f23fc918eebf', 'CARD', NULL  , 'expense' ,       55955, '2026-03-10', 'Food'            , NULL                  , NULL),
    ('c735f9a9-820a-5fd9-bc5f-6455bf739f3c', 'CARD', NULL  , 'expense' ,        2000, '2026-03-10', 'Food'            , NULL                  , NULL),
    ('47fc299a-c667-5bbe-935c-f6b30f9e9cc3', 'CARD', NULL  , 'expense' ,       25200, '2026-03-10', 'Food'            , NULL                  , NULL),
    ('ff45f346-aba4-583b-a7d5-b9acf8a61107', 'CARD', NULL  , 'expense' ,      200000, '2026-03-10', 'Others'          , NULL                  , 'Blackmores'),
    ('be517fb6-024a-5689-8212-39b862769668', 'BCA' , NULL  , 'income'  ,      143991, '2026-03-10', NULL              , NULL                  , 'ST012T2'),
    -- 2026-03-11
    ('239e3389-033b-5455-9009-8218adcfaec5', 'CARD', NULL  , 'expense' ,    17387180, '2026-03-11', NULL              , NULL                  , NULL),
    ('a2da0a00-fd99-5965-b34d-e3cb40722945', 'CARD', NULL  , 'expense' ,      119300, '2026-03-11', 'Others'          , NULL                  , NULL),
    ('f9a5b25e-4998-597d-bcd3-644e708b12a3', 'CARD', NULL  , 'expense' ,       28153, '2026-03-11', 'Food'            , NULL                  , NULL),
    ('1f53b7a8-03ea-5545-b5fa-779cc72e5624', 'CARD', NULL  , 'expense' ,        2000, '2026-03-11', 'Food'            , NULL                  , NULL),
    ('142ada06-daff-50c2-93e8-d7609539b65f', 'CARD', NULL  , 'expense' ,       25200, '2026-03-11', 'Food'            , NULL                  , NULL),
    ('9043fb18-0d72-5baa-88d9-75379d455205', 'CARD', NULL  , 'expense' ,       62100, '2026-03-11', 'Food'            , NULL                  , NULL),
    ('24d135fe-e135-5bee-a351-e88e41cb98c9', 'BCA' , 'CARD', 'transfer',    18419028, '2026-03-11', NULL              , NULL                  , NULL),
    ('3f3bd174-5d58-5051-9e6c-534c6f87dadb', 'BCA' , NULL  , 'expense' ,      192303, '2026-03-11', NULL              , 'IPL Cilejit'         , NULL),
    ('8869f5f5-c359-519f-b77c-0453822a66f9', 'BCA' , NULL  , 'expense' ,      402000, '2026-03-11', 'Others'          , NULL                  , 'Dispenser Repair'),
    -- 2026-03-13
    ('efcdbd47-424f-5a56-be89-d3d2220c6fdd', 'CARD', NULL  , 'expense' ,      121797, '2026-03-13', 'Others'          , NULL                  , 'PBB'),
    ('1b82304b-18c7-51d4-a7cb-20f3ad92d318', 'CARD', NULL  , 'expense' ,     -121797, '2026-03-13', 'Others'          , NULL                  , 'PBB Cancelled'),
    ('855b9d82-3fee-58e5-96fc-96690ca16637', 'CARD', NULL  , 'expense' ,      427350, '2026-03-13', NULL              , 'First Media'         , NULL),
    ('04d7e3e3-e498-5e60-868e-398d10f681fa', 'CARD', NULL  , 'expense' ,      121797, '2026-03-13', 'Others'          , NULL                  , NULL),
    ('fc2c6ae4-dd54-5e6a-b5bf-bb2effe6fba5', 'CARD', NULL  , 'expense' ,       43500, '2026-03-13', 'Food'            , NULL                  , NULL),
    ('53e314b4-3c25-5ff8-8de5-11183dc415d4', 'CARD', NULL  , 'expense' ,        2000, '2026-03-13', 'Food'            , NULL                  , NULL),
    -- 2026-03-14
    ('afbc054e-752f-5ada-b863-cb9d2560d6f6', 'CARD', NULL  , 'expense' ,       46000, '2026-03-14', 'Transport'       , NULL                  , NULL),
    ('56620fa1-c3f7-5f6b-8610-f5047c9f8423', 'CARD', NULL  , 'expense' ,       20000, '2026-03-14', 'Social'          , NULL                  , NULL),
    ('bcf79511-538b-5381-b438-d3ad97ef9b43', 'CARD', NULL  , 'expense' ,      121500, '2026-03-14', 'Social'          , NULL                  , NULL),
    ('b8a4c5d4-6c1c-5caa-824b-7d003c115bc9', 'CARD', NULL  , 'expense' ,       28500, '2026-03-14', 'Transport'       , NULL                  , NULL),
    -- 2026-03-15
    ('153ab669-1db3-5603-b26f-5237eab13e65', 'CARD', NULL  , 'expense' ,       61000, '2026-03-15', 'Social'          , NULL                  , NULL),
    ('6de34aed-8d70-5f94-a51a-43eb1f8665ea', 'CARD', NULL  , 'expense' ,      149300, '2026-03-15', 'Food'            , NULL                  , NULL),
    ('6ed69aad-3470-5079-aab0-9073c913e77e', 'CARD', NULL  , 'expense' ,        2000, '2026-03-15', 'Food'            , NULL                  , NULL),
    -- 2026-03-17
    ('c04d1e94-5858-5598-ba75-a6e76d7f33c6', 'CARD', NULL  , 'expense' ,      471960, '2026-03-17', 'Social'          , NULL                  , NULL),
    -- 2026-03-18
    ('030b4464-e8cb-5037-9c63-a5e8db08e141', 'CARD', NULL  , 'expense' ,      111000, '2026-03-18', 'Food'            , NULL                  , NULL),
    ('6d40d23d-4a89-5852-b24f-f163d6dc6b2c', 'CARD', NULL  , 'expense' ,        2000, '2026-03-18', 'Food'            , NULL                  , NULL),
    ('5a6db763-1f2f-52f0-9c04-a23c696f41e3', 'CARD', NULL  , 'expense' ,      259319, '2026-03-18', 'Social'          , NULL                  , NULL),
    -- 2026-03-20
    ('bf29b997-5e9b-5a80-bfaf-48568b94062a', 'CARD', NULL  , 'expense' ,      376650, '2026-03-20', 'Social'          , NULL                  , NULL),
    ('85d61000-8d64-53ab-a624-78bf4fc86849', 'BCA' , 'CARD', 'transfer',     1000000, '2026-03-20', NULL              , NULL                  , NULL),
    ('676a57a2-f078-508b-9afb-50658b6764d3', 'BCA' , NULL  , 'expense' ,       20000, '2026-03-20', NULL              , 'ADM BCA'             , NULL),
    -- 2026-03-21
    ('1e965adf-3b79-5c0b-ac76-498ccefc71a5', 'CARD', NULL  , 'expense' ,      104000, '2026-03-21', 'Social'          , NULL                  , NULL),
    ('5faf5f75-0694-565d-a18e-7cffe84541b4', 'CARD', NULL  , 'expense' ,       98500, '2026-03-21', 'Transport'       , NULL                  , NULL),
    ('40bd3744-5615-5af5-947d-534def40afb3', 'CARD', NULL  , 'expense' ,       73000, '2026-03-21', 'Transport'       , NULL                  , NULL),
    ('18f85858-20d2-5681-b806-e26ec0d774fd', 'CARD', NULL  , 'expense' ,       73000, '2026-03-21', 'Transport'       , NULL                  , NULL),
    ('239da3c7-1631-56f9-a26f-64390d4508fc', 'CARD', NULL  , 'expense' ,        5000, '2026-03-21', 'Transport'       , NULL                  , NULL),
    ('8e955354-08da-5b28-a295-48283930d28d', 'CARD', NULL  , 'expense' ,       20000, '2026-03-21', 'Social'          , NULL                  , NULL),
    ('9a88f9ec-0aae-5481-b6af-a7275d23e91c', 'CARD', NULL  , 'expense' ,       71000, '2026-03-21', 'Transport'       , NULL                  , NULL),
    ('d0444f3b-7fba-52e0-97ea-1d2cfc02e2ca', 'CARD', NULL  , 'expense' ,      129500, '2026-03-21', 'Transport'       , NULL                  , NULL),
    ('3d922b8e-fd86-5eae-9f14-301208c23e7f', 'CARD', NULL  , 'expense' ,      -73000, '2026-03-21', 'Transport'       , NULL                  , NULL),
    ('7239e661-ae4d-5e3d-a129-62d7e7caf170', 'CARD', NULL  , 'expense' ,      -98500, '2026-03-21', 'Transport'       , NULL                  , NULL),
    ('c6041ae4-49b1-55b4-a422-495a2a832cec', 'CARD', NULL  , 'expense' ,      -71000, '2026-03-21', 'Transport'       , NULL                  , NULL),
    -- 2026-03-22
    ('1d71f36c-2c35-501c-8491-734be2f40adb', 'CARD', NULL  , 'expense' ,       93004, '2026-03-22', 'Social'          , NULL                  , NULL),
    ('accbd318-9911-503d-a359-0e4ddaf4f3f1', 'CARD', NULL  , 'expense' ,       30932, '2026-03-22', 'Social'          , NULL                  , NULL),
    ('4f63012a-5056-5357-a390-a9583774cb43', 'CARD', NULL  , 'expense' ,       50175, '2026-03-22', 'Others'          , NULL                  , 'Groceries'),
    -- 2026-03-23
    ('aa05d998-98d7-5d99-8736-04dda644d806', 'CARD', NULL  , 'expense' ,      437470, '2026-03-23', 'Others'          , NULL                  , 'Groceries'),
    -- ('1ef96a9f-edd1-5f63-b3ce-f6e96b2d11f9', 'CARD', NULL  , 'expense' ,     6939639, '2026-03-23', NULL              , NULL                  , 'D-Ark'),  -- DUPLICATE of non-monthly sheet — commented out for review, see overlaps-2026-03.md
    ('4f7d8098-1e9d-5798-84dc-10eae8340874', 'BCA' , 'CARD', 'transfer',    10000000, '2026-03-23', NULL              , NULL                  , NULL),
    -- 2026-03-25
    ('7764b7c7-b3b8-5c57-bfa9-3a814d32219b', 'CARD', NULL  , 'expense' ,       31000, '2026-03-25', 'Food'            , NULL                  , NULL),
    ('91674ff3-3b51-5412-8604-e7e7ef285f59', 'BCA' , NULL  , 'expense' ,    12299123, '2026-03-25', NULL              , 'KPR'                 , NULL),
    ('6846e75e-32a1-501f-a7c0-8390461f8dcf', 'BCA' , NULL  , 'expense' ,     1000000, '2026-03-25', 'Transport'       , NULL                  , 'EMoney'),
    ('86566074-7b19-508d-95ea-2fc85b884e00', 'BCA' , NULL  , 'expense' ,        1500, '2026-03-25', 'Others'          , NULL                  , 'EMoney'),
    ('6fb86588-e2f7-5473-b9d7-1a0b59018b3f', 'CARD', NULL  , 'expense' ,       10000, '2026-03-25', 'Others'          , NULL                  , 'Materai Credit Card'),
    -- 2026-03-26
    ('15222190-24d8-5969-a996-4d97a27cc6f3', 'CARD', NULL  , 'expense' ,       34000, '2026-03-26', 'Food'            , NULL                  , NULL),
    ('9e11618c-999d-5486-b8b9-827b861eaaad', 'CARD', NULL  , 'expense' ,       28000, '2026-03-26', 'Food'            , NULL                  , NULL),
    ('5d125228-1a51-514d-ad51-aa97516c8a5e', 'CARD', NULL  , 'expense' ,       29300, '2026-03-26', 'Food'            , NULL                  , NULL),
    ('542a155c-96ec-5d89-97a0-d9497125a9d5', 'CARD', NULL  , 'expense' ,      208500, '2026-03-26', 'Food'            , NULL                  , NULL),
    ('30709946-c5ac-5a95-9e76-cbdd72355b0f', 'CARD', NULL  , 'expense' ,        2000, '2026-03-26', 'Food'            , NULL                  , NULL),
    -- 2026-03-27
    ('afe900a8-9791-5b98-af85-79956ca3883f', 'CARD', NULL  , 'expense' ,       96100, '2026-03-27', 'Food'            , NULL                  , NULL),
    ('94edab75-d5b9-5f49-ac71-7b7e5c735e13', 'CARD', NULL  , 'expense' ,        2000, '2026-03-27', 'Food'            , NULL                  , NULL),
    -- 2026-03-28
    ('1ae44486-34cc-5163-b751-af254df60bee', 'CARD', NULL  , 'expense' ,       33500, '2026-03-28', 'Transport'       , NULL                  , NULL),
    ('e0b98f46-af64-5006-9304-1037010f5991', 'CARD', NULL  , 'expense' ,        2000, '2026-03-28', 'Transport'       , NULL                  , NULL),
    ('4b2a6671-8a19-5da1-895d-318a4ba1e9ad', 'CARD', NULL  , 'expense' ,      133000, '2026-03-28', 'Food'            , NULL                  , NULL),
    ('df2e3698-00a0-5ffb-ab59-8264cc2ae8bf', 'CARD', NULL  , 'expense' ,       15500, '2026-03-28', 'Transport'       , NULL                  , NULL),
    ('e8f80489-3f4b-5575-8275-7f4afa939fc9', 'CARD', NULL  , 'expense' ,        2000, '2026-03-28', 'Transport'       , NULL                  , NULL),
    ('d3be67d3-baea-505e-bfb5-132ea48208de', 'CARD', NULL  , 'expense' ,      222000, '2026-03-28', 'Others'          , NULL                  , NULL),
    -- 2026-03-29
    ('7bc7b646-496e-57fb-ac44-2b32e1941372', 'CARD', NULL  , 'expense' ,       51000, '2026-03-29', 'Social'          , NULL                  , NULL),
    ('de9f58eb-6221-5bf3-874e-34106c245bd9', 'CARD', NULL  , 'expense' ,      117800, '2026-03-29', 'Food'            , NULL                  , NULL),
    -- 2026-03-30
    ('be8e9448-3c40-5655-a1d7-4c99517bc9ae', 'CARD', NULL  , 'expense' ,      163000, '2026-03-30', 'Food'            , NULL                  , NULL),
    ('f3099cbf-5709-5483-ba16-e6b9652348f9', 'CARD', NULL  , 'expense' ,        2000, '2026-03-30', 'Food'            , NULL                  , NULL),
    -- 2026-03-31
    ('23f102d9-b6cf-5243-9a17-ddbea2bfb4ad', 'CARD', NULL  , 'expense' ,      221063, '2026-03-31', NULL              , 'FF XIV'              , NULL),
    ('4b952000-7f35-5017-a997-44a0ba22c7e0', 'CARD', NULL  , 'expense' ,      179000, '2026-03-31', 'Food'            , NULL                  , NULL),
    ('cac3cbb1-a4df-5e68-aaef-59737811c658', 'CARD', NULL  , 'expense' ,        2000, '2026-03-31', 'Food'            , NULL                  , NULL),
    ('13e5ad14-a471-5921-a1cf-cd6bfed73956', 'CARD', NULL  , 'expense' ,      133960, '2026-03-31', 'Food'            , NULL                  , NULL),
    ('dbea255b-9647-58de-a355-6544f8282717', 'BCA' , NULL  , 'income'  ,         179, '2026-03-31', NULL              , NULL                  , 'Bank Interest')
  ) AS v(id, acct, xfer, type, amount, date, budget_name, fixed_name, description)
LEFT JOIN budgets b
  ON b.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid
  AND b.year_month = '2026-03' AND b.name = v.budget_name
LEFT JOIN fixed_expenses f
  ON f.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid AND f.year_month = '2026-03'
  AND f.name = v.fixed_name
ON CONFLICT (id) DO NOTHING;

COMMIT;
