#!/usr/bin/env python3
"""
Seed the month BEFORE the earliest imported monthly sheet so its budget
carry-over (Row 2 of that sheet) is reflected in the app.

The app computes budget carry-over natively (v_budget_progress chains
remaining(M-1) -> carry_in(M) across consecutive months). The earliest imported
month has no prior lineage, so its carry_in defaults to 0 instead of its Row 2.
This generator creates, for the previous month, one budget per envelope plus a
single dummy BCA expense sized so that:

    remaining(prev) = periodic(prev) - dummy_spend = <first month's Row 2>

so carry_in(first month) = its Row 2. Verified to reproduce each sheet's Row 3.

Usage:
    python3 generate_carryover_seed.py <YYYY-MM>     # the EARLIEST imported month
    e.g. python3 generate_carryover_seed.py 2026-04  -> writes 2026-03-carryover-seed.sql

Notes:
  * Per the user's choice the dummy transactions land on the REAL BCA account, so
    they DO move the BCA balance (cascading forward). Account balances are being
    handled separately, so that's accepted for now.
  * Envelopes whose Row 2 is 0 are skipped (the first month anchors at carry_in 0
    with no prior-month budget needed).
  * When the real previous month is later imported, it supersedes this seed
    (re-run that month; delete this seed's rows first if they'd double up).
  * Idempotent: deterministic ids + natural-key upserts.
"""

import csv
import sys
import uuid
from pathlib import Path

if len(sys.argv) != 2 or len(sys.argv[1]) != 7 or sys.argv[1][4] != "-":
    raise SystemExit("usage: python3 generate_carryover_seed.py <YYYY-MM>  (earliest imported month)")

FIRST_YM = sys.argv[1]
_y, _m = int(FIRST_YM[:4]), int(FIRST_YM[5:])
_py, _pm = (_y - 1, 12) if _m == 1 else (_y, _m - 1)
PREV_YM = f"{_py:04d}-{_pm:02d}"

_ABBREV = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
           "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
CSV_PATH = Path(f"/mnt/e/Downloads/Finance Management 5.0 - {_ABBREV[_m - 1]} {_y}.csv")
OUT_PATH = Path(__file__).resolve().parent / f"{PREV_YM}-carryover-seed.sql"

USER_ID = "9e36aab2-dc6e-4ff6-9ae1-c81e82225424"
BCA = "bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae"
NS = uuid.UUID("b7e2c1a0-9d34-4f57-8e26-1a3c5b7d9f04")

# CSV columns: Row 2 carry-in lives in the budget columns; col M holds periodic.
COL = {"Food": 1, "Transport": 2, "Social": 3, "Other Expenses": 4}
BUDGET_DISPLAY = {"Other Expenses": "Others"}        # app budget name


def app_name(csv_name):
    return BUDGET_DISPLAY.get(csv_name, csv_name)


def money(s):
    s = (s or "").strip()
    if not s:
        return None
    neg = s.startswith("-")
    d = s.replace("-", "").replace("Rp", "").replace(",", "").strip()
    return None if not d else (-int(d) if neg else int(d))


def sqlstr(s):
    return "NULL" if s is None else "'" + s.replace("'", "''") + "'"


def main():
    if not CSV_PATH.exists():
        raise SystemExit(f"CSV not found: {CSV_PATH}")
    rows = list(csv.reader(CSV_PATH.open(encoding="utf-8-sig")))
    row2 = rows[1]   # sheet Row 2 = previous month's ending budget (carry-in)

    # periodic budget per envelope, from the col-M "Monthly Expenses Details".
    periodic = {}
    for r in rows:
        if len(r) > 12 and (r[11] or "").strip() in COL:
            periodic[app_name(r[11].strip())] = money(r[12])

    seeds = []  # (app_name, periodic, carry_in, dummy_spend)
    for csv_name, ci in COL.items():
        carry_in = money(row2[ci])
        name = app_name(csv_name)
        if not carry_in:                 # 0 or None -> no seed (anchors at 0)
            continue
        per = periodic[name]
        seeds.append((name, per, carry_in, per - carry_in))

    write_sql(seeds)
    for name, per, ci, dummy in seeds:
        print(f"  {name:10} periodic {per:>10} - dummy {dummy:>10} = remaining {ci:>10}")
    print(f"Wrote {OUT_PATH}  (seed {PREV_YM} -> carry_in for {FIRST_YM})")


def write_sql(seeds):
    out = []
    w = out.append
    w("-- ============================================================")
    w(f"-- Budget carry-over seed for {PREV_YM} -> feeds carry_in of {FIRST_YM}.")
    w(f"-- Values = Row 2 of '{CSV_PATH.name}'. Reproduces that sheet's Row 3.")
    w(f"-- User {USER_ID} | dummy expenses on BCA {BCA} (DO move the BCA balance).")
    w("-- Run this BEFORE the per-month imports. Idempotent.")
    w("-- Generated by supabase/imports/generate_carryover_seed.py")
    w("-- ============================================================")
    w("BEGIN;")
    w("")
    w(f"-- {PREV_YM} budgets (standard periodic; carry-over chains into {FIRST_YM}).")
    for name, per, _ci, _d in seeds:
        w(f"INSERT INTO budgets (user_id, name, year_month, periodic_amount) "
          f"VALUES ({sqlstr(USER_ID)}, {sqlstr(name)}, {sqlstr(PREV_YM)}, {per}) "
          f"ON CONFLICT (user_id, name, year_month) "
          f"DO UPDATE SET periodic_amount = EXCLUDED.periodic_amount;")
    w("")
    w(f"INSERT INTO account_monthly_balances (account_id, year_month, balance) "
      f"VALUES ({sqlstr(BCA)}, {sqlstr(PREV_YM)}, 0) "
      f"ON CONFLICT (account_id, year_month) DO NOTHING;")
    w("")
    w("-- Dummy BCA expense per envelope: periodic - spend = remaining (= Row 2).")
    w("INSERT INTO transactions")
    w("  (id, user_id, account_id, transfer_account_id, type, status,")
    w("   amount, description, date, category_id, budget_id, fixed_expense_id)")
    w("SELECT")
    w(f"  v.id::uuid, {sqlstr(USER_ID)}::uuid, {sqlstr(BCA)}::uuid, NULL,")
    w("  'expense'::transaction_type, 'confirmed',")
    w("  v.amount, v.description, v.date::date,")
    w("  NULL, b.id, NULL")
    w("FROM (VALUES")
    last = len(seeds) - 1
    for idx, (name, _per, _ci, dummy) in enumerate(seeds):
        tid = uuid.uuid5(NS, f"{PREV_YM}|carryover|{name}")
        desc = f"Carry-over seed -> {FIRST_YM}"
        comma = "," if idx < last else ""
        w(f"    ('{tid}', {dummy}, '{PREV_YM}-01', {sqlstr(desc)}, {sqlstr(name)}){comma}")
    w("  ) AS v(id, amount, date, description, budget_name)")
    w(f"LEFT JOIN budgets b ON b.user_id = {sqlstr(USER_ID)}::uuid "
      f"AND b.year_month = {sqlstr(PREV_YM)} AND b.name = v.budget_name")
    w("ON CONFLICT (id) DO NOTHING;")
    w("")
    w("COMMIT;")
    OUT_PATH.write_text("\n".join(out) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
