-- ============================================================
-- Backfill: 'Finance Management 5.0 - Non-Monthly Transaction.csv'
-- User 9e36aab2-dc6e-4ff6-9ae1-c81e82225424
-- Default account BCA bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae
-- Credit card        2f940480-5908-4c11-9fa1-9ff7a58c65c9  (flip a row's 'BCA' token to 'CARD' to use it)
-- No budgets / no fixed expenses. Every row is an expense (negative = money back).
-- Idempotent: re-runnable, but ON CONFLICT (id) DO NOTHING means edits to
-- already-imported rows are ignored — make account edits BEFORE the first run.
-- Rows marked 'Also in monthly <YYYY-MM> sheet' are the same real transaction
-- as a monthly-sheet row. This sheet is kept as the source, so they stay
-- ACTIVE here; the matching monthly row is commented out (no double-counting).
--
-- STRUCTURE: run the SETUP block once, then each month block (each is its own
-- transaction) — in date order if you want balances to settle as you go.
-- Generated by supabase/imports/generate_nonmonthly.py
-- ============================================================

-- ============================================================
-- SETUP — run once before the per-month blocks.
-- ============================================================
BEGIN;

-- Categories (create-or-reuse by name; event-scoped names kept literal).
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Car Expenses') ON CONFLICT (user_id, name) DO NOTHING;
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Savings') ON CONFLICT (user_id, name) DO NOTHING;
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Housing 2024') ON CONFLICT (user_id, name) DO NOTHING;
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'PC Upgrade 2024') ON CONFLICT (user_id, name) DO NOTHING;
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'SQ Parking') ON CONFLICT (user_id, name) DO NOTHING;
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Tooth Maintenance') ON CONFLICT (user_id, name) DO NOTHING;
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Tineco') ON CONFLICT (user_id, name) DO NOTHING;
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Jember Expenses') ON CONFLICT (user_id, name) DO NOTHING;
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'KlinWater') ON CONFLICT (user_id, name) DO NOTHING;
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Artiz Studio') ON CONFLICT (user_id, name) DO NOTHING;
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Jawa Trip Expenses') ON CONFLICT (user_id, name) DO NOTHING;
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'ExitLag') ON CONFLICT (user_id, name) DO NOTHING;
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'ROG Ally Update') ON CONFLICT (user_id, name) DO NOTHING;
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Housing 2025') ON CONFLICT (user_id, name) DO NOTHING;
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Surabaya Expenses') ON CONFLICT (user_id, name) DO NOTHING;
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Wedding') ON CONFLICT (user_id, name) DO NOTHING;
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Secret Lab') ON CONFLICT (user_id, name) DO NOTHING;
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Fashion') ON CONFLICT (user_id, name) DO NOTHING;
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'MRT Cikarang') ON CONFLICT (user_id, name) DO NOTHING;
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Software Development') ON CONFLICT (user_id, name) DO NOTHING;
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'STNK') ON CONFLICT (user_id, name) DO NOTHING;
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'PBB Alegria') ON CONFLICT (user_id, name) DO NOTHING;
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'House Renovation') ON CONFLICT (user_id, name) DO NOTHING;
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'iPhone Air') ON CONFLICT (user_id, name) DO NOTHING;
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Digivice') ON CONFLICT (user_id, name) DO NOTHING;
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Google One') ON CONFLICT (user_id, name) DO NOTHING;
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Shoes') ON CONFLICT (user_id, name) DO NOTHING;
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'Bluetooth Keyboard') ON CONFLICT (user_id, name) DO NOTHING;
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'ST012T2') ON CONFLICT (user_id, name) DO NOTHING;
INSERT INTO categories (user_id, name) VALUES ('9e36aab2-dc6e-4ff6-9ae1-c81e82225424', 'PIA') ON CONFLICT (user_id, name) DO NOTHING;

-- Monthly-balance rows for every month in range (both accounts) so the
-- balance-recalc trigger has rows to update, regardless of run order.
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2024-06', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2024-07', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2024-08', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2024-09', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2024-10', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2024-11', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2024-12', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2025-01', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2025-02', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2025-03', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2025-04', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2025-05', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2025-06', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2025-07', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2025-08', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2025-09', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2025-10', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2025-11', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2025-12', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2026-01', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2026-02', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2026-03', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2026-04', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2026-05', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae', '2026-06', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('2f940480-5908-4c11-9fa1-9ff7a58c65c9', '2024-06', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('2f940480-5908-4c11-9fa1-9ff7a58c65c9', '2024-07', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('2f940480-5908-4c11-9fa1-9ff7a58c65c9', '2024-08', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('2f940480-5908-4c11-9fa1-9ff7a58c65c9', '2024-09', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('2f940480-5908-4c11-9fa1-9ff7a58c65c9', '2024-10', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('2f940480-5908-4c11-9fa1-9ff7a58c65c9', '2024-11', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('2f940480-5908-4c11-9fa1-9ff7a58c65c9', '2024-12', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('2f940480-5908-4c11-9fa1-9ff7a58c65c9', '2025-01', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('2f940480-5908-4c11-9fa1-9ff7a58c65c9', '2025-02', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('2f940480-5908-4c11-9fa1-9ff7a58c65c9', '2025-03', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('2f940480-5908-4c11-9fa1-9ff7a58c65c9', '2025-04', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('2f940480-5908-4c11-9fa1-9ff7a58c65c9', '2025-05', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('2f940480-5908-4c11-9fa1-9ff7a58c65c9', '2025-06', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('2f940480-5908-4c11-9fa1-9ff7a58c65c9', '2025-07', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('2f940480-5908-4c11-9fa1-9ff7a58c65c9', '2025-08', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('2f940480-5908-4c11-9fa1-9ff7a58c65c9', '2025-09', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('2f940480-5908-4c11-9fa1-9ff7a58c65c9', '2025-10', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('2f940480-5908-4c11-9fa1-9ff7a58c65c9', '2025-11', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('2f940480-5908-4c11-9fa1-9ff7a58c65c9', '2025-12', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('2f940480-5908-4c11-9fa1-9ff7a58c65c9', '2026-01', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('2f940480-5908-4c11-9fa1-9ff7a58c65c9', '2026-02', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('2f940480-5908-4c11-9fa1-9ff7a58c65c9', '2026-03', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('2f940480-5908-4c11-9fa1-9ff7a58c65c9', '2026-04', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('2f940480-5908-4c11-9fa1-9ff7a58c65c9', '2026-05', 0) ON CONFLICT (account_id, year_month) DO NOTHING;
INSERT INTO account_monthly_balances (account_id, year_month, balance) VALUES ('2f940480-5908-4c11-9fa1-9ff7a58c65c9', '2026-06', 0) ON CONFLICT (account_id, year_month) DO NOTHING;

COMMIT;

-- ============================================================
-- 2024-06  (19 transaction(s))
-- ============================================================
BEGIN;
INSERT INTO transactions
  (id, user_id, account_id, transfer_account_id, type, status,
   amount, description, date, category_id, budget_id, fixed_expense_id)
SELECT
  v.id::uuid, '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid,
  CASE v.acct WHEN 'BCA' THEN 'bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae'::uuid WHEN 'CARD' THEN '2f940480-5908-4c11-9fa1-9ff7a58c65c9'::uuid END,
  NULL,                       -- transfer_account_id (no transfers here)
  'expense'::transaction_type, 'confirmed',
  v.amount, v.description, v.date::date,
  c.id,                       -- category_id (matched by name)
  NULL, NULL                  -- budget_id, fixed_expense_id (n/a)
FROM (VALUES
    ('d1c3b825-8394-536e-aa7b-7a3599034ffc', 'BCA' ,       5000000, '2024-06-01', 'Car Expenses'          , 'Booking Fee'),
    ('254ca088-3a9e-5789-b35a-a8049d4ca9f6', 'BCA' ,     -19350000, '2024-06-03', 'Savings'               , 'Bareksa June 2024'),
    ('aa02c93c-23aa-5c42-9dc9-8424f13d1ca0', 'BCA' ,     -10272411, '2024-06-03', 'Housing 2024'          , 'BTN'),
    ('ebc404aa-5721-5c8b-8774-9867b1fe053c', 'BCA' ,       -174500, '2024-06-03', 'Housing 2024'          , 'Danamon'),
    ('6b6602c8-dfc0-5fe7-8166-925e3efd7a34', 'BCA' ,        -25000, '2024-06-03', 'Housing 2024'          , 'Danamon'),
    ('de9c46df-fa8f-5798-97a7-99781571ca05', 'BCA' ,      -9544693, '2024-06-03', 'Housing 2024'          , 'Danamon'),
    ('e2216ed0-508a-54f6-8a73-0261a1f40c96', 'BCA' ,      -3019616, '2024-06-04', 'Savings'               , 'Bareksa June 2024'),
    ('fbd40de8-c15d-5461-adfa-92bc589b9ac1', 'BCA' ,     -17106596, '2024-06-04', 'Savings'               , 'Bareksa June 2024'),
    ('39a544b5-4d2d-56df-9b4c-8c8954803174', 'BCA' ,     -13694550, '2024-06-06', 'Savings'               , 'Bareksa June 2024'),
    ('969e87b1-2beb-56ad-9913-58c1c1788120', 'BCA' ,     -13353994, '2024-06-06', 'Savings'               , 'Bareksa June 2024'),
    ('efdcefc7-1f9b-53eb-ac5b-778d002991f5', 'BCA' ,        502500, '2024-06-06', 'Housing 2024'          , 'Sertifikat Rumah'),
    ('10a56bc5-6a11-53ac-aa51-ec85c54292ef', 'BCA' ,     -15082489, '2024-06-07', 'Savings'               , 'Bareksa June 2024'),
    ('c366e66e-836c-5fef-b4b3-d98708a955a9', 'BCA' ,      76954880, '2024-06-13', 'Car Expenses'          , 'DP Wuling'),
    ('b240e7c4-1d54-594b-bbac-5252bcb7d7ec', 'BCA' ,       1500000, '2024-06-13', 'Car Expenses'          , 'STCK'),
    ('fe99802b-c1c2-518d-aeb0-ee5bde6030d0', 'BCA' ,       2200000, '2024-06-13', 'Car Expenses'          , 'Meteran Baru 7700 (Returned)'),
    ('5428d94c-4347-523c-9fe5-3e368e7319f2', 'BCA' ,        175000, '2024-06-21', 'Car Expenses'          , 'Talang Air'),
    ('72c248be-13a8-586d-9e06-54ac2839480b', 'BCA' ,        986549, '2024-06-24', 'Car Expenses'          , 'Ban'),
    ('b152f086-7cdc-52cc-8a76-601d52521549', 'BCA' ,      -2217477, '2024-06-28', 'Car Expenses'          , 'Meteran Baru 7700 (Returned)'),
    ('bab89d8d-85cd-5d04-bb28-cd464ca37a7a', 'BCA' ,       2100000, '2024-06-29', 'Car Expenses'          , 'Meteran Baru 7700 (OVO)')
  ) AS v(id, acct, amount, date, category_name, description)
LEFT JOIN categories c ON c.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid AND c.name = v.category_name
ON CONFLICT (id) DO NOTHING;
COMMIT;

-- ============================================================
-- 2024-07  (11 transaction(s))
-- ============================================================
BEGIN;
INSERT INTO transactions
  (id, user_id, account_id, transfer_account_id, type, status,
   amount, description, date, category_id, budget_id, fixed_expense_id)
SELECT
  v.id::uuid, '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid,
  CASE v.acct WHEN 'BCA' THEN 'bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae'::uuid WHEN 'CARD' THEN '2f940480-5908-4c11-9fa1-9ff7a58c65c9'::uuid END,
  NULL,                       -- transfer_account_id (no transfers here)
  'expense'::transaction_type, 'confirmed',
  v.amount, v.description, v.date::date,
  c.id,                       -- category_id (matched by name)
  NULL, NULL                  -- budget_id, fixed_expense_id (n/a)
FROM (VALUES
    ('20c9f639-f49d-57c2-b042-c10d19210361', 'BCA' ,        107700, '2024-07-01', 'Car Expenses'          , 'Case Wuling Remote'),
    ('1d6266af-6576-542f-945d-aefe066099b4', 'BCA' ,        106100, '2024-07-01', 'Car Expenses'          , 'Car Mount'),
    ('1de3e8ae-681f-53d4-870d-638f7129579e', 'BCA' ,        149000, '2024-07-01', 'Car Expenses'          , 'Charger cable extension'),
    ('047567ff-414a-5ff9-b6b5-e4cb743c15cc', 'BCA' ,         51000, '2024-07-03', 'Car Expenses'          , 'Sarung Ban Serap'),
    ('afbf89d7-382c-57ed-a2a8-56f6cdcdfc6b', 'BCA' ,        181700, '2024-07-04', 'Car Expenses'          , 'Grounding Stick'),
    ('f2c7f407-5382-5cfa-91cc-781b74a6e0cf', 'BCA' ,        117520, '2024-07-04', 'Car Expenses'          , 'Tongsis e-toll'),
    ('ee08b582-3ca1-57e2-92f1-297366417914', 'BCA' ,        131020, '2024-07-06', 'Car Expenses'          , 'Tissue box + kucing'),
    ('ffb7def8-b9f8-5aa0-a98d-f15c31de2f61', 'BCA' ,         95000, '2024-07-07', 'Car Expenses'          , 'Karpet Mobil'),
    ('17efbc17-bf7c-5629-a286-8dbfbd75e44e', 'BCA' ,        878880, '2024-07-07', 'Car Expenses'          , 'Dashcam'),
    ('c30d150d-b058-51c3-b5a2-c335dc216f8a', 'BCA' ,        114409, '2024-07-11', 'Car Expenses'          , 'Tire Sealant'),
    ('e732b2cc-2248-5a77-b146-540f359eb164', 'BCA' ,        502500, '2024-07-16', 'Car Expenses'          , 'Grounding PLN')
  ) AS v(id, acct, amount, date, category_name, description)
LEFT JOIN categories c ON c.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid AND c.name = v.category_name
ON CONFLICT (id) DO NOTHING;
COMMIT;

-- ============================================================
-- 2024-08  (3 transaction(s))
-- ============================================================
BEGIN;
INSERT INTO transactions
  (id, user_id, account_id, transfer_account_id, type, status,
   amount, description, date, category_id, budget_id, fixed_expense_id)
SELECT
  v.id::uuid, '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid,
  CASE v.acct WHEN 'BCA' THEN 'bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae'::uuid WHEN 'CARD' THEN '2f940480-5908-4c11-9fa1-9ff7a58c65c9'::uuid END,
  NULL,                       -- transfer_account_id (no transfers here)
  'expense'::transaction_type, 'confirmed',
  v.amount, v.description, v.date::date,
  c.id,                       -- category_id (matched by name)
  NULL, NULL                  -- budget_id, fixed_expense_id (n/a)
FROM (VALUES
    ('76c2645a-0ae8-5451-a951-0d9ac2b48892', 'BCA' ,        200544, '2024-08-01', 'Car Expenses'          , 'Kabel Grounding'),
    ('f86a4262-b866-50c8-942a-969689713627', 'BCA' ,        106550, '2024-08-01', 'Car Expenses'          , 'Flexible Conduit'),
    ('91a37437-8067-50cc-9ae8-2f32cc65d164', 'BCA' ,        188600, '2024-08-05', 'Car Expenses'          , 'KIIP Car Holder')
  ) AS v(id, acct, amount, date, category_name, description)
LEFT JOIN categories c ON c.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid AND c.name = v.category_name
ON CONFLICT (id) DO NOTHING;
COMMIT;

-- ============================================================
-- 2024-09  (1 transaction(s))
-- ============================================================
BEGIN;
INSERT INTO transactions
  (id, user_id, account_id, transfer_account_id, type, status,
   amount, description, date, category_id, budget_id, fixed_expense_id)
SELECT
  v.id::uuid, '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid,
  CASE v.acct WHEN 'BCA' THEN 'bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae'::uuid WHEN 'CARD' THEN '2f940480-5908-4c11-9fa1-9ff7a58c65c9'::uuid END,
  NULL,                       -- transfer_account_id (no transfers here)
  'expense'::transaction_type, 'confirmed',
  v.amount, v.description, v.date::date,
  c.id,                       -- category_id (matched by name)
  NULL, NULL                  -- budget_id, fixed_expense_id (n/a)
FROM (VALUES
    ('2a86d418-6005-5cdb-a1b4-19a993d8ad31', 'BCA' ,       2905700, '2024-09-22', 'PC Upgrade 2024'       , 'ASROCK Z790 PG LIGHTNING')
  ) AS v(id, acct, amount, date, category_name, description)
LEFT JOIN categories c ON c.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid AND c.name = v.category_name
ON CONFLICT (id) DO NOTHING;
COMMIT;

-- ============================================================
-- 2024-10  (7 transaction(s))
-- ============================================================
BEGIN;
INSERT INTO transactions
  (id, user_id, account_id, transfer_account_id, type, status,
   amount, description, date, category_id, budget_id, fixed_expense_id)
SELECT
  v.id::uuid, '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid,
  CASE v.acct WHEN 'BCA' THEN 'bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae'::uuid WHEN 'CARD' THEN '2f940480-5908-4c11-9fa1-9ff7a58c65c9'::uuid END,
  NULL,                       -- transfer_account_id (no transfers here)
  'expense'::transaction_type, 'confirmed',
  v.amount, v.description, v.date::date,
  c.id,                       -- category_id (matched by name)
  NULL, NULL                  -- budget_id, fixed_expense_id (n/a)
FROM (VALUES
    ('a2a1ccef-da21-5793-96d0-fa8e1f047ec1', 'BCA' ,       2138283, '2024-10-01', 'PC Upgrade 2024'       , 'Intel Core i7-14700'),
    ('3b20748b-8912-554f-9a44-84fd66158eff', 'BCA' ,        550433, '2024-10-01', 'PC Upgrade 2024'       , 'XPG LANCER RAM PC DDR5 32GB (2X16GB)'),
    ('8787a8f4-6fd6-5b4d-bf99-29f05c7a9cd0', 'BCA' ,        245616, '2024-10-01', 'PC Upgrade 2024'       , 'ThermalRight Phantom Spirit 120 SE'),
    ('975fa7e9-91ad-57c5-9b48-0d1769897331', 'BCA' ,        146900, '2024-10-01', 'PC Upgrade 2024'       , 'UGREEN Kabel USB 3.0 to Sata 2.5 inch SSD HDD Converter'),
    ('6b7ab7d1-9390-572f-9f09-1e284364f662', 'BCA' ,       1227450, '2024-10-01', 'PC Upgrade 2024'       , 'WD SSD 1TB'),
    ('c2613f73-1a91-5e15-8834-4b4593d78962', 'BCA' ,        169453, '2024-10-01', 'PC Upgrade 2024'       , 'ARCTIC P12 PWM PST Pack of 5'),
    ('41d22bc0-5b18-5916-8354-df2ac236822e', 'BCA' ,      -2249650, '2024-10-01', 'PC Upgrade 2024'       , 'Old PC Parts Sold')
  ) AS v(id, acct, amount, date, category_name, description)
LEFT JOIN categories c ON c.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid AND c.name = v.category_name
ON CONFLICT (id) DO NOTHING;
COMMIT;

-- ============================================================
-- 2024-11  (4 transaction(s))
-- ============================================================
BEGIN;
INSERT INTO transactions
  (id, user_id, account_id, transfer_account_id, type, status,
   amount, description, date, category_id, budget_id, fixed_expense_id)
SELECT
  v.id::uuid, '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid,
  CASE v.acct WHEN 'BCA' THEN 'bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae'::uuid WHEN 'CARD' THEN '2f940480-5908-4c11-9fa1-9ff7a58c65c9'::uuid END,
  NULL,                       -- transfer_account_id (no transfers here)
  'expense'::transaction_type, 'confirmed',
  v.amount, v.description, v.date::date,
  c.id,                       -- category_id (matched by name)
  NULL, NULL                  -- budget_id, fixed_expense_id (n/a)
FROM (VALUES
    ('76cc92bb-2ff2-5d5b-be03-5e180a33ba75', 'BCA' ,       2138283, '2024-11-01', 'PC Upgrade 2024'       , 'Intel Core i7-14700'),
    ('aa03cf0a-96be-549b-afbe-a2a2a1df53bd', 'BCA' ,        550433, '2024-11-01', 'PC Upgrade 2024'       , 'XPG LANCER RAM PC DDR5 32GB (2X16GB)'),
    ('9f826b45-a2b7-58f1-b178-8f3bf323c796', 'BCA' ,        245616, '2024-11-01', 'PC Upgrade 2024'       , 'ThermalRight Phantom Spirit 120 SE'),
    ('6da0ec93-0d30-5541-aa9b-6820532d6d32', 'BCA' ,        169453, '2024-11-01', 'PC Upgrade 2024'       , 'ARCTIC P12 PWM PST Pack of 5')
  ) AS v(id, acct, amount, date, category_name, description)
LEFT JOIN categories c ON c.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid AND c.name = v.category_name
ON CONFLICT (id) DO NOTHING;
COMMIT;

-- ============================================================
-- 2024-12  (6 transaction(s))
-- ============================================================
BEGIN;
INSERT INTO transactions
  (id, user_id, account_id, transfer_account_id, type, status,
   amount, description, date, category_id, budget_id, fixed_expense_id)
SELECT
  v.id::uuid, '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid,
  CASE v.acct WHEN 'BCA' THEN 'bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae'::uuid WHEN 'CARD' THEN '2f940480-5908-4c11-9fa1-9ff7a58c65c9'::uuid END,
  NULL,                       -- transfer_account_id (no transfers here)
  'expense'::transaction_type, 'confirmed',
  v.amount, v.description, v.date::date,
  c.id,                       -- category_id (matched by name)
  NULL, NULL                  -- budget_id, fixed_expense_id (n/a)
FROM (VALUES
    ('2db93599-043e-5742-8d8f-9ba00be699ee', 'BCA' ,       2138283, '2024-12-01', 'PC Upgrade 2024'       , 'Intel Core i7-14700'),
    ('0ae8db8b-bee6-506b-9efc-118d7f802ccc', 'BCA' ,        550433, '2024-12-01', 'PC Upgrade 2024'       , 'XPG LANCER RAM PC DDR5 32GB (2X16GB)'),
    ('dcda1ef5-630e-5914-b370-decc6e14907d', 'BCA' ,        245616, '2024-12-01', 'PC Upgrade 2024'       , 'ThermalRight Phantom Spirit 120 SE'),
    ('13a5c054-461d-5a5e-bcd5-c32994f79c94', 'BCA' ,        169453, '2024-12-01', 'PC Upgrade 2024'       , 'ARCTIC P12 PWM PST Pack of 5'),
    ('f50eedb1-3422-5435-9262-a485afc3c028', 'BCA' ,       5280000, '2024-12-06', 'SQ Parking'            , 'Parkir Jan-Dec 2025'),
    ('a856d9ec-ebc7-5bff-882b-ccabdf3cc705', 'BCA' ,       4315000, '2024-12-29', 'Tooth Maintenance'     , 'Retainer')
  ) AS v(id, acct, amount, date, category_name, description)
LEFT JOIN categories c ON c.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid AND c.name = v.category_name
ON CONFLICT (id) DO NOTHING;
COMMIT;

-- ============================================================
-- 2025-01  (5 transaction(s))
-- ============================================================
BEGIN;
INSERT INTO transactions
  (id, user_id, account_id, transfer_account_id, type, status,
   amount, description, date, category_id, budget_id, fixed_expense_id)
SELECT
  v.id::uuid, '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid,
  CASE v.acct WHEN 'BCA' THEN 'bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae'::uuid WHEN 'CARD' THEN '2f940480-5908-4c11-9fa1-9ff7a58c65c9'::uuid END,
  NULL,                       -- transfer_account_id (no transfers here)
  'expense'::transaction_type, 'confirmed',
  v.amount, v.description, v.date::date,
  c.id,                       -- category_id (matched by name)
  NULL, NULL                  -- budget_id, fixed_expense_id (n/a)
FROM (VALUES
    ('93c40a47-ee6e-5e1b-920e-b96f2d22d940', 'BCA' ,       5419000, '2025-01-19', 'Tineco'                , 'Tineco'),
    ('1be03f14-9dc1-55f7-bb65-6090a301e90f', 'BCA' ,       1505000, '2025-01-28', 'Car Expenses'          , 'MCB RCCB'),
    ('041bd74a-b8cb-5e79-b047-eb748aae1111', 'BCA' ,       1142967, '2025-01-28', 'Jember Expenses'       , 'Agoda'),
    ('3f0cf522-d87c-5482-bebe-9958cb7dc51f', 'BCA' ,       1615000, '2025-01-29', 'KlinWater'             , 'KlinWater'),
    ('01cf0668-1ac6-5707-8e40-c4d4849b0d79', 'BCA' ,      18800000, '2025-01-31', 'Artiz Studio'          , 'Artiz Studio')
  ) AS v(id, acct, amount, date, category_name, description)
LEFT JOIN categories c ON c.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid AND c.name = v.category_name
ON CONFLICT (id) DO NOTHING;
COMMIT;

-- ============================================================
-- 2025-02  (4 transaction(s))
-- ============================================================
BEGIN;
INSERT INTO transactions
  (id, user_id, account_id, transfer_account_id, type, status,
   amount, description, date, category_id, budget_id, fixed_expense_id)
SELECT
  v.id::uuid, '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid,
  CASE v.acct WHEN 'BCA' THEN 'bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae'::uuid WHEN 'CARD' THEN '2f940480-5908-4c11-9fa1-9ff7a58c65c9'::uuid END,
  NULL,                       -- transfer_account_id (no transfers here)
  'expense'::transaction_type, 'confirmed',
  v.amount, v.description, v.date::date,
  c.id,                       -- category_id (matched by name)
  NULL, NULL                  -- budget_id, fixed_expense_id (n/a)
FROM (VALUES
    ('a8286a46-fccf-5747-9ca2-04ae212fb034', 'BCA' ,      -1332550, '2025-02-01', 'PC Upgrade 2024'       , 'Motherboard'),
    ('087b7d11-3cc1-5332-a750-b9ebbbcda140', 'BCA' ,       3028557, '2025-02-11', 'Jember Expenses'       , 'Pesawat Jember Tokopedia'),
    ('81de9623-9fc1-5eb5-bf86-a766e2a49675', 'BCA' ,      -1500000, '2025-02-11', 'Jember Expenses'       , 'Pesawat Jember Tokopedia'),
    ('40502fdf-8dd2-53dd-856f-71ddb15392b0', 'BCA' ,        374000, '2025-02-23', 'Jawa Trip Expenses'    , 'Magelang Vacation')
  ) AS v(id, acct, amount, date, category_name, description)
LEFT JOIN categories c ON c.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid AND c.name = v.category_name
ON CONFLICT (id) DO NOTHING;
COMMIT;

-- ============================================================
-- 2025-03  (7 transaction(s))
-- ============================================================
BEGIN;
INSERT INTO transactions
  (id, user_id, account_id, transfer_account_id, type, status,
   amount, description, date, category_id, budget_id, fixed_expense_id)
SELECT
  v.id::uuid, '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid,
  CASE v.acct WHEN 'BCA' THEN 'bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae'::uuid WHEN 'CARD' THEN '2f940480-5908-4c11-9fa1-9ff7a58c65c9'::uuid END,
  NULL,                       -- transfer_account_id (no transfers here)
  'expense'::transaction_type, 'confirmed',
  v.amount, v.description, v.date::date,
  c.id,                       -- category_id (matched by name)
  NULL, NULL                  -- budget_id, fixed_expense_id (n/a)
FROM (VALUES
    ('4c48c371-f21f-5ddf-ac3f-83da355bbb7a', 'BCA' ,        129423, '2025-03-27', 'Jember Expenses'       , 'Lapis Legit'),
    ('8232e900-4e97-5678-87c4-1e7d6f7d19cd', 'BCA' ,         20000, '2025-03-29', 'Jember Expenses'       , 'Food'),
    ('6bef9ccc-dcde-5414-8326-31f816a43cef', 'BCA' ,         84700, '2025-03-30', 'Jember Expenses'       , 'Larisso'),
    ('c9bd2e74-228e-59a2-aa27-59b154192c1d', 'BCA' ,         25000, '2025-03-30', 'Jember Expenses'       , 'Coffee'),
    ('e083c03a-6b51-5d39-ab36-cd28086b5421', 'BCA' ,         30800, '2025-03-31', 'Jember Expenses'       , 'Resto Rembangan'),
    ('172c98fc-d54f-510a-8510-ed64751f7386', 'BCA' ,         95500, '2025-03-31', 'Jember Expenses'       , 'GrabFood'),
    ('378a6e3d-50b7-564b-a40a-40ba1e2ef8f7', 'BCA' ,        580000, '2025-03-31', 'Jember Expenses'       , 'Jember Surabaya')
  ) AS v(id, acct, amount, date, category_name, description)
LEFT JOIN categories c ON c.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid AND c.name = v.category_name
ON CONFLICT (id) DO NOTHING;
COMMIT;

-- ============================================================
-- 2025-04  (13 transaction(s))
-- ============================================================
BEGIN;
INSERT INTO transactions
  (id, user_id, account_id, transfer_account_id, type, status,
   amount, description, date, category_id, budget_id, fixed_expense_id)
SELECT
  v.id::uuid, '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid,
  CASE v.acct WHEN 'BCA' THEN 'bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae'::uuid WHEN 'CARD' THEN '2f940480-5908-4c11-9fa1-9ff7a58c65c9'::uuid END,
  NULL,                       -- transfer_account_id (no transfers here)
  'expense'::transaction_type, 'confirmed',
  v.amount, v.description, v.date::date,
  c.id,                       -- category_id (matched by name)
  NULL, NULL                  -- budget_id, fixed_expense_id (n/a)
FROM (VALUES
    ('587b48a4-4a3e-55e9-aa01-da055fb230c1', 'BCA' ,         97911, '2025-04-01', 'Jember Expenses'       , 'Oleh oleh'),
    ('368fc47a-1b33-5c68-a076-7235f42d98f9', 'BCA' ,         30000, '2025-04-02', 'Jember Expenses'       , 'Cofy Coffee'),
    ('6f61fa72-9f33-5b14-b21b-f48cdf0e0f6c', 'BCA' ,         30000, '2025-04-02', 'Jember Expenses'       , 'KatsuQ'),
    ('9c1114e4-537e-502e-8e89-02a5308952e4', 'BCA' ,         18000, '2025-04-03', 'Jember Expenses'       , 'Blue Bird Taxi'),
    ('e820b6bc-6175-5b75-a12d-901b8e042503', 'BCA' ,         83000, '2025-04-03', 'Jember Expenses'       , 'Galaxy Mall Food'),
    ('3da5e77b-97cb-5cd2-bdbf-f3e47953dc00', 'BCA' ,         22500, '2025-04-04', 'Jember Expenses'       , 'E-Money'),
    ('a4ffa3bc-c4ac-515f-bf08-10e600d59585', 'BCA' ,        138700, '2025-04-04', 'Jember Expenses'       , 'Hokky'),
    ('4182d545-1e4e-5f23-9439-caf9b985c2f5', 'BCA' ,         22000, '2025-04-04', 'Jember Expenses'       , 'Coffee'),
    ('b64beacf-27de-5429-9548-387642ad9c46', 'BCA' ,        -70000, '2025-04-04', 'Jember Expenses'       , 'Transfer Lidya'),
    ('5856f331-1dea-54b7-bf09-268bd19f3180', 'BCA' ,        104300, '2025-04-05', 'Jember Expenses'       , 'XanhSM Taxi'),
    ('b8817d36-1821-5b00-8872-306384bbc0de', 'BCA' ,        140000, '2025-04-05', 'Jember Expenses'       , 'Living World Food'),
    ('df404e3d-8e51-50ca-b171-5a63c9a950b1', 'BCA' ,        576668, '2025-04-05', 'Jember Expenses'       , 'Jember OVO Expenses'),
    ('c09d900c-a574-5be6-a875-f254b4995cc4', 'BCA' ,        142743, '2025-04-20', 'Jawa Trip Expenses'    , 'Hotel Cirebon')
  ) AS v(id, acct, amount, date, category_name, description)
LEFT JOIN categories c ON c.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid AND c.name = v.category_name
ON CONFLICT (id) DO NOTHING;
COMMIT;

-- ============================================================
-- 2025-05  (1 transaction(s))
-- ============================================================
BEGIN;
INSERT INTO transactions
  (id, user_id, account_id, transfer_account_id, type, status,
   amount, description, date, category_id, budget_id, fixed_expense_id)
SELECT
  v.id::uuid, '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid,
  CASE v.acct WHEN 'BCA' THEN 'bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae'::uuid WHEN 'CARD' THEN '2f940480-5908-4c11-9fa1-9ff7a58c65c9'::uuid END,
  NULL,                       -- transfer_account_id (no transfers here)
  'expense'::transaction_type, 'confirmed',
  v.amount, v.description, v.date::date,
  c.id,                       -- category_id (matched by name)
  NULL, NULL                  -- budget_id, fixed_expense_id (n/a)
FROM (VALUES
    ('1df151f5-6c5d-59a6-a7be-5f2588ba90c9', 'BCA' ,       2755834, '2025-05-09', 'Jawa Trip Expenses'    , 'Bensin + EToll + Food')
  ) AS v(id, acct, amount, date, category_name, description)
LEFT JOIN categories c ON c.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid AND c.name = v.category_name
ON CONFLICT (id) DO NOTHING;
COMMIT;

-- ============================================================
-- 2025-06  (6 transaction(s))
-- ============================================================
BEGIN;
INSERT INTO transactions
  (id, user_id, account_id, transfer_account_id, type, status,
   amount, description, date, category_id, budget_id, fixed_expense_id)
SELECT
  v.id::uuid, '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid,
  CASE v.acct WHEN 'BCA' THEN 'bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae'::uuid WHEN 'CARD' THEN '2f940480-5908-4c11-9fa1-9ff7a58c65c9'::uuid END,
  NULL,                       -- transfer_account_id (no transfers here)
  'expense'::transaction_type, 'confirmed',
  v.amount, v.description, v.date::date,
  c.id,                       -- category_id (matched by name)
  NULL, NULL                  -- budget_id, fixed_expense_id (n/a)
FROM (VALUES
    ('24d74078-bf64-5cac-a01f-f1dc070fcbfe', 'BCA' ,    -155162000, '2025-06-01', 'Savings'               , 'Bonus'),
    ('da53e109-fd3b-586b-a141-6ca183d37d4e', 'BCA' ,     115568412, '2025-06-02', 'Car Expenses'          , 'Pelunasan dipercepat'),
    ('cc75d82f-4221-5c55-9f2d-5e457cd0349e', 'BCA' ,    -107861660, '2025-06-17', 'Savings'               , 'Grab Stock'),
    ('5356b9c7-7104-50bb-b3b2-c688b7baa6c5', 'BCA' ,     100000000, '2025-06-18', 'Savings'               , 'Superbank Deposit'),
    ('8454e958-ea42-510c-bbfb-fd69bbc5ea5b', 'BCA' ,      40000000, '2025-06-21', 'Savings'               , 'Superbank Deposit'),
    ('af30ead0-b268-5361-85b8-d725bf64b1ed', 'BCA' ,        997393, '2025-06-30', 'ExitLag'               , 'ExitLag')
  ) AS v(id, acct, amount, date, category_name, description)
LEFT JOIN categories c ON c.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid AND c.name = v.category_name
ON CONFLICT (id) DO NOTHING;
COMMIT;

-- ============================================================
-- 2025-07  (4 transaction(s))
-- ============================================================
BEGIN;
INSERT INTO transactions
  (id, user_id, account_id, transfer_account_id, type, status,
   amount, description, date, category_id, budget_id, fixed_expense_id)
SELECT
  v.id::uuid, '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid,
  CASE v.acct WHEN 'BCA' THEN 'bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae'::uuid WHEN 'CARD' THEN '2f940480-5908-4c11-9fa1-9ff7a58c65c9'::uuid END,
  NULL,                       -- transfer_account_id (no transfers here)
  'expense'::transaction_type, 'confirmed',
  v.amount, v.description, v.date::date,
  c.id,                       -- category_id (matched by name)
  NULL, NULL                  -- budget_id, fixed_expense_id (n/a)
FROM (VALUES
    ('0814c5fe-3648-50b6-be88-24c21924b553', 'BCA' ,      13850264, '2025-07-17', 'ROG Ally Update'       , 'ROG Ally X'),
    ('caba4c80-ef18-5085-af3b-1eb3e51a0750', 'BCA' ,        901100, '2025-07-18', 'ROG Ally Update'       , 'Bag Accessories'),
    ('bdf660d7-3bb4-5a6e-b364-7966dadb97c1', 'BCA' ,        325805, '2025-07-18', 'ROG Ally Update'       , 'Keyboard'),
    ('4361ec78-31cd-5b66-96ac-e13ec616dd31', 'BCA' ,      -9458053, '2025-07-31', 'ROG Ally Update'       , 'ROG Savings July 2025')
  ) AS v(id, acct, amount, date, category_name, description)
LEFT JOIN categories c ON c.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid AND c.name = v.category_name
ON CONFLICT (id) DO NOTHING;
COMMIT;

-- ============================================================
-- 2025-08  (2 transaction(s))
-- ============================================================
BEGIN;
INSERT INTO transactions
  (id, user_id, account_id, transfer_account_id, type, status,
   amount, description, date, category_id, budget_id, fixed_expense_id)
SELECT
  v.id::uuid, '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid,
  CASE v.acct WHEN 'BCA' THEN 'bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae'::uuid WHEN 'CARD' THEN '2f940480-5908-4c11-9fa1-9ff7a58c65c9'::uuid END,
  NULL,                       -- transfer_account_id (no transfers here)
  'expense'::transaction_type, 'confirmed',
  v.amount, v.description, v.date::date,
  c.id,                       -- category_id (matched by name)
  NULL, NULL                  -- budget_id, fixed_expense_id (n/a)
FROM (VALUES
    ('ba3568dd-7b29-54c9-a417-5b1c18a96687', 'BCA' ,      20000000, '2025-08-26', 'Housing 2025'          , 'UTJ'),
    ('45e2f4ea-f07d-5680-b30a-7434df264a10', 'BCA' ,      -1213890, '2025-08-31', 'Savings'               , 'Food Savings')
  ) AS v(id, acct, amount, date, category_name, description)
LEFT JOIN categories c ON c.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid AND c.name = v.category_name
ON CONFLICT (id) DO NOTHING;
COMMIT;

-- ============================================================
-- 2025-09  (3 transaction(s))
-- ============================================================
BEGIN;
INSERT INTO transactions
  (id, user_id, account_id, transfer_account_id, type, status,
   amount, description, date, category_id, budget_id, fixed_expense_id)
SELECT
  v.id::uuid, '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid,
  CASE v.acct WHEN 'BCA' THEN 'bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae'::uuid WHEN 'CARD' THEN '2f940480-5908-4c11-9fa1-9ff7a58c65c9'::uuid END,
  NULL,                       -- transfer_account_id (no transfers here)
  'expense'::transaction_type, 'confirmed',
  v.amount, v.description, v.date::date,
  c.id,                       -- category_id (matched by name)
  NULL, NULL                  -- budget_id, fixed_expense_id (n/a)
FROM (VALUES
    ('8b148bfa-d14f-5d24-a727-b18f8cee1c68', 'BCA' ,       -500000, '2025-09-02', 'Savings'               , 'Appraisal Bank Permata'),
    ('9df6b4ce-c7b0-5572-b2eb-29320b133260', 'BCA' ,        500000, '2025-09-02', 'Housing 2025'          , 'Appraisal Bank Permata'),
    ('1eec0bed-e3a3-5a02-bb3c-a7ee2ed75fd6', 'BCA' ,       1500000, '2025-09-27', 'Housing 2025'          , 'Appraisal BCA')
  ) AS v(id, acct, amount, date, category_name, description)
LEFT JOIN categories c ON c.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid AND c.name = v.category_name
ON CONFLICT (id) DO NOTHING;
COMMIT;

-- ============================================================
-- 2025-10  (14 transaction(s))
-- ============================================================
BEGIN;
INSERT INTO transactions
  (id, user_id, account_id, transfer_account_id, type, status,
   amount, description, date, category_id, budget_id, fixed_expense_id)
SELECT
  v.id::uuid, '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid,
  CASE v.acct WHEN 'BCA' THEN 'bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae'::uuid WHEN 'CARD' THEN '2f940480-5908-4c11-9fa1-9ff7a58c65c9'::uuid END,
  NULL,                       -- transfer_account_id (no transfers here)
  'expense'::transaction_type, 'confirmed',
  v.amount, v.description, v.date::date,
  c.id,                       -- category_id (matched by name)
  NULL, NULL                  -- budget_id, fixed_expense_id (n/a)
FROM (VALUES
    ('4a0b81d7-5d78-50fd-afc1-d2186a2a9afc', 'BCA' ,     -80000000, '2025-10-06', 'Savings'               , 'DP 2'),
    ('196e7db4-402c-5e4b-b3b5-517617fc2b5c', 'BCA' ,      80000000, '2025-10-06', 'Housing 2025'          , 'DP 2'),
    ('22e4732d-63f9-5dd3-a111-510d156f6683', 'BCA' ,      85000000, '2025-10-07', 'Housing 2025'          , 'DP 3'),
    ('066474ee-dc5b-5c4c-9041-fd9165a088cb', 'BCA' ,     -85000000, '2025-10-07', 'Savings'               , 'DP 3'),
    ('e133c826-4023-5af0-b5dc-254afb0f5dcf', 'BCA' ,      -5260000, '2025-10-14', 'Savings'               , 'AJB + Balik Nama'),
    ('1bfdcdb7-6653-544e-8f53-23cfc7f12a60', 'BCA' ,       5260000, '2025-10-14', 'Housing 2025'          , 'AJB + Balik Nama'),
    ('3b377238-509b-57f0-b818-ff47ed2b37be', 'BCA' ,     -75000000, '2025-10-20', 'Housing 2025'          , 'Lidya'),
    ('6c32050c-3dd1-5f06-80c1-02fb46c4c30c', 'BCA' ,      89000000, '2025-10-23', 'Housing 2025'          , 'BPHTB'),
    ('162839c7-e291-51b4-873d-f0ac3263b0a3', 'BCA' ,     -41671000, '2025-10-23', 'Savings'               , 'Superbank Deposit'),
    ('c580dda6-2f52-526d-86a4-b998f03b1da1', 'BCA' ,       8325000, '2025-10-31', 'Housing 2025'          , 'KPR Provisi'),
    ('92a52dbc-f0ad-5809-8f1f-0dae5f29add2', 'BCA' ,       1665000, '2025-10-31', 'Housing 2025'          , 'KPR ADM'),
    ('f7ffc718-750a-507d-9cb2-ca2b09952541', 'BCA' ,      16703280, '2025-10-31', 'Housing 2025'          , 'Asuransi Jiwa'),
    ('5b00ea85-26cb-56fc-bc9c-2d8a46e02438', 'BCA' ,       2379755, '2025-10-31', 'Housing 2025'          , 'Asuransi Kebakaran'),
    ('a03f9b80-d4a3-59de-89a0-a21f7cea09b2', 'BCA' ,      15010000, '2025-10-31', 'Housing 2025'          , 'Notaris')
  ) AS v(id, acct, amount, date, category_name, description)
LEFT JOIN categories c ON c.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid AND c.name = v.category_name
ON CONFLICT (id) DO NOTHING;
COMMIT;

-- ============================================================
-- 2025-11  (5 transaction(s))
-- ============================================================
BEGIN;
INSERT INTO transactions
  (id, user_id, account_id, transfer_account_id, type, status,
   amount, description, date, category_id, budget_id, fixed_expense_id)
SELECT
  v.id::uuid, '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid,
  CASE v.acct WHEN 'BCA' THEN 'bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae'::uuid WHEN 'CARD' THEN '2f940480-5908-4c11-9fa1-9ff7a58c65c9'::uuid END,
  NULL,                       -- transfer_account_id (no transfers here)
  'expense'::transaction_type, 'confirmed',
  v.amount, v.description, v.date::date,
  c.id,                       -- category_id (matched by name)
  NULL, NULL                  -- budget_id, fixed_expense_id (n/a)
FROM (VALUES
    ('d94048b5-f7d5-5bd0-b65b-a8fb58aac59c', 'BCA' ,       1700000, '2025-11-14', 'Surabaya Expenses'     , 'Tiket Kereta'),
    ('708a98d5-97b7-5753-98a9-3d5e9c266fad', 'BCA' ,       1740000, '2025-11-15', 'Surabaya Expenses'     , 'Tiket Bus'),
    ('6bc45cdd-af5a-53f2-9b62-d4c93f172e61', 'BCA' ,       -850000, '2025-11-16', 'Surabaya Expenses'     , 'Tiket Bus Lidya'),
    ('d44377a8-d0f3-5e2d-8a45-5f0f711e865c', 'BCA' ,       3241496, '2025-11-16', 'Surabaya Expenses'     , 'Hotel'),
    ('13356f3d-b5e0-503a-a4bc-73936d6753e6', 'BCA' ,       7500000, '2025-11-29', 'Wedding'               , 'Kalung')
  ) AS v(id, acct, amount, date, category_name, description)
LEFT JOIN categories c ON c.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid AND c.name = v.category_name
ON CONFLICT (id) DO NOTHING;
COMMIT;

-- ============================================================
-- 2025-12  (2 transaction(s))
-- ============================================================
BEGIN;
INSERT INTO transactions
  (id, user_id, account_id, transfer_account_id, type, status,
   amount, description, date, category_id, budget_id, fixed_expense_id)
SELECT
  v.id::uuid, '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid,
  CASE v.acct WHEN 'BCA' THEN 'bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae'::uuid WHEN 'CARD' THEN '2f940480-5908-4c11-9fa1-9ff7a58c65c9'::uuid END,
  NULL,                       -- transfer_account_id (no transfers here)
  'expense'::transaction_type, 'confirmed',
  v.amount, v.description, v.date::date,
  c.id,                       -- category_id (matched by name)
  NULL, NULL                  -- budget_id, fixed_expense_id (n/a)
FROM (VALUES
    ('19287d63-970f-549d-b03d-7f363dec75b6', 'BCA' ,       3080000, '2025-12-21', 'Surabaya Expenses'     , 'Tiket Kereta'),
    ('d51671d0-0c74-514b-abeb-85feca1576c2', 'BCA' ,       8585760, '2025-12-21', 'Secret Lab'            , 'Secret lab')
  ) AS v(id, acct, amount, date, category_name, description)
LEFT JOIN categories c ON c.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid AND c.name = v.category_name
ON CONFLICT (id) DO NOTHING;
COMMIT;

-- ============================================================
-- 2026-01  (7 transaction(s))
-- ============================================================
BEGIN;
INSERT INTO transactions
  (id, user_id, account_id, transfer_account_id, type, status,
   amount, description, date, category_id, budget_id, fixed_expense_id)
SELECT
  v.id::uuid, '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid,
  CASE v.acct WHEN 'BCA' THEN 'bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae'::uuid WHEN 'CARD' THEN '2f940480-5908-4c11-9fa1-9ff7a58c65c9'::uuid END,
  NULL,                       -- transfer_account_id (no transfers here)
  'expense'::transaction_type, 'confirmed',
  v.amount, v.description, v.date::date,
  c.id,                       -- category_id (matched by name)
  NULL, NULL                  -- budget_id, fixed_expense_id (n/a)
FROM (VALUES
    ('9af1dabf-7db7-5a36-a2ba-eb81d96b604d', 'BCA' ,     -14078000, '2026-01-01', 'Savings'               , 'Superbank Deposit'),
    ('b8570ea4-7688-54ff-9f04-8e520b4ca77f', 'BCA' ,        599000, '2026-01-04', 'Fashion'               , 'Celana'),
    ('226c422e-79c3-51e7-b10b-71b562b2bcd1', 'BCA' ,        247401, '2026-01-04', 'Fashion'               , 'Sepatu'),
    ('638631d4-3d4b-5eb8-b7ef-2cf6f9c4a3e9', 'BCA' ,       5282500, '2026-01-08', 'SQ Parking'            , 'Parkir Jan-Dec 2026'),
    ('13988da5-32ce-564d-8302-8b2a28d1c976', 'BCA' ,       1600000, '2026-01-20', 'Wedding'               , 'Jember Ticket'),
    ('39549045-34fd-5a5e-8b6b-be17468822d5', 'BCA' ,        177500, '2026-01-21', 'Wedding'               , 'Kertanegara'),
    ('e8d9c76d-85e0-597a-bca9-6501ff1a700e', 'BCA' ,        375000, '2026-01-21', 'Wedding'               , 'Hotel Anda')
  ) AS v(id, acct, amount, date, category_name, description)
LEFT JOIN categories c ON c.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid AND c.name = v.category_name
ON CONFLICT (id) DO NOTHING;
COMMIT;

-- ============================================================
-- 2026-02  (16 transaction(s))
-- ============================================================
BEGIN;
INSERT INTO transactions
  (id, user_id, account_id, transfer_account_id, type, status,
   amount, description, date, category_id, budget_id, fixed_expense_id)
SELECT
  v.id::uuid, '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid,
  CASE v.acct WHEN 'BCA' THEN 'bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae'::uuid WHEN 'CARD' THEN '2f940480-5908-4c11-9fa1-9ff7a58c65c9'::uuid END,
  NULL,                       -- transfer_account_id (no transfers here)
  'expense'::transaction_type, 'confirmed',
  v.amount, v.description, v.date::date,
  c.id,                       -- category_id (matched by name)
  NULL, NULL                  -- budget_id, fixed_expense_id (n/a)
FROM (VALUES
    ('800d7d9c-edaf-5774-bb54-64d8a93ee47a', 'BCA' ,       5800000, '2026-02-07', 'Artiz Studio'          , 'Artiz Studio'),
    ('b689eb61-1e9d-5c31-8cf9-3f089c4d6769', 'BCA' ,        948473, '2026-02-09', 'Secret Lab'            , 'Lumbar support'),
    ('418762ee-8c1a-5af6-9a6d-d134958a2603', 'BCA' ,        840834, '2026-02-10', 'MRT Cikarang'          , 'Hotel'),
    ('a0699b40-e5e5-55de-830f-3210ea1af2ff', 'BCA' ,        286000, '2026-02-13', 'MRT Cikarang'          , 'Grab'),
    ('1e80744b-2732-5fe7-80df-576ae6dfdafa', 'BCA' ,        202500, '2026-02-13', 'MRT Cikarang'          , 'E-Toll'),
    ('513edd10-3833-568d-a08c-54dfb7d5ee1b', 'BCA' ,         14000, '2026-02-14', 'MRT Cikarang'          , 'Grab'),
    ('39e1adc7-a24f-564a-a8b6-29a49c2b6a7d', 'BCA' ,         12000, '2026-02-15', 'MRT Cikarang'          , 'Grab'),
    ('2bc49903-9cbc-5733-a179-be4c8733f81f', 'BCA' ,         64000, '2026-02-15', 'MRT Cikarang'          , 'Grab'),
    ('959ee471-d929-58ef-bd56-b9bdd19641d0', 'BCA' ,        -50000, '2026-02-16', 'MRT Cikarang'          , 'Prize'),
    ('8ab3a6ca-63ec-5ef3-bd05-227ddb791e8f', 'BCA' ,        177500, '2026-02-16', 'Wedding'               , 'Kertanegara'),
    ('54702064-fce6-5fb3-b305-3f3dea03fdea', 'BCA' ,       1000000, '2026-02-17', 'Wedding'               , 'TMI DP'),
    ('a45cb0ae-1bd7-56da-a412-c27bdd0894d7', 'BCA' ,        375000, '2026-02-17', 'Wedding'               , 'Hotel Anda'),
    ('53cd9033-79c9-5913-a35f-3e74636ec10f', 'BCA' ,      10000000, '2026-02-19', 'Wedding'               , 'Ring DP'),
    ('4f8d2414-2f45-55a2-8421-7e4a8922efe7', 'BCA' ,        108000, '2026-02-21', 'Wedding'               , 'Grab to Home'),
    ('e7ed3ac7-71ac-525d-b3d4-bb5a297c1cbb', 'BCA' ,      16000000, '2026-02-27', 'Wedding'               , 'Ring'),
    ('6aecbb29-81cd-5761-98f4-7b06ab579c70', 'BCA' ,       4000000, '2026-02-27', 'Wedding'               , 'Decor + MC')
  ) AS v(id, acct, amount, date, category_name, description)
LEFT JOIN categories c ON c.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid AND c.name = v.category_name
ON CONFLICT (id) DO NOTHING;
COMMIT;

-- ============================================================
-- 2026-03  (10 transaction(s))
-- ============================================================
BEGIN;
INSERT INTO transactions
  (id, user_id, account_id, transfer_account_id, type, status,
   amount, description, date, category_id, budget_id, fixed_expense_id)
SELECT
  v.id::uuid, '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid,
  CASE v.acct WHEN 'BCA' THEN 'bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae'::uuid WHEN 'CARD' THEN '2f940480-5908-4c11-9fa1-9ff7a58c65c9'::uuid END,
  NULL,                       -- transfer_account_id (no transfers here)
  'expense'::transaction_type, 'confirmed',
  v.amount, v.description, v.date::date,
  c.id,                       -- category_id (matched by name)
  NULL, NULL                  -- budget_id, fixed_expense_id (n/a)
FROM (VALUES
    ('eb0afb6f-5f16-58d2-a5b2-750e0d47fa01', 'BCA' ,       1695885, '2026-03-01', 'Software Development'  , 'Apple Developer'),
    ('87df2743-b708-5796-a248-71fee0a781ec', 'BCA' ,        281500, '2026-03-01', 'STNK'                  , 'STNK Motor'),
    ('a92852da-95ac-52a1-a678-623e4eb3a465', 'BCA' ,        642443, '2026-03-05', 'PBB Alegria'           , 'PBB Alegria'),
    ('8afb9e05-be9a-56df-8fcc-b52f3852abba', 'BCA' ,       7752500, '2026-03-05', 'House Renovation'      , 'Deposit Alegria'),
    ('ad7b9dec-2dfb-5f8d-b7b7-07631c49d2bf', 'BCA' ,      -6000000, '2026-03-07', 'ROG Ally Update'       , 'Steam Deck Sold'),
    ('c680d3ff-3188-50ad-b347-6819ada6f24b', 'BCA' ,      17387180, '2026-03-13', 'iPhone Air'            , 'iPhone Air'),
    ('4e8a5250-ebea-5d09-bb27-c2f6f43111ea', 'BCA' ,       6939639, '2026-03-23', 'Digivice'              , 'D-Ark 25th'),
    ('85931737-a8cb-56ef-a8de-e698d854b98c', 'BCA' ,     -42525000, '2026-03-23', 'Savings'               , 'THR'),
    ('fb6f51ac-bf28-5d91-bf9e-7d67b527718d', 'BCA' ,        365200, '2026-03-18', 'Google One'            , 'Google One Subscription'),
    ('f6ba679b-877a-5d42-ace9-b8c31239e06a', 'BCA' ,       1000000, '2026-03-24', 'Wedding'               , 'Aston DP')
  ) AS v(id, acct, amount, date, category_name, description)
LEFT JOIN categories c ON c.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid AND c.name = v.category_name
ON CONFLICT (id) DO NOTHING;
COMMIT;

-- ============================================================
-- 2026-04  (31 transaction(s), 5 tagged duplicate(s))
-- ============================================================
BEGIN;
INSERT INTO transactions
  (id, user_id, account_id, transfer_account_id, type, status,
   amount, description, date, category_id, budget_id, fixed_expense_id)
SELECT
  v.id::uuid, '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid,
  CASE v.acct WHEN 'BCA' THEN 'bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae'::uuid WHEN 'CARD' THEN '2f940480-5908-4c11-9fa1-9ff7a58c65c9'::uuid END,
  NULL,                       -- transfer_account_id (no transfers here)
  'expense'::transaction_type, 'confirmed',
  v.amount, v.description, v.date::date,
  c.id,                       -- category_id (matched by name)
  NULL, NULL                  -- budget_id, fixed_expense_id (n/a)
FROM (VALUES
    ('1bc8585b-2fb0-56b3-8227-e21c68b9ad91', 'BCA' ,     -77403441, '2026-04-01', 'Savings'               , 'Bonus'),
    ('9acd3fc0-cdf9-5cc5-93f8-3433b6359811', 'BCA' ,       1198752, '2026-04-04', 'Shoes'                 , 'Crocs'),  -- Also in monthly 2026-04 sheet — kept HERE as the source; the monthly row is commented out (see overlaps-2026-04.md)
    ('35fe6158-1917-5107-973f-88b2b4a9ab72', 'BCA' ,       2679963, '2026-04-04', 'Secret Lab'            , 'Recliner'),  -- Also in monthly 2026-04 sheet — kept HERE as the source; the monthly row is commented out (see overlaps-2026-04.md)
    ('b5aefbba-54ce-58df-a0c4-04f9e0873163', 'BCA' ,        472184, '2026-04-04', 'Bluetooth Keyboard'    , 'Bluetooth Keyboard'),  -- Also in monthly 2026-04 sheet — kept HERE as the source; the monthly row is commented out (see overlaps-2026-04.md)
    ('a5c50c70-d44b-5068-9be1-89d0bac7f1c0', 'BCA' ,      16099749, '2026-04-05', 'House Renovation'      , 'Material Dunia Bangunan'),  -- Also in monthly 2026-04 sheet — kept HERE as the source; the monthly row is commented out (see overlaps-2026-04.md)
    ('ceb67230-631d-53fe-8f6a-dfeca44e2276', 'BCA' ,       5000000, '2026-04-05', 'House Renovation'      , 'DP Contractor'),
    ('99209c4b-c741-5602-beee-e9cf1c22ca16', 'BCA' ,        400000, '2026-04-08', 'House Renovation'      , 'DP Kusen'),
    ('468690aa-5ee4-5067-9eea-8418650ab45a', 'BCA' ,       4075000, '2026-04-10', 'House Renovation'      , 'Material'),
    ('54c1ebe7-422f-5ca1-9727-e6107b176875', 'BCA' ,       1105000, '2026-04-10', 'House Renovation'      , 'Besi Wiremesh'),
    ('c4e72d8b-0121-5ad4-9779-286f792cdc71', 'BCA' ,       5000000, '2026-04-10', 'House Renovation'      , 'Contractor 1'),
    ('26da6a08-cdb3-52fb-b09f-cb511819b2a7', 'BCA' ,       1700000, '2026-04-11', 'House Renovation'      , 'Pasir Semen'),
    ('e6ce91d5-5451-5fc0-93ef-2621d3c8ee40', 'BCA' ,        554484, '2026-04-18', 'House Renovation'      , 'Keramik'),  -- Also in monthly 2026-04 sheet — kept HERE as the source; the monthly row is commented out (see overlaps-2026-04.md)
    ('a7b62dc1-a931-5c5a-a5d7-adc7069f9b53', 'BCA' ,        561000, '2026-04-12', 'House Renovation'      , NULL),
    ('9c26b1f8-64df-59c5-bae3-9db7b42ef94b', 'BCA' ,        160000, '2026-04-13', 'House Renovation'      , NULL),
    ('f74ce7b0-175c-5c5f-b6c2-a9122600b145', 'BCA' ,       3628000, '2026-04-13', 'House Renovation'      , NULL),
    ('a4fef0c5-97fe-59b5-9a6c-c8c4171a7092', 'BCA' ,       3026000, '2026-04-13', 'House Renovation'      , NULL),
    ('63caae1f-a4f7-5e67-8cea-0a2c17f64568', 'BCA' ,        305000, '2026-04-13', 'House Renovation'      , NULL),
    ('d85d6ad7-813a-5317-b408-15b3c3b1e762', 'BCA' ,        300000, '2026-04-15', 'House Renovation'      , NULL),
    ('b62ff3c1-7a9d-5072-a85d-466ad10d38c1', 'BCA' ,        535000, '2026-04-16', 'House Renovation'      , NULL),
    ('39f604a7-48e5-515c-8b49-1cb6b88b4a78', 'BCA' ,        135000, '2026-04-16', 'House Renovation'      , NULL),
    ('aa4f6f11-619e-54f8-b709-d78c36c2400f', 'BCA' ,        705000, '2026-04-17', 'House Renovation'      , NULL),
    ('c5737283-3d91-592f-aa89-3aa7c408db2d', 'BCA' ,      10000000, '2026-04-17', 'House Renovation'      , 'Contractor 2'),
    ('bec5c32c-247d-5c72-b253-cb06a3460803', 'BCA' ,        230000, '2026-04-20', 'House Renovation'      , NULL),
    ('1a03b4c3-d028-589d-a820-c44e4e151009', 'BCA' ,        475000, '2026-04-21', 'House Renovation'      , NULL),
    ('0c3219a0-44d7-5c6f-a314-2b15e013dadb', 'BCA' ,        310000, '2026-04-21', 'House Renovation'      , NULL),
    ('42e912d2-fb6d-51e7-895b-4ce9b9b1c7d5', 'BCA' ,       2000000, '2026-04-23', 'House Renovation'      , NULL),
    ('dc3961a2-326f-58ce-b193-a5f84f16333f', 'BCA' ,        230000, '2026-04-23', 'House Renovation'      , NULL),
    ('4af60c51-8e2f-5969-a6f1-c8006334b310', 'BCA' ,       7000000, '2026-04-24', 'House Renovation'      , 'Contractor 3'),
    ('27670128-1713-5506-bcab-2818b890acc3', 'BCA' ,        209000, '2026-04-24', 'House Renovation'      , NULL),
    ('a0baec0d-37d5-5354-8e97-f6134ea2e602', 'BCA' ,        846000, '2026-04-29', 'House Renovation'      , NULL),
    ('39a722a8-5790-5672-999b-a8209e7a53dc', 'BCA' ,        654000, '2026-04-29', 'House Renovation'      , NULL)
  ) AS v(id, acct, amount, date, category_name, description)
LEFT JOIN categories c ON c.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid AND c.name = v.category_name
ON CONFLICT (id) DO NOTHING;
COMMIT;

-- ============================================================
-- 2026-05  (29 transaction(s), 10 tagged duplicate(s))
-- ============================================================
BEGIN;
INSERT INTO transactions
  (id, user_id, account_id, transfer_account_id, type, status,
   amount, description, date, category_id, budget_id, fixed_expense_id)
SELECT
  v.id::uuid, '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid,
  CASE v.acct WHEN 'BCA' THEN 'bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae'::uuid WHEN 'CARD' THEN '2f940480-5908-4c11-9fa1-9ff7a58c65c9'::uuid END,
  NULL,                       -- transfer_account_id (no transfers here)
  'expense'::transaction_type, 'confirmed',
  v.amount, v.description, v.date::date,
  c.id,                       -- category_id (matched by name)
  NULL, NULL                  -- budget_id, fixed_expense_id (n/a)
FROM (VALUES
    ('f31a20da-bc06-5f3b-ac49-0e75b3512ec3', 'BCA' ,       6000000, '2026-05-01', 'House Renovation'      , 'Contractor 4'),
    ('595879a8-666d-5a6b-83ec-20a622e057e3', 'BCA' ,        204700, '2026-05-03', 'House Renovation'      , NULL),  -- Also in monthly 2026-05 sheet — kept HERE as the source; the monthly row is commented out (see overlaps-2026-05.md)
    ('2394aaff-e348-56e0-80d4-eb1d7630b6fa', 'BCA' ,        138400, '2026-05-03', 'House Renovation'      , NULL),
    ('ee72ff50-ee28-5c0c-9674-aafcd7f590ff', 'BCA' ,        328246, '2026-05-06', 'House Renovation'      , NULL),  -- Also in monthly 2026-05 sheet — kept HERE as the source; the monthly row is commented out (see overlaps-2026-05.md)
    ('0e3cdea8-600a-5aa4-924b-b0167ad67174', 'BCA' ,       1022000, '2026-05-05', 'House Renovation'      , NULL),
    ('5e84a148-4a4b-51c1-a4c0-44d55752ca5f', 'BCA' ,        230000, '2026-05-07', 'House Renovation'      , 'Car Charger'),
    ('914ca0b5-7fac-5054-99e5-13531bcc0ec0', 'BCA' ,      12228980, '2026-05-08', 'House Renovation'      , 'Car Charger KWH NIDI SLO'),
    ('c605bdd4-d33b-5026-bec7-81c96edfb13f', 'BCA' ,      10000000, '2026-05-08', 'House Renovation'      , 'Contractor 5'),
    ('ce0b9192-a829-5486-9f8f-745f9c5e2071', 'BCA' ,        342430, '2026-05-13', 'House Renovation'      , 'Tangga Rumah Lipat'),  -- Also in monthly 2026-05 sheet — kept HERE as the source; the monthly row is commented out (see overlaps-2026-05.md)
    ('6c3686d3-2807-54a8-b309-90ff251bced7', 'BCA' ,       1456000, '2026-05-11', 'House Renovation'      , 'Pipa + Paket Grounding'),
    ('d840fc46-7a75-54b5-b1ff-24b0ddcc8cff', 'BCA' ,        994000, '2026-05-11', 'House Renovation'      , NULL),
    ('9642b98a-69ab-590b-9471-ce12f9100d52', 'BCA' ,     -30000000, '2026-05-11', 'ST012T2'               , NULL),
    ('9a3f4ea2-867a-5b56-a650-db0b53029933', 'BCA' ,        580000, '2026-05-12', 'House Renovation'      , 'Car Charger Fuse 63A'),
    ('ee6fbd6d-6d8a-5c7b-b2e0-d02efe8083eb', 'BCA' ,       1500000, '2026-05-13', 'House Renovation'      , 'Car Charger Move'),
    ('bbd5603b-f618-576b-a40f-f4f89b84d1f0', 'BCA' ,       2900000, '2026-05-15', 'House Renovation'      , NULL),
    ('187e0184-b120-5b12-b0c2-91f8d4392f19', 'BCA' ,        500000, '2026-05-15', 'House Renovation'      , 'Pintu Kawat Nyamuk'),
    ('0ffc28f7-7c03-51cd-a157-57969cd97aa5', 'BCA' ,       4300973, '2026-05-16', 'House Renovation'      , 'TTRacing Titus X'),  -- Also in monthly 2026-05 sheet — kept HERE as the source; the monthly row is commented out (see overlaps-2026-05.md)
    ('b5c561e2-fc87-5338-8815-fa70ef05e137', 'BCA' ,       1431500, '2026-05-18', 'House Renovation'      , 'TP Link'),  -- Also in monthly 2026-05 sheet — kept HERE as the source; the monthly row is commented out (see overlaps-2026-05.md)
    ('e5544a31-b522-5391-a5cb-807e38caeb3a', 'BCA' ,       1000000, '2026-05-18', 'House Renovation'      , 'Pintu Kawat Nyamuk'),
    ('6759ca81-5954-544e-b114-373714bb267b', 'BCA' ,        269705, '2026-05-20', 'House Renovation'      , 'Vention Cable Management'),  -- Also in monthly 2026-05 sheet — kept HERE as the source; the monthly row is commented out (see overlaps-2026-05.md)
    ('2c3b9781-b73b-5ddd-b27b-bcab5a848eb2', 'BCA' ,        107982, '2026-05-20', 'House Renovation'      , 'Cable Management'),  -- Also in monthly 2026-05 sheet — kept HERE as the source; the monthly row is commented out (see overlaps-2026-05.md)
    ('ff3d1827-f82d-55e1-86ce-0b3110e59c4d', 'BCA' ,       1026422, '2026-05-23', 'PIA'                   , 'PIA'),  -- Also in monthly 2026-05 sheet — kept HERE as the source; the monthly row is commented out (see overlaps-2026-05.md)
    ('c8ed088a-6876-5dd7-8244-0ed53d2d5d6e', 'BCA' ,      27213000, '2026-05-24', 'House Renovation'      , 'IKEA'),  -- Also in monthly 2026-05 sheet — kept HERE as the source; the monthly row is commented out (see overlaps-2026-05.md)
    ('3d70d92b-ef55-5bc1-819f-11ff862a7625', 'BCA' ,        901500, '2026-05-24', 'House Renovation'      , 'Headboard'),  -- Also in monthly 2026-05 sheet — kept HERE as the source; the monthly row is commented out (see overlaps-2026-05.md)
    ('03f485cb-993b-577a-a005-7b6375ecef4e', 'BCA' ,       8500000, '2026-05-22', 'House Renovation'      , 'Lemari Gantung'),
    ('731ea45a-a372-57c8-8f49-cc655e703ea9', 'BCA' ,       2800000, '2026-05-22', 'House Renovation'      , 'Pintu Kawat Nyamuk + Lemari Gantung + Rumput'),
    ('8875d99b-53b2-55f7-baa5-5dabbe4bcf90', 'BCA' ,       3400000, '2026-05-22', 'House Renovation'      , 'Onna'),
    ('bf09983a-7204-5565-a07b-0299bc845570', 'BCA' ,       3307613, '2026-05-28', 'House Renovation'      , 'Onna'),
    ('82104f85-f0dc-5128-8851-0241bcdcc4e2', 'BCA' ,        700000, '2026-05-30', 'House Renovation'      , 'Pindahan')
  ) AS v(id, acct, amount, date, category_name, description)
LEFT JOIN categories c ON c.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid AND c.name = v.category_name
ON CONFLICT (id) DO NOTHING;
COMMIT;

-- ============================================================
-- 2026-06  (5 transaction(s))
-- ============================================================
BEGIN;
INSERT INTO transactions
  (id, user_id, account_id, transfer_account_id, type, status,
   amount, description, date, category_id, budget_id, fixed_expense_id)
SELECT
  v.id::uuid, '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid,
  CASE v.acct WHEN 'BCA' THEN 'bfc92cd3-0eb3-497d-a7c2-7e7eb669e2ae'::uuid WHEN 'CARD' THEN '2f940480-5908-4c11-9fa1-9ff7a58c65c9'::uuid END,
  NULL,                       -- transfer_account_id (no transfers here)
  'expense'::transaction_type, 'confirmed',
  v.amount, v.description, v.date::date,
  c.id,                       -- category_id (matched by name)
  NULL, NULL                  -- budget_id, fixed_expense_id (n/a)
FROM (VALUES
    ('3cd2f7fc-65ff-5efd-a34a-236ffea3d2b6', 'BCA' ,        250000, '2026-06-01', 'House Renovation'      , 'Kasur'),
    ('d0128c47-3c33-5dbd-863f-3be674b3196c', 'BCA' ,     -11000000, '2026-06-01', 'House Renovation'      , 'From Lidya for Kasur'),
    ('cc9a66b0-8da1-5e37-bc7d-2226834660a3', 'BCA' ,      10600000, '2026-06-01', 'House Renovation'      , 'Kasur'),
    ('4786e8dd-d365-5787-b195-65a8c1b02e41', 'BCA' ,        700200, '2026-06-01', 'House Renovation'      , 'Tools'),
    ('c5a3e64c-1741-5488-a21f-7b0c6ea2650c', 'BCA' ,        391070, '2026-06-03', 'Software Development'  , 'Claude')
  ) AS v(id, acct, amount, date, category_name, description)
LEFT JOIN categories c ON c.user_id = '9e36aab2-dc6e-4ff6-9ae1-c81e82225424'::uuid AND c.name = v.category_name
ON CONFLICT (id) DO NOTHING;
COMMIT;

